/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: "@scaleway/sdk-jobs",
  namespace: "jobs",
  displayName: "Jobs",
  versions: ["v1alpha1", "v1alpha2"]
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
