/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: '@scaleway/sdk-mongodb',
  namespace: 'mongodb',
  displayName: 'Mongodb',
  versions: ['v1', 'v1alpha1'],
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
