/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: '@scaleway/sdk-test',
  namespace: 'test',
  displayName: 'Test',
  versions: ['v1'],
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
