// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'mnq',
  version: 'v1beta1',
  folderName: 'mnqv1beta1',
  services: [
    {
      apiClass: 'NatsAPI',
      methods: [
        {
          methodName: 'getNatsAccount',
          protoName: 'GetNatsAccount',
          paramsType: 'NatsApiGetNatsAccountRequest',
          returnType: 'NatsAccount',
          returnTypeNamespace: '@scaleway/sdk-mnq/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listNatsAccounts',
          protoName: 'ListNatsAccounts',
          paramsType: 'NatsApiListNatsAccountsRequest',
          returnType: 'ListNatsAccountsResponse',
          returnTypeNamespace: '@scaleway/sdk-mnq/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'NatsAccount',
          listItemTypeNamespace: '@scaleway/sdk-mnq/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getNatsCredentials',
          protoName: 'GetNatsCredentials',
          paramsType: 'NatsApiGetNatsCredentialsRequest',
          returnType: 'NatsCredentials',
          returnTypeNamespace: '@scaleway/sdk-mnq/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listNatsCredentials',
          protoName: 'ListNatsCredentials',
          paramsType: 'NatsApiListNatsCredentialsRequest',
          returnType: 'ListNatsCredentialsResponse',
          returnTypeNamespace: '@scaleway/sdk-mnq/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'NatsCredentials',
          listItemTypeNamespace: '@scaleway/sdk-mnq/v1beta1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'SnsAPI',
      methods: [
        {
          methodName: 'getSnsInfo',
          protoName: 'GetSnsInfo',
          paramsType: 'SnsApiGetSnsInfoRequest',
          returnType: 'SnsInfo',
          returnTypeNamespace: '@scaleway/sdk-mnq/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSnsCredentials',
          protoName: 'GetSnsCredentials',
          paramsType: 'SnsApiGetSnsCredentialsRequest',
          returnType: 'SnsCredentials',
          returnTypeNamespace: '@scaleway/sdk-mnq/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSnsCredentials',
          protoName: 'ListSnsCredentials',
          paramsType: 'SnsApiListSnsCredentialsRequest',
          returnType: 'ListSnsCredentialsResponse',
          returnTypeNamespace: '@scaleway/sdk-mnq/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'SnsCredentials',
          listItemTypeNamespace: '@scaleway/sdk-mnq/v1beta1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'SqsAPI',
      methods: [
        {
          methodName: 'getSqsInfo',
          protoName: 'GetSqsInfo',
          paramsType: 'SqsApiGetSqsInfoRequest',
          returnType: 'SqsInfo',
          returnTypeNamespace: '@scaleway/sdk-mnq/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSqsCredentials',
          protoName: 'GetSqsCredentials',
          paramsType: 'SqsApiGetSqsCredentialsRequest',
          returnType: 'SqsCredentials',
          returnTypeNamespace: '@scaleway/sdk-mnq/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSqsCredentials',
          protoName: 'ListSqsCredentials',
          paramsType: 'SqsApiListSqsCredentialsRequest',
          returnType: 'ListSqsCredentialsResponse',
          returnTypeNamespace: '@scaleway/sdk-mnq/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'SqsCredentials',
          listItemTypeNamespace: '@scaleway/sdk-mnq/v1beta1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
