/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: '@scaleway/sdk-function',
  namespace: 'function',
  displayName: 'Function',
  versions: ['v1beta1'],
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
