// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.
export { API } from './api.gen'
export type {
  AddSubnetsRequest,
  AddSubnetsResponse,
  CreatePrivateNetworkRequest,
  CreateVPCRequest,
  DeletePrivateNetworkRequest,
  DeleteSubnetsRequest,
  DeleteSubnetsResponse,
  DeleteVPCRequest,
  EnableDHCPRequest,
  EnableRoutingRequest,
  GetPrivateNetworkRequest,
  GetVPCRequest,
  ListPrivateNetworksRequest,
  ListPrivateNetworksRequestOrderBy,
  ListPrivateNetworksResponse,
  ListVPCsRequest,
  ListVPCsRequestOrderBy,
  ListVPCsResponse,
  MigrateZonalPrivateNetworksRequest,
  PrivateNetwork,
  SetSubnetsRequest,
  SetSubnetsResponse,
  Subnet,
  UpdatePrivateNetworkRequest,
  UpdateVPCRequest,
  VPC,
} from './types.gen'
