// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'instance',
  version: 'v1',
  folderName: 'instancev1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'getServerTypesAvailability',
          protoName: 'GetServerTypesAvailability',
          paramsType: 'GetServerTypesAvailabilityRequest',
          returnType: 'GetServerTypesAvailabilityResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listServersTypes',
          protoName: 'ListServersTypes',
          paramsType: 'ListServersTypesRequest',
          returnType: 'ListServersTypesResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listVolumesTypes',
          protoName: 'ListVolumesTypes',
          paramsType: 'ListVolumesTypesRequest',
          returnType: 'ListVolumesTypesResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listServers',
          protoName: 'ListServers',
          paramsType: 'ListServersRequest',
          returnType: 'ListServersResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Server',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getServer',
          protoName: 'GetServer',
          paramsType: 'GetServerRequest',
          returnType: 'GetServerResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listServerActions',
          protoName: 'ListServerActions',
          paramsType: 'ListServerActionsRequest',
          returnType: 'ListServerActionsResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listServerUserData',
          protoName: 'ListServerUserData',
          paramsType: 'ListServerUserDataRequest',
          returnType: 'ListServerUserDataResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getServerCompatibleTypes',
          protoName: 'GetServerCompatibleTypes',
          paramsType: 'GetServerCompatibleTypesRequest',
          returnType: 'ServerCompatibleTypes',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listImages',
          protoName: 'ListImages',
          paramsType: 'ListImagesRequest',
          returnType: 'ListImagesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Image',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getImage',
          protoName: 'GetImage',
          paramsType: 'GetImageRequest',
          returnType: 'GetImageResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSnapshots',
          protoName: 'ListSnapshots',
          paramsType: 'ListSnapshotsRequest',
          returnType: 'ListSnapshotsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Snapshot',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSnapshot',
          protoName: 'GetSnapshot',
          paramsType: 'GetSnapshotRequest',
          returnType: 'GetSnapshotResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listVolumes',
          protoName: 'ListVolumes',
          paramsType: 'ListVolumesRequest',
          returnType: 'ListVolumesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Volume',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getVolume',
          protoName: 'GetVolume',
          paramsType: 'GetVolumeRequest',
          returnType: 'GetVolumeResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSecurityGroups',
          protoName: 'ListSecurityGroups',
          paramsType: 'ListSecurityGroupsRequest',
          returnType: 'ListSecurityGroupsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'SecurityGroup',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSecurityGroup',
          protoName: 'GetSecurityGroup',
          paramsType: 'GetSecurityGroupRequest',
          returnType: 'GetSecurityGroupResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDefaultSecurityGroupRules',
          protoName: 'ListDefaultSecurityGroupRules',
          paramsType: 'ListDefaultSecurityGroupRulesRequest',
          returnType: 'ListSecurityGroupRulesResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSecurityGroupRules',
          protoName: 'ListSecurityGroupRules',
          paramsType: 'ListSecurityGroupRulesRequest',
          returnType: 'ListSecurityGroupRulesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'SecurityGroupRule',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSecurityGroupRule',
          protoName: 'GetSecurityGroupRule',
          paramsType: 'GetSecurityGroupRuleRequest',
          returnType: 'GetSecurityGroupRuleResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listPlacementGroups',
          protoName: 'ListPlacementGroups',
          paramsType: 'ListPlacementGroupsRequest',
          returnType: 'ListPlacementGroupsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'PlacementGroup',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getPlacementGroup',
          protoName: 'GetPlacementGroup',
          paramsType: 'GetPlacementGroupRequest',
          returnType: 'GetPlacementGroupResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getPlacementGroupServers',
          protoName: 'GetPlacementGroupServers',
          paramsType: 'GetPlacementGroupServersRequest',
          returnType: 'GetPlacementGroupServersResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listIps',
          protoName: 'ListIps',
          paramsType: 'ListIpsRequest',
          returnType: 'ListIpsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Ip',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getIp',
          protoName: 'GetIp',
          paramsType: 'GetIpRequest',
          returnType: 'GetIpResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listPrivateNICs',
          protoName: 'ListPrivateNICs',
          paramsType: 'ListPrivateNICsRequest',
          returnType: 'ListPrivateNICsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'PrivateNIC',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getPrivateNIC',
          protoName: 'GetPrivateNIC',
          paramsType: 'GetPrivateNICRequest',
          returnType: 'GetPrivateNICResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDashboard',
          protoName: 'GetDashboard',
          paramsType: 'GetDashboardRequest',
          returnType: 'GetDashboardResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
