// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.
export { API } from './api.gen.js'
export * from './content.gen.js'
export * from './marshalling.gen.js'
export type {
  CreateDHCPEntryRequest,
  CreateDHCPRequest,
  CreateGatewayNetworkRequest,
  CreateGatewayNetworkRequestIpamConfig,
  CreateGatewayRequest,
  CreateIPRequest,
  CreatePATRuleRequest,
  DHCP,
  DHCPEntry,
  DHCPEntryType,
  DeleteDHCPEntryRequest,
  DeleteDHCPRequest,
  DeleteGatewayNetworkRequest,
  DeleteGatewayRequest,
  DeleteIPRequest,
  DeletePATRuleRequest,
  EnableIPMobilityRequest,
  Gateway,
  GatewayNetwork,
  GatewayNetworkStatus,
  GatewayStatus,
  GatewayType,
  GetDHCPEntryRequest,
  GetDHCPRequest,
  GetGatewayNetworkRequest,
  GetGatewayRequest,
  GetIPRequest,
  GetPATRuleRequest,
  IP,
  IpamConfig,
  ListDHCPEntriesRequest,
  ListDHCPEntriesRequestOrderBy,
  ListDHCPEntriesResponse,
  ListDHCPsRequest,
  ListDHCPsRequestOrderBy,
  ListDHCPsResponse,
  ListGatewayNetworksRequest,
  ListGatewayNetworksRequestOrderBy,
  ListGatewayNetworksResponse,
  ListGatewayTypesRequest,
  ListGatewayTypesResponse,
  ListGatewaysRequest,
  ListGatewaysRequestOrderBy,
  ListGatewaysResponse,
  ListIPsRequest,
  ListIPsRequestOrderBy,
  ListIPsResponse,
  ListPATRulesRequest,
  ListPATRulesRequestOrderBy,
  ListPATRulesResponse,
  MigrateToV2Request,
  PATRule,
  PATRuleProtocol,
  RefreshSSHKeysRequest,
  SetDHCPEntriesRequest,
  SetDHCPEntriesRequestEntry,
  SetDHCPEntriesResponse,
  SetPATRulesRequest,
  SetPATRulesRequestRule,
  SetPATRulesResponse,
  UpdateDHCPEntryRequest,
  UpdateDHCPRequest,
  UpdateGatewayNetworkRequest,
  UpdateGatewayNetworkRequestIpamConfig,
  UpdateGatewayRequest,
  UpdateIPRequest,
  UpdatePATRuleRequest,
  UpgradeGatewayRequest,
} from './types.gen.js'
