// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'vpcgw',
  version: 'v1',
  folderName: 'vpcgwv1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listGateways',
          protoName: 'ListGateways',
          paramsType: 'ListGatewaysRequest',
          returnType: 'ListGatewaysResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Gateway',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getGateway',
          protoName: 'GetGateway',
          paramsType: 'GetGatewayRequest',
          returnType: 'Gateway',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listGatewayNetworks',
          protoName: 'ListGatewayNetworks',
          paramsType: 'ListGatewayNetworksRequest',
          returnType: 'ListGatewayNetworksResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'GatewayNetwork',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getGatewayNetwork',
          protoName: 'GetGatewayNetwork',
          paramsType: 'GetGatewayNetworkRequest',
          returnType: 'GatewayNetwork',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listDHCPs',
          protoName: 'ListDHCPs',
          paramsType: 'ListDHCPsRequest',
          returnType: 'ListDHCPsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'DHCP',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDHCP',
          protoName: 'GetDHCP',
          paramsType: 'GetDHCPRequest',
          returnType: 'DHCP',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDHCPEntries',
          protoName: 'ListDHCPEntries',
          paramsType: 'ListDHCPEntriesRequest',
          returnType: 'ListDHCPEntriesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'DHCPEntry',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDHCPEntry',
          protoName: 'GetDHCPEntry',
          paramsType: 'GetDHCPEntryRequest',
          returnType: 'DHCPEntry',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listPATRules',
          protoName: 'ListPATRules',
          paramsType: 'ListPATRulesRequest',
          returnType: 'ListPATRulesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'PATRule',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getPATRule',
          protoName: 'GetPATRule',
          paramsType: 'GetPATRuleRequest',
          returnType: 'PATRule',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listGatewayTypes',
          protoName: 'ListGatewayTypes',
          paramsType: 'ListGatewayTypesRequest',
          returnType: 'ListGatewayTypesResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listIPs',
          protoName: 'ListIPs',
          paramsType: 'ListIPsRequest',
          returnType: 'ListIPsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'IP',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getIP',
          protoName: 'GetIP',
          paramsType: 'GetIPRequest',
          returnType: 'IP',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
