// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'vpc',
  version: 'v2',
  folderName: 'vpcv2',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listVPCs',
          protoName: 'ListVPCs',
          paramsType: 'ListVPCsRequest',
          returnType: 'ListVPCsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'VPC',
          listItemTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getVPC',
          protoName: 'GetVPC',
          paramsType: 'GetVPCRequest',
          returnType: 'VPC',
          returnTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listPrivateNetworks',
          protoName: 'ListPrivateNetworks',
          paramsType: 'ListPrivateNetworksRequest',
          returnType: 'ListPrivateNetworksResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'PrivateNetwork',
          listItemTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getPrivateNetwork',
          protoName: 'GetPrivateNetwork',
          paramsType: 'GetPrivateNetworkRequest',
          returnType: 'PrivateNetwork',
          returnTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSubnets',
          protoName: 'ListSubnets',
          paramsType: 'ListSubnetsRequest',
          returnType: 'ListSubnetsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Subnet',
          listItemTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRoute',
          protoName: 'GetRoute',
          paramsType: 'GetRouteRequest',
          returnType: 'Route',
          returnTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getAcl',
          protoName: 'GetAcl',
          paramsType: 'GetAclRequest',
          returnType: 'GetAclResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listVPCConnectors',
          protoName: 'ListVPCConnectors',
          paramsType: 'ListVPCConnectorsRequest',
          returnType: 'ListVPCConnectorsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'VPCConnector',
          listItemTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getVPCConnector',
          protoName: 'GetVPCConnector',
          paramsType: 'GetVPCConnectorRequest',
          returnType: 'VPCConnector',
          returnTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSubnetOverlaps',
          protoName: 'ListSubnetOverlaps',
          paramsType: 'ListSubnetOverlapsRequest',
          returnType: 'ListSubnetOverlapsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ListSubnetOverlapsResponseSubnetOverlap',
          listItemTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listIngressRules',
          protoName: 'ListIngressRules',
          paramsType: 'ListIngressRulesRequest',
          returnType: 'ListIngressRulesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'IngressRule',
          listItemTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getIngressRule',
          protoName: 'GetIngressRule',
          paramsType: 'GetIngressRuleRequest',
          returnType: 'IngressRule',
          returnTypeNamespace: '@scaleway-internal/sdk-vpc/v2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
