export { V as VitestExecutor } from './chunks/execute.Cjlr2CRw.js';
import 'node:vm';
import 'node:url';
import 'node:fs';
import 'vite-node/client';
import 'vite-node/utils';
import 'pathe';
import '@vitest/utils/error';
import './path.js';
import '@vitest/utils';
import './chunks/base.DSsbfkDg.js';
