/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: '@scaleway/sdk-rdb',
  namespace: 'rdb',
  displayName: 'Rdb',
  versions: ['v1'],
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
