// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'inference',
  version: 'v1',
  folderName: 'inferencev1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listDeployments',
          protoName: 'ListDeployments',
          paramsType: 'ListDeploymentsRequest',
          returnType: 'ListDeploymentsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-inference/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Deployment',
          listItemTypeNamespace: '@scaleway-internal/sdk-inference/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDeployment',
          protoName: 'GetDeployment',
          paramsType: 'GetDeploymentRequest',
          returnType: 'Deployment',
          returnTypeNamespace: '@scaleway-internal/sdk-inference/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDeploymentCertificate',
          protoName: 'GetDeploymentCertificate',
          paramsType: 'GetDeploymentCertificateRequest',
          returnType: 'Blob',
          returnTypeNamespace: '@scaleway-internal/sdk-inference/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listModels',
          protoName: 'ListModels',
          paramsType: 'ListModelsRequest',
          returnType: 'ListModelsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-inference/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Model',
          listItemTypeNamespace: '@scaleway-internal/sdk-inference/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getModel',
          protoName: 'GetModel',
          paramsType: 'GetModelRequest',
          returnType: 'Model',
          returnTypeNamespace: '@scaleway-internal/sdk-inference/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listNodeTypes',
          protoName: 'ListNodeTypes',
          paramsType: 'ListNodeTypesRequest',
          returnType: 'ListNodeTypesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-inference/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'NodeType',
          listItemTypeNamespace: '@scaleway-internal/sdk-inference/v1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
