// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'kafka',
  version: 'v1alpha1',
  folderName: 'kafkav1alpha1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listNodeTypes',
          protoName: 'ListNodeTypes',
          paramsType: 'ListNodeTypesRequest',
          returnType: 'ListNodeTypesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-kafka/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'NodeType',
          listItemTypeNamespace: '@scaleway-internal/sdk-kafka/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listVersions',
          protoName: 'ListVersions',
          paramsType: 'ListVersionsRequest',
          returnType: 'ListVersionsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-kafka/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Version',
          listItemTypeNamespace: '@scaleway-internal/sdk-kafka/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listClusters',
          protoName: 'ListClusters',
          paramsType: 'ListClustersRequest',
          returnType: 'ListClustersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-kafka/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Cluster',
          listItemTypeNamespace: '@scaleway-internal/sdk-kafka/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getCluster',
          protoName: 'GetCluster',
          paramsType: 'GetClusterRequest',
          returnType: 'Cluster',
          returnTypeNamespace: '@scaleway-internal/sdk-kafka/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'getClusterCertificateAuthority',
          protoName: 'GetClusterCertificateAuthority',
          paramsType: 'GetClusterCertificateAuthorityRequest',
          returnType: 'Blob',
          returnTypeNamespace: '@scaleway-internal/sdk-kafka/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listUsers',
          protoName: 'ListUsers',
          paramsType: 'ListUsersRequest',
          returnType: 'ListUsersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-kafka/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'User',
          listItemTypeNamespace: '@scaleway-internal/sdk-kafka/v1alpha1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
