// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'rdb',
  version: 'v1',
  folderName: 'rdbv1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listDatabaseEngines',
          protoName: 'ListDatabaseEngines',
          paramsType: 'ListDatabaseEnginesRequest',
          returnType: 'ListDatabaseEnginesResponse',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'DatabaseEngine',
          listItemTypeNamespace: '@scaleway/sdk-rdb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listNodeTypes',
          protoName: 'ListNodeTypes',
          paramsType: 'ListNodeTypesRequest',
          returnType: 'ListNodeTypesResponse',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'NodeType',
          listItemTypeNamespace: '@scaleway/sdk-rdb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDatabaseBackups',
          protoName: 'ListDatabaseBackups',
          paramsType: 'ListDatabaseBackupsRequest',
          returnType: 'ListDatabaseBackupsResponse',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'DatabaseBackup',
          listItemTypeNamespace: '@scaleway/sdk-rdb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDatabaseBackup',
          protoName: 'GetDatabaseBackup',
          paramsType: 'GetDatabaseBackupRequest',
          returnType: 'DatabaseBackup',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listInstances',
          protoName: 'ListInstances',
          paramsType: 'ListInstancesRequest',
          returnType: 'ListInstancesResponse',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Instance',
          listItemTypeNamespace: '@scaleway/sdk-rdb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getInstance',
          protoName: 'GetInstance',
          paramsType: 'GetInstanceRequest',
          returnType: 'Instance',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'getInstanceCertificate',
          protoName: 'GetInstanceCertificate',
          paramsType: 'GetInstanceCertificateRequest',
          returnType: 'Blob',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getInstanceMetrics',
          protoName: 'GetInstanceMetrics',
          paramsType: 'GetInstanceMetricsRequest',
          returnType: 'InstanceMetrics',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getReadReplica',
          protoName: 'GetReadReplica',
          paramsType: 'GetReadReplicaRequest',
          returnType: 'ReadReplica',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listInstanceLogs',
          protoName: 'ListInstanceLogs',
          paramsType: 'ListInstanceLogsRequest',
          returnType: 'ListInstanceLogsResponse',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getInstanceLog',
          protoName: 'GetInstanceLog',
          paramsType: 'GetInstanceLogRequest',
          returnType: 'InstanceLog',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listInstanceLogsDetails',
          protoName: 'ListInstanceLogsDetails',
          paramsType: 'ListInstanceLogsDetailsRequest',
          returnType: 'ListInstanceLogsDetailsResponse',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listInstanceACLRules',
          protoName: 'ListInstanceACLRules',
          paramsType: 'ListInstanceACLRulesRequest',
          returnType: 'ListInstanceACLRulesResponse',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ACLRule',
          listItemTypeNamespace: '@scaleway/sdk-rdb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listUsers',
          protoName: 'ListUsers',
          paramsType: 'ListUsersRequest',
          returnType: 'ListUsersResponse',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'User',
          listItemTypeNamespace: '@scaleway/sdk-rdb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDatabases',
          protoName: 'ListDatabases',
          paramsType: 'ListDatabasesRequest',
          returnType: 'ListDatabasesResponse',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Database',
          listItemTypeNamespace: '@scaleway/sdk-rdb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listPrivileges',
          protoName: 'ListPrivileges',
          paramsType: 'ListPrivilegesRequest',
          returnType: 'ListPrivilegesResponse',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Privilege',
          listItemTypeNamespace: '@scaleway/sdk-rdb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSnapshots',
          protoName: 'ListSnapshots',
          paramsType: 'ListSnapshotsRequest',
          returnType: 'ListSnapshotsResponse',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Snapshot',
          listItemTypeNamespace: '@scaleway/sdk-rdb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSnapshot',
          protoName: 'GetSnapshot',
          paramsType: 'GetSnapshotRequest',
          returnType: 'Snapshot',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'getEndpoint',
          protoName: 'GetEndpoint',
          paramsType: 'GetEndpointRequest',
          returnType: 'Endpoint',
          returnTypeNamespace: '@scaleway/sdk-rdb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
