/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */
import { Accountv3 } from '@scaleway/sdk-account'
import { Applesiliconv1alpha1 } from '@scaleway/sdk-applesilicon'
import { AuditTrailv1alpha1 } from '@scaleway/sdk-audit-trail'
import { Autoscalingv1alpha1 } from '@scaleway/sdk-autoscaling'
import { Baremetalv1, Baremetalv3 } from '@scaleway/sdk-baremetal'
import { Billingv2beta1 } from '@scaleway/sdk-billing'
import { Blockv1, Blockv1alpha1 } from '@scaleway/sdk-block'
import { Cockpitv1 } from '@scaleway/sdk-cockpit'
import { Containerv1beta1 } from '@scaleway/sdk-container'
import { Datawarehousev1beta1 } from '@scaleway/sdk-datawarehouse'
import { Dediboxv1 } from '@scaleway/sdk-dedibox'
import { Domainv2beta1 } from '@scaleway/sdk-domain'
import { EdgeServicesv1beta1 } from '@scaleway/sdk-edge-services'
import { EnvironmentalFootprintv1alpha1 } from '@scaleway/sdk-environmental-footprint'
import { Filev1alpha1 } from '@scaleway/sdk-file'
import { Flexibleipv1alpha1 } from '@scaleway/sdk-flexibleip'
import { Functionv1beta1 } from '@scaleway/sdk-function'
import { Iamv1alpha1 } from '@scaleway/sdk-iam'
import { Inferencev1, Inferencev1beta1 } from '@scaleway/sdk-inference'
import { Instancev1 } from '@scaleway/sdk-instance'
import { Interlinkv1beta1 } from '@scaleway/sdk-interlink'
import { Iotv1 } from '@scaleway/sdk-iot'
import { Ipamv1 } from '@scaleway/sdk-ipam'
import { Jobsv1alpha1 } from '@scaleway/sdk-jobs'
import { K8Sv1 } from '@scaleway/sdk-k8s'
import { Kafkav1alpha1 } from '@scaleway/sdk-kafka'
import { KeyManagerv1alpha1 } from '@scaleway/sdk-key-manager'
import { Lbv1 } from '@scaleway/sdk-lb'
import { Marketplacev2 } from '@scaleway/sdk-marketplace'
import { Mnqv1beta1 } from '@scaleway/sdk-mnq'
import { Mongodbv1, Mongodbv1alpha1 } from '@scaleway/sdk-mongodb'
import { ProductCatalogv2alpha1 } from '@scaleway/sdk-product-catalog'
import { Qaasv1alpha1 } from '@scaleway/sdk-qaas'
import { Rdbv1 } from '@scaleway/sdk-rdb'
import { Redisv1 } from '@scaleway/sdk-redis'
import { Registryv1 } from '@scaleway/sdk-registry'
import { S2SVpnv1alpha1 } from '@scaleway/sdk-s2s-vpn'
import { Searchdbv1alpha1 } from '@scaleway/sdk-searchdb'
import { Secretv1beta1 } from '@scaleway/sdk-secret'
import { ServerlessSqldbv1alpha1 } from '@scaleway/sdk-serverless-sqldb'
import { Temv1alpha1 } from '@scaleway/sdk-tem'
import { Testv1 } from '@scaleway/sdk-test'
import { Vpcv2 } from '@scaleway/sdk-vpc'
import { Vpcgwv1, Vpcgwv2 } from '@scaleway/sdk-vpcgw'
import { Webhostingv1 } from '@scaleway/sdk-webhosting'

export { createAdvancedClient, createClient } from '@scaleway/sdk-client'

/**
 * @deprecated Direct version exports are deprecated. Use the 'Account' namespace instead (e.g., Account.v1).
 */
export { Accountv3 }
export const Account = {
  v3: Accountv3,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Applesilicon' namespace instead (e.g., Applesilicon.v1).
 */
export { Applesiliconv1alpha1 }
export const Applesilicon = {
  v1alpha1: Applesiliconv1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'AuditTrail' namespace instead (e.g., AuditTrail.v1).
 */
export { AuditTrailv1alpha1 }
export const AuditTrail = {
  v1alpha1: AuditTrailv1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Autoscaling' namespace instead (e.g., Autoscaling.v1).
 */
export { Autoscalingv1alpha1 }
export const Autoscaling = {
  v1alpha1: Autoscalingv1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Baremetal' namespace instead (e.g., Baremetal.v1).
 */
export { Baremetalv1, Baremetalv3 }
export const Baremetal = {
  v1: Baremetalv1,
  v3: Baremetalv3,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Billing' namespace instead (e.g., Billing.v1).
 */
export { Billingv2beta1 }
export const Billing = {
  v2beta1: Billingv2beta1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Block' namespace instead (e.g., Block.v1).
 */
export { Blockv1, Blockv1alpha1 }
export const Block = {
  v1: Blockv1,
  v1alpha1: Blockv1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Cockpit' namespace instead (e.g., Cockpit.v1).
 */
export { Cockpitv1 }
export const Cockpit = {
  v1: Cockpitv1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Container' namespace instead (e.g., Container.v1).
 */
export { Containerv1beta1 }
export const Container = {
  v1beta1: Containerv1beta1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Datawarehouse' namespace instead (e.g., Datawarehouse.v1).
 */
export { Datawarehousev1beta1 }
export const Datawarehouse = {
  v1beta1: Datawarehousev1beta1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Dedibox' namespace instead (e.g., Dedibox.v1).
 */
export { Dediboxv1 }
export const Dedibox = {
  v1: Dediboxv1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Domain' namespace instead (e.g., Domain.v1).
 */
export { Domainv2beta1 }
export const Domain = {
  v2beta1: Domainv2beta1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'EdgeServices' namespace instead (e.g., EdgeServices.v1).
 */
export { EdgeServicesv1beta1 }
export const EdgeServices = {
  v1beta1: EdgeServicesv1beta1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'EnvironmentalFootprint' namespace instead (e.g., EnvironmentalFootprint.v1).
 */
export { EnvironmentalFootprintv1alpha1 }
export const EnvironmentalFootprint = {
  v1alpha1: EnvironmentalFootprintv1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'File' namespace instead (e.g., File.v1).
 */
export { Filev1alpha1 }
export const File = {
  v1alpha1: Filev1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Flexibleip' namespace instead (e.g., Flexibleip.v1).
 */
export { Flexibleipv1alpha1 }
export const Flexibleip = {
  v1alpha1: Flexibleipv1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Function' namespace instead (e.g., Function.v1).
 */
export { Functionv1beta1 }
export const Function = {
  v1beta1: Functionv1beta1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Iam' namespace instead (e.g., Iam.v1).
 */
export { Iamv1alpha1 }
export const Iam = {
  v1alpha1: Iamv1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Inference' namespace instead (e.g., Inference.v1).
 */
export { Inferencev1, Inferencev1beta1 }
export const Inference = {
  v1: Inferencev1,
  v1beta1: Inferencev1beta1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Instance' namespace instead (e.g., Instance.v1).
 */
export { Instancev1 }
export const Instance = {
  v1: Instancev1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Interlink' namespace instead (e.g., Interlink.v1).
 */
export { Interlinkv1beta1 }
export const Interlink = {
  v1beta1: Interlinkv1beta1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Iot' namespace instead (e.g., Iot.v1).
 */
export { Iotv1 }
export const Iot = {
  v1: Iotv1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Ipam' namespace instead (e.g., Ipam.v1).
 */
export { Ipamv1 }
export const Ipam = {
  v1: Ipamv1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Jobs' namespace instead (e.g., Jobs.v1).
 */
export { Jobsv1alpha1 }
export const Jobs = {
  v1alpha1: Jobsv1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'K8s' namespace instead (e.g., K8s.v1).
 */
export { K8Sv1 }
export const K8s = {
  v1: K8Sv1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Kafka' namespace instead (e.g., Kafka.v1).
 */
export { Kafkav1alpha1 }
export const Kafka = {
  v1alpha1: Kafkav1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'KeyManager' namespace instead (e.g., KeyManager.v1).
 */
export { KeyManagerv1alpha1 }
export const KeyManager = {
  v1alpha1: KeyManagerv1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Lb' namespace instead (e.g., Lb.v1).
 */
export { Lbv1 }
export const Lb = {
  v1: Lbv1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Marketplace' namespace instead (e.g., Marketplace.v1).
 */
export { Marketplacev2 }
export const Marketplace = {
  v2: Marketplacev2,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Mnq' namespace instead (e.g., Mnq.v1).
 */
export { Mnqv1beta1 }
export const Mnq = {
  v1beta1: Mnqv1beta1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Mongodb' namespace instead (e.g., Mongodb.v1).
 */
export { Mongodbv1, Mongodbv1alpha1 }
export const Mongodb = {
  v1: Mongodbv1,
  v1alpha1: Mongodbv1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'ProductCatalog' namespace instead (e.g., ProductCatalog.v1).
 */
export { ProductCatalogv2alpha1 }
export const ProductCatalog = {
  v2alpha1: ProductCatalogv2alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Qaas' namespace instead (e.g., Qaas.v1).
 */
export { Qaasv1alpha1 }
export const Qaas = {
  v1alpha1: Qaasv1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Rdb' namespace instead (e.g., Rdb.v1).
 */
export { Rdbv1 }
export const Rdb = {
  v1: Rdbv1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Redis' namespace instead (e.g., Redis.v1).
 */
export { Redisv1 }
export const Redis = {
  v1: Redisv1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Registry' namespace instead (e.g., Registry.v1).
 */
export { Registryv1 }
export const Registry = {
  v1: Registryv1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'S2sVpn' namespace instead (e.g., S2sVpn.v1).
 */
export { S2SVpnv1alpha1 }
export const S2sVpn = {
  v1alpha1: S2SVpnv1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Searchdb' namespace instead (e.g., Searchdb.v1).
 */
export { Searchdbv1alpha1 }
export const Searchdb = {
  v1alpha1: Searchdbv1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Secret' namespace instead (e.g., Secret.v1).
 */
export { Secretv1beta1 }
export const Secret = {
  v1beta1: Secretv1beta1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'ServerlessSqldb' namespace instead (e.g., ServerlessSqldb.v1).
 */
export { ServerlessSqldbv1alpha1 }
export const ServerlessSqldb = {
  v1alpha1: ServerlessSqldbv1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Tem' namespace instead (e.g., Tem.v1).
 */
export { Temv1alpha1 }
export const Tem = {
  v1alpha1: Temv1alpha1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Test' namespace instead (e.g., Test.v1).
 */
export { Testv1 }
export const Test = {
  v1: Testv1,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Vpc' namespace instead (e.g., Vpc.v1).
 */
export { Vpcv2 }
export const Vpc = {
  v2: Vpcv2,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Vpcgw' namespace instead (e.g., Vpcgw.v1).
 */
export { Vpcgwv1, Vpcgwv2 }
export const Vpcgw = {
  v1: Vpcgwv1,
  v2: Vpcgwv2,
}

/**
 * @deprecated Direct version exports are deprecated. Use the 'Webhosting' namespace instead (e.g., Webhosting.v1).
 */
export { Webhostingv1 }
export const Webhosting = {
  v1: Webhostingv1,
}

