/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

import metadata from './metadata.gen.json' with { type: 'json' }

export type Metadata = {
  name: string
  namespace: string
  displayName: string
  versions: string[]
}

export const pkgMetadata: Metadata = metadata

export default pkgMetadata
