/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: '@scaleway/sdk-block',
  namespace: 'block',
  displayName: 'Block',
  versions: ['v1', 'v1alpha1'],
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
