import { base, ignorePatterns, react } from '@scaleway/oxlint-config'
import { defineConfig } from 'oxlint'

export default defineConfig({
  extends: [base, react],
  options: {
    reportUnusedDisableDirectives: 'warn',
    typeAware: true,
    typeCheck: false,
  },
  ignorePatterns: [
    ...ignorePatterns,
    '**/app.config.d.ts',
    '**/package.config.d.ts',
    'global.d.ts',
    '**/*.mjs',
    'packages_generated/**',
    'packages/**',
    'examples/**',
    'tools/generate-react-sdk/src/types.generated.ts',
  ],
  rules: {
    'typescript/no-unsafe-member-access': 'warn',
    'typescript/no-unsafe-assignment': 'warn',
    'eslint/no-console': 'warn',
    'eslint/no-continue': 'warn',
    'eslint/no-unused-vars': 'warn',
    'eslint/max-statements': 'warn',
    'unicorn/catch-error-name': 'warn',
    'unicorn/explicit-length-check': 'warn',
    // TODO: new errors from @scaleway/oxlint-config 1.x upgrade — fix later
    'eslint/curly': 'warn',
    'eslint/default-case': 'warn',
    'eslint/init-declarations': 'warn',
    'eslint/max-depth': 'warn',
    'eslint/max-params': 'warn',
    'eslint/no-await-in-loop': 'warn',
    'eslint/no-implicit-coercion': 'warn',
    'eslint/no-use-before-define': 'warn',
    'eslint/no-useless-assignment': 'warn',
    'eslint/prefer-destructuring': 'warn',
    'eslint/prefer-named-capture-group': 'warn',
    'eslint/prefer-template': 'warn',
    'eslint/require-unicode-regexp': 'warn',
    'eslint/sort-imports': 'warn',
    'import/no-nodejs-modules': 'warn',
    'node/no-process-env': 'warn',
    'oxc/no-accumulating-spread': 'warn',
    'typescript/consistent-indexed-object-style': 'warn',
    'typescript/no-confusing-void-expression': 'warn',
    'typescript/no-unnecessary-boolean-literal-compare': 'warn',
    'typescript/no-unnecessary-condition': 'warn',
    'typescript/no-unnecessary-template-expression': 'warn',
    'typescript/no-unnecessary-type-conversion': 'warn',
    'typescript/no-unnecessary-type-parameters': 'warn',
    'typescript/no-unsafe-type-assertion': 'warn',
    'typescript/prefer-nullish-coalescing': 'warn',
    'typescript/prefer-regexp-exec': 'warn',
    'typescript/require-await': 'warn',
    'typescript/restrict-template-expressions': 'warn',
    'typescript/strict-boolean-expressions': 'warn',
    'unicorn/import-style': 'warn',
    'unicorn/no-array-sort': 'warn',
    'unicorn/no-length-as-slice-end': 'warn',
    'unicorn/no-nested-ternary': 'warn',
    'unicorn/no-unnecessary-slice-end': 'warn',
    'unicorn/prefer-import-meta-properties': 'warn',
    'unicorn/prefer-string-raw': 'warn',
    'unicorn/prefer-string-replace-all': 'warn',
    'unicorn/switch-case-braces': 'warn',
    'unicorn/text-encoding-identifier-case': 'warn',
  },
})
