import { base, ignorePatterns, react } from '@scaleway/oxlint-config'
import { defineConfig } from 'oxlint'

export default defineConfig({
  extends: [base, react],
  options: {
    reportUnusedDisableDirectives: 'warn',
    typeAware: true,
    typeCheck: false,
  },
  ignorePatterns: [
    ...ignorePatterns,
    '**/app.config.d.ts',
    '**/package.config.d.ts',
    '**/*.mjs',
    'packages_generated/**',
    'examples/**',
    'tools/generate-react-sdk/src/types.generated.ts',
  ],
  rules: {
    'eslint/no-console': 'warn',
    'eslint/no-unused-vars': 'warn',

    // Downgrade base-preset error rules to warn (to be fixed and re-enabled as error)
    'eslint/eqeqeq': 'warn',
    'eslint/no-await-in-loop': 'warn',
    'eslint/no-bitwise': 'warn',
    'eslint/no-eq-null': 'warn',
    'eslint/no-shadow': 'warn',
    'eslint/no-var': 'warn',
    'eslint/prefer-destructuring': 'warn',
    'eslint/prefer-named-capture-group': 'warn',
    'eslint/prefer-template': 'warn',
    'eslint/require-unicode-regexp': 'warn',
    'eslint/vars-on-top': 'warn',
    'import/no-namespace': 'warn',
    'react/set-state-in-effect': 'warn',
    'typescript/explicit-member-accessibility': 'warn',
    'typescript/method-signature-style': 'warn',
    'typescript/no-dynamic-delete': 'warn',
    'typescript/no-redundant-type-constituents': 'warn',
    'typescript/no-unnecessary-condition': 'warn',
    'typescript/no-unnecessary-type-parameters': 'warn',
    'typescript/no-unsafe-assignment': 'warn',
    'typescript/no-unsafe-call': 'warn',
    'typescript/no-unsafe-member-access': 'warn',
    'typescript/no-unsafe-return': 'warn',
    'typescript/no-unsafe-type-assertion': 'warn',
    'typescript/only-throw-error': 'warn',
    'typescript/parameter-properties': 'warn',
    'typescript/prefer-function-type': 'warn',
    'typescript/prefer-readonly': 'warn',
    'typescript/promise-function-async': 'warn',
    'typescript/strict-boolean-expressions': 'warn',
    'typescript/strict-void-return': 'warn',
    'unicorn/catch-error-name': 'warn',
    'unicorn/consistent-function-scoping': 'warn',
    'unicorn/custom-error-definition': 'warn',
    'unicorn/error-message': 'warn',
    'unicorn/max-nested-calls': 'warn',
    'unicorn/no-await-expression-member': 'warn',
    'unicorn/no-length-as-slice-end': 'warn',
    'unicorn/no-typeof-undefined': 'warn',
    'unicorn/no-unnecessary-slice-end': 'warn',
    'unicorn/no-unreadable-array-destructuring': 'warn',
    'unicorn/no-useless-promise-resolve-reject': 'warn',
    'unicorn/numeric-separators-style': 'warn',
    'unicorn/prefer-array-some': 'warn',
    'unicorn/prefer-code-point': 'warn',
    'unicorn/prefer-global-this': 'warn',
    'unicorn/prefer-import-meta-properties': 'warn',
    'unicorn/prefer-module': 'warn',
    'unicorn/prefer-native-coercion-functions': 'warn',
    'unicorn/prefer-number-coercion': 'warn',
    'unicorn/prefer-number-properties': 'warn',
    'unicorn/prefer-response-static-json': 'warn',
    'unicorn/prefer-spread': 'warn',
    'unicorn/prefer-string-replace-all': 'warn',
    'unicorn/prefer-string-slice': 'warn',
    'unicorn/prefer-ternary': 'warn',
    'unicorn/prefer-type-error': 'warn',
    'unicorn/switch-case-braces': 'warn',
    'unicorn/text-encoding-identifier-case': 'warn',
  },
  overrides: [
    {
      files: ['tools/**', 'vite.config.ts', 'packages/configuration-loader/**'],
      rules: {
        'import/no-nodejs-modules': 'off',
      },
    },
    {
      files: ['tools/pnpm-auto-release/**'],
      rules: {
        'node/no-process-env': 'off',
      },
    },
  ],
})
