packages:
  - 'packages/*'
  - 'packages_generated/*'
  - 'tools/*'

savePrefix: ''
strictPeerDependencies: false
autoInstallPeers: true
engineStrict: true

# Needed as we run a pnpm install after building packages
optimisticRepeatInstall: false

allowBuilds:
  esbuild: true
  nx: true
