/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: "@scaleway/sdk-annotations",
  namespace: "annotations",
  displayName: "Annotations",
  versions: ["v1"]
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
