/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: "@scaleway/sdk-environmental-footprint",
  namespace: "environmental-footprint",
  displayName: "Environmental Footprint",
  versions: ["v1alpha1"]
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
