// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'jobs',
  version: 'v1alpha2',
  folderName: 'jobsv1alpha2',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'getJobDefinition',
          protoName: 'GetJobDefinition',
          paramsType: 'GetJobDefinitionRequest',
          returnType: 'JobDefinition',
          returnTypeNamespace: '@scaleway/sdk-jobs/v1alpha2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listJobDefinitions',
          protoName: 'ListJobDefinitions',
          paramsType: 'ListJobDefinitionsRequest',
          returnType: 'ListJobDefinitionsResponse',
          returnTypeNamespace: '@scaleway/sdk-jobs/v1alpha2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'JobDefinition',
          listItemTypeNamespace: '@scaleway/sdk-jobs/v1alpha2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getJobRun',
          protoName: 'GetJobRun',
          paramsType: 'GetJobRunRequest',
          returnType: 'JobRun',
          returnTypeNamespace: '@scaleway/sdk-jobs/v1alpha2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listJobRuns',
          protoName: 'ListJobRuns',
          paramsType: 'ListJobRunsRequest',
          returnType: 'ListJobRunsResponse',
          returnTypeNamespace: '@scaleway/sdk-jobs/v1alpha2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'JobRun',
          listItemTypeNamespace: '@scaleway/sdk-jobs/v1alpha2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSecret',
          protoName: 'GetSecret',
          paramsType: 'GetSecretRequest',
          returnType: 'Secret',
          returnTypeNamespace: '@scaleway/sdk-jobs/v1alpha2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSecrets',
          protoName: 'ListSecrets',
          paramsType: 'ListSecretsRequest',
          returnType: 'ListSecretsResponse',
          returnTypeNamespace: '@scaleway/sdk-jobs/v1alpha2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getTrigger',
          protoName: 'GetTrigger',
          paramsType: 'GetTriggerRequest',
          returnType: 'Trigger',
          returnTypeNamespace: '@scaleway/sdk-jobs/v1alpha2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listTriggers',
          protoName: 'ListTriggers',
          paramsType: 'ListTriggersRequest',
          returnType: 'ListTriggersResponse',
          returnTypeNamespace: '@scaleway/sdk-jobs/v1alpha2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Trigger',
          listItemTypeNamespace: '@scaleway/sdk-jobs/v1alpha2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listJobResources',
          protoName: 'ListJobResources',
          paramsType: 'ListJobResourcesRequest',
          returnType: 'ListJobResourcesResponse',
          returnTypeNamespace: '@scaleway/sdk-jobs/v1alpha2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getJobLimits',
          protoName: 'GetJobLimits',
          paramsType: 'GetJobLimitsRequest',
          returnType: 'JobLimits',
          returnTypeNamespace: '@scaleway/sdk-jobs/v1alpha2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
