/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: "@scaleway/sdk-account",
  namespace: "account",
  displayName: "Account",
  versions: ["v3"]
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
