import { Accountv3 } from '@scaleway/sdk-account'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useAccountv3ProjectAPI = createSDKFactory(
  Accountv3.ProjectAPI,
  'accountv3Project',
)
