import { Accountv3 } from '@scaleway/sdk-account'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useAccountv3ContractAPI = createSDKFactory(
  Accountv3.ContractAPI,
  'accountv3Contract',
)
