import { AuditTrailv1alpha1 } from '@scaleway/sdk-audit-trail'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useAuditTrailv1alpha1API = createSDKFactory(
  AuditTrailv1alpha1.API,
  'auditTrailv1alpha1',
)
