import { AuditTrailv1alpha1 } from '@scaleway/sdk-audit-trail'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useAuditTrailv1alpha1API = createSDKFactory(
  AuditTrailv1alpha1.API,
  'auditTrailv1alpha1',
)
