import { Autoscalingv1alpha1 } from '@scaleway/sdk-autoscaling'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useAutoscalingv1alpha1API = createSDKFactory(
  Autoscalingv1alpha1.API,
  'autoscalingv1alpha1',
)
