import { Cockpitv1 } from '@scaleway/sdk-cockpit'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useCockpitv1GlobalAPI = createSDKFactory(
  Cockpitv1.GlobalAPI,
  'cockpitv1Global',
)
