import { Dediboxv1 } from '@scaleway/sdk-dedibox'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useDediboxv1IPv6BlockAPI = createSDKFactory(
  Dediboxv1.IPv6BlockAPI,
  'dediboxv1IPv6Block',
)
