import { Dediboxv1 } from '@scaleway/sdk-dedibox'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useDediboxv1BillingAPI = createSDKFactory(
  Dediboxv1.BillingAPI,
  'dediboxv1Billing',
)
