import { Domainv2beta1 } from '@scaleway/sdk-domain'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useDomainv2beta1API = createSDKFactory(
  Domainv2beta1.API,
  'domainv2beta1',
)
