import { EdgeServicesv1beta1 } from '@scaleway/sdk-edge-services'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useEdgeServicesv1beta1API = createSDKFactory(
  EdgeServicesv1beta1.API,
  'edgeServicesv1beta1',
)
