import { Filev1alpha1 } from '@scaleway/sdk-file'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useFilev1alpha1API = createSDKFactory(
  Filev1alpha1.API,
  'filev1alpha1',
)
