import { Flexibleipv1alpha1 } from '@scaleway/sdk-flexibleip'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useFlexibleipv1alpha1API = createSDKFactory(
  Flexibleipv1alpha1.API,
  'flexibleipv1alpha1',
)
