import { Functionv1beta1 } from '@scaleway/sdk-function'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useFunctionv1beta1API = createSDKFactory(
  Functionv1beta1.API,
  'functionv1beta1',
)
