import { Iamv1alpha1 } from '@scaleway/sdk-iam'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useIamv1alpha1API = createSDKFactory(
  Iamv1alpha1.API,
  'iamv1alpha1',
)
