import { Iamv1alpha1 } from '@scaleway/sdk-iam'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useIamv1alpha1API = createSDKFactory(
  Iamv1alpha1.API,
  'iamv1alpha1',
)
