import { Inferencev1 } from '@scaleway/sdk-inference'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useInferencev1API = createSDKFactory(
  Inferencev1.API,
  'inferencev1',
)
