import { Instancev1 } from '@scaleway/sdk-instance'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useInstancev1API = createSDKFactory(Instancev1.API, 'instancev1')
