import { Instancev1 } from '@scaleway/sdk-instance'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useInstancev1API = createSDKFactory(Instancev1.API, 'instancev1')
