import { Ipamv1 } from '@scaleway/sdk-ipam'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useIpamv1API = createSDKFactory(Ipamv1.API, 'ipamv1')
