import { K8Sv1 } from '@scaleway/sdk-k8s'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useK8Sv1API = createSDKFactory(K8Sv1.API, 'k8Sv1')
