import { Lbv1 } from '@scaleway/sdk-lb'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useLbv1ZonedAPI = createSDKFactory(Lbv1.ZonedAPI, 'lbv1Zoned')
