import { Marketplacev2 } from '@scaleway/sdk-marketplace'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useMarketplacev2API = createSDKFactory(
  Marketplacev2.API,
  'marketplacev2',
)
