import { Marketplacev2 } from '@scaleway/sdk-marketplace'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useMarketplacev2API = createSDKFactory(
  Marketplacev2.API,
  'marketplacev2',
)
