import { Mnqv1beta1 } from '@scaleway/sdk-mnq'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useMnqv1beta1NatsAPI = createSDKFactory(
  Mnqv1beta1.NatsAPI,
  'mnqv1beta1Nats',
)
