import { Mongodbv1alpha1 } from '@scaleway/sdk-mongodb'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useMongodbv1alpha1API = createSDKFactory(
  Mongodbv1alpha1.API,
  'mongodbv1alpha1',
)
