import { Mongodbv1 } from '@scaleway/sdk-mongodb'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useMongodbv1API = createSDKFactory(Mongodbv1.API, 'mongodbv1')
