import { Partnerv1 } from '@scaleway/sdk-partner'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const usePartnerv1API = createSDKFactory(Partnerv1.API, 'partnerv1')
