import { Partnerv1 } from '@scaleway/sdk-partner'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const usePartnerv1API = createSDKFactory(Partnerv1.API, 'partnerv1')
