import { ProductCatalogv2alpha1 } from '@scaleway/sdk-product-catalog'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useProductCatalogv2alpha1PublicCatalogAPI = createSDKFactory(
  ProductCatalogv2alpha1.PublicCatalogAPI,
  'productCatalogv2alpha1PublicCatalog',
)
