import { Rdbv1 } from '@scaleway/sdk-rdb'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useRdbv1API = createSDKFactory(Rdbv1.API, 'rdbv1')
