import { Redisv1 } from '@scaleway/sdk-redis'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useRedisv1API = createSDKFactory(Redisv1.API, 'redisv1')
