import { Registryv1 } from '@scaleway/sdk-registry'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useRegistryv1API = createSDKFactory(Registryv1.API, 'registryv1')
