import { S2SVpnv1alpha1 } from '@scaleway/sdk-s2s-vpn'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useS2SVpnv1alpha1API = createSDKFactory(
  S2SVpnv1alpha1.API,
  's2SVpnv1alpha1',
)
