import { Searchdbv1alpha1 } from '@scaleway/sdk-searchdb'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useSearchdbv1alpha1API = createSDKFactory(
  Searchdbv1alpha1.API,
  'searchdbv1alpha1',
)
