import { Secretv1beta1 } from '@scaleway/sdk-secret'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useSecretv1beta1API = createSDKFactory(
  Secretv1beta1.API,
  'secretv1beta1',
)
