import { ServerlessSqldbv1alpha1 } from '@scaleway/sdk-serverless-sqldb'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useServerlessSqldbv1alpha1API = createSDKFactory(
  ServerlessSqldbv1alpha1.API,
  'serverlessSqldbv1alpha1',
)
