import { Temv1alpha1 } from '@scaleway/sdk-tem'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useTemv1alpha1API = createSDKFactory(
  Temv1alpha1.API,
  'temv1alpha1',
)
