import { Testv1 } from '@scaleway/sdk-test'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useTestv1API = createSDKFactory(Testv1.API, 'testv1')
