import { Vpcgwv2 } from '@scaleway/sdk-vpcgw'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useVpcgwv2API = createSDKFactory(Vpcgwv2.API, 'vpcgwv2')
