import { Vpcgwv1 } from '@scaleway/sdk-vpcgw'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useVpcgwv1API = createSDKFactory(Vpcgwv1.API, 'vpcgwv1')
