import { Vpcv2 } from '@scaleway/sdk-vpc'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useVpcv2API = createSDKFactory(Vpcv2.API, 'vpcv2')
