import { Webhostingv1 } from '@scaleway/sdk-webhosting'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useWebhostingv1FtpAccountAPI = createSDKFactory(
  Webhostingv1.FtpAccountAPI,
  'webhostingv1FtpAccount',
)
