import { Webhostingv1 } from '@scaleway/sdk-webhosting'
import { createSDKFactory } from '../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased
export const useWebhostingv1DatabaseAPI = createSDKFactory(
  Webhostingv1.DatabaseAPI,
  'webhostingv1Database',
)
