// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'marketplace',
  version: 'v2',
  folderName: 'marketplacev2',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listImages',
          protoName: 'ListImages',
          paramsType: 'ListImagesRequest',
          returnType: 'ListImagesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-marketplace/v2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Image',
          listItemTypeNamespace: '@scaleway-internal/sdk-marketplace/v2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getImage',
          protoName: 'GetImage',
          paramsType: 'GetImageRequest',
          returnType: 'Image',
          returnTypeNamespace: '@scaleway-internal/sdk-marketplace/v2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listVersions',
          protoName: 'ListVersions',
          paramsType: 'ListVersionsRequest',
          returnType: 'ListVersionsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-marketplace/v2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Version',
          listItemTypeNamespace: '@scaleway-internal/sdk-marketplace/v2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getVersion',
          protoName: 'GetVersion',
          paramsType: 'GetVersionRequest',
          returnType: 'Version',
          returnTypeNamespace: '@scaleway-internal/sdk-marketplace/v2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listLocalImages',
          protoName: 'ListLocalImages',
          paramsType: 'ListLocalImagesRequest',
          returnType: 'ListLocalImagesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-marketplace/v2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'LocalImage',
          listItemTypeNamespace: '@scaleway-internal/sdk-marketplace/v2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getLocalImage',
          protoName: 'GetLocalImage',
          paramsType: 'GetLocalImageRequest',
          returnType: 'LocalImage',
          returnTypeNamespace: '@scaleway-internal/sdk-marketplace/v2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listCategories',
          protoName: 'ListCategories',
          paramsType: 'ListCategoriesRequest',
          returnType: 'ListCategoriesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-marketplace/v2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Category',
          listItemTypeNamespace: '@scaleway-internal/sdk-marketplace/v2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getCategory',
          protoName: 'GetCategory',
          paramsType: 'GetCategoryRequest',
          returnType: 'Category',
          returnTypeNamespace: '@scaleway-internal/sdk-marketplace/v2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
