/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: '@scaleway/sdk-baremetal',
  namespace: 'baremetal',
  displayName: 'Baremetal',
  versions: ['v1', 'v3'],
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
