// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.
export { API } from './api.gen'
export * from './content.gen'
export type {
  CreateNameRequest,
  CreatePinByCIDRequest,
  CreatePinByURLRequest,
  CreateVolumeRequest,
  DeleteNameRequest,
  DeletePinRequest,
  DeleteVolumeRequest,
  ExportKeyNameRequest,
  ExportKeyNameResponse,
  GetNameRequest,
  GetPinRequest,
  GetVolumeRequest,
  ImportKeyNameRequest,
  ListNamesRequest,
  ListNamesRequestOrderBy,
  ListNamesResponse,
  ListPinsRequest,
  ListPinsRequestOrderBy,
  ListPinsResponse,
  ListVolumesRequest,
  ListVolumesRequestOrderBy,
  ListVolumesResponse,
  Name,
  NameStatus,
  Pin,
  PinCID,
  PinCIDMeta,
  PinDetails,
  PinInfo,
  PinOptions,
  PinStatus,
  ReplacePinRequest,
  ReplacePinResponse,
  UpdateNameRequest,
  UpdateVolumeRequest,
  Volume,
} from './types.gen'
