// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.
export { API, IpnsAPI } from './api.gen'
export * from './content.gen'
export type {
  CreatePinByCIDRequest,
  CreatePinByURLRequest,
  CreateVolumeRequest,
  DeletePinRequest,
  DeleteVolumeRequest,
  ExportKeyNameResponse,
  GetPinRequest,
  GetVolumeRequest,
  IpnsApiCreateNameRequest,
  IpnsApiDeleteNameRequest,
  IpnsApiExportKeyNameRequest,
  IpnsApiGetNameRequest,
  IpnsApiImportKeyNameRequest,
  IpnsApiListNamesRequest,
  IpnsApiUpdateNameRequest,
  ListNamesRequestOrderBy,
  ListNamesResponse,
  ListPinsRequest,
  ListPinsRequestOrderBy,
  ListPinsResponse,
  ListVolumesRequest,
  ListVolumesRequestOrderBy,
  ListVolumesResponse,
  Name,
  NameStatus,
  Pin,
  PinCID,
  PinCIDMeta,
  PinDetails,
  PinInfo,
  PinStatus,
  ReplacePinRequest,
  ReplacePinResponse,
  UpdateVolumeRequest,
  Volume,
} from './types.gen'
