// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'mongodb',
  version: 'v1',
  folderName: 'mongodbv1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listNodeTypes',
          protoName: 'ListNodeTypes',
          paramsType: 'ListNodeTypesRequest',
          returnType: 'ListNodeTypesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'NodeType',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listVersions',
          protoName: 'ListVersions',
          paramsType: 'ListVersionsRequest',
          returnType: 'ListVersionsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Version',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listInstances',
          protoName: 'ListInstances',
          paramsType: 'ListInstancesRequest',
          returnType: 'ListInstancesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Instance',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getInstance',
          protoName: 'GetInstance',
          paramsType: 'GetInstanceRequest',
          returnType: 'Instance',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'getInstanceCertificate',
          protoName: 'GetInstanceCertificate',
          paramsType: 'GetInstanceCertificateRequest',
          returnType: 'Blob',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSnapshot',
          protoName: 'GetSnapshot',
          paramsType: 'GetSnapshotRequest',
          returnType: 'Snapshot',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSnapshots',
          protoName: 'ListSnapshots',
          paramsType: 'ListSnapshotsRequest',
          returnType: 'ListSnapshotsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Snapshot',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listUsers',
          protoName: 'ListUsers',
          paramsType: 'ListUsersRequest',
          returnType: 'ListUsersResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'User',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDatabases',
          protoName: 'ListDatabases',
          paramsType: 'ListDatabasesRequest',
          returnType: 'ListDatabasesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Database',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listMaintenances',
          protoName: 'ListMaintenances',
          paramsType: 'ListMaintenancesRequest',
          returnType: 'ListMaintenancesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Maintenance',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getMaintenance',
          protoName: 'GetMaintenance',
          paramsType: 'GetMaintenanceRequest',
          returnType: 'Maintenance',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
