// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'audit_trail',
  version: 'v1alpha1',
  folderName: 'auditTrailv1alpha1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listEvents',
          protoName: 'ListEvents',
          paramsType: 'ListEventsRequest',
          returnType: 'ListEventsResponse',
          isList: true,
          paginationType: 'cursor',
          pageParamKey: 'pageToken',
          listItemType: 'Event',
          nextPageField: 'nextPageToken',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listAuthenticationEvents',
          protoName: 'ListAuthenticationEvents',
          paramsType: 'ListAuthenticationEventsRequest',
          returnType: 'ListAuthenticationEventsResponse',
          isList: true,
          paginationType: 'cursor',
          pageParamKey: 'pageToken',
          listItemType: 'AuthenticationEvent',
          nextPageField: 'nextPageToken',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSystemEvents',
          protoName: 'ListSystemEvents',
          paramsType: 'ListSystemEventsRequest',
          returnType: 'ListSystemEventsResponse',
          isList: true,
          paginationType: 'cursor',
          pageParamKey: 'pageToken',
          listItemType: 'SystemEvent',
          nextPageField: 'nextPageToken',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listCombinedEvents',
          protoName: 'ListCombinedEvents',
          paramsType: 'ListCombinedEventsRequest',
          returnType: 'ListCombinedEventsResponse',
          isList: true,
          paginationType: 'cursor',
          pageParamKey: 'pageToken',
          listItemType: 'ListCombinedEventsResponseCombinedEvent',
          nextPageField: 'nextPageToken',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listProducts',
          protoName: 'ListProducts',
          paramsType: 'ListProductsRequest',
          returnType: 'ListProductsResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listExportJobs',
          protoName: 'ListExportJobs',
          paramsType: 'ListExportJobsRequest',
          returnType: 'ListExportJobsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ExportJob',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listAlertRules',
          protoName: 'ListAlertRules',
          paramsType: 'ListAlertRulesRequest',
          returnType: 'ListAlertRulesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'AlertRule',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
