// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'billing',
  version: 'v2beta1',
  folderName: 'billingv2beta1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listConsumptions',
          protoName: 'ListConsumptions',
          paramsType: 'ListConsumptionsRequest',
          returnType: 'ListConsumptionsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-billing/v2beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ListConsumptionsResponseConsumption',
          listItemTypeNamespace: '@scaleway-internal/sdk-billing/v2beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listTaxes',
          protoName: 'ListTaxes',
          paramsType: 'ListTaxesRequest',
          returnType: 'ListTaxesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-billing/v2beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ListTaxesResponseTax',
          listItemTypeNamespace: '@scaleway-internal/sdk-billing/v2beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listInvoices',
          protoName: 'ListInvoices',
          paramsType: 'ListInvoicesRequest',
          returnType: 'ListInvoicesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-billing/v2beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Invoice',
          listItemTypeNamespace: '@scaleway-internal/sdk-billing/v2beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getInvoice',
          protoName: 'GetInvoice',
          paramsType: 'GetInvoiceRequest',
          returnType: 'Invoice',
          returnTypeNamespace: '@scaleway-internal/sdk-billing/v2beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDiscounts',
          protoName: 'ListDiscounts',
          paramsType: 'ListDiscountsRequest',
          returnType: 'ListDiscountsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-billing/v2beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Discount',
          listItemTypeNamespace: '@scaleway-internal/sdk-billing/v2beta1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'FinOpsAPI',
      methods: [
        {
          methodName: 'listCharges',
          protoName: 'ListCharges',
          paramsType: 'FinOpsApiListChargesRequest',
          returnType: 'ListChargesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-billing/v2beta1',
          isList: true,
          paginationType: 'cursor',
          pageParamKey: 'pageToken',
          listItemType: 'Charge',
          listItemTypeNamespace: '@scaleway-internal/sdk-billing/v2beta1',
          nextPageField: 'nextPageToken',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
