// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.
export { API, DediboxAPI } from './api.gen'
export * from './content.gen'
export type {
  CreateHostingRequest,
  DediboxApiListDediboxHostingsRequest,
  DediboxApiMigrateDediboxHostingRequest,
  DediboxHosting,
  DediboxHostingType,
  DeleteHostingRequest,
  DnsRecord,
  DnsRecordStatus,
  DnsRecordType,
  DnsRecords,
  DnsRecordsStatus,
  GetDomainDnsRecordsRequest,
  GetHostingRequest,
  Hosting,
  HostingCpanelUrls,
  HostingDnsStatus,
  HostingOption,
  HostingStatus,
  ListDediboxHostingsRequestOrderBy,
  ListDediboxHostingsResponse,
  ListHostingsRequest,
  ListHostingsRequestOrderBy,
  ListHostingsResponse,
  ListOffersRequest,
  ListOffersRequestOrderBy,
  ListOffersResponse,
  Nameserver,
  NameserverStatus,
  Offer,
  OfferProduct,
  OfferQuotaWarning,
  RestoreHostingRequest,
  UpdateHostingRequest,
} from './types.gen'
export * as ValidationRules from './validation-rules.gen'
