/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: '@scaleway/sdk-datalab',
  namespace: 'datalab',
  displayName: 'Datalab',
  versions: ['v1beta1'],
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
