/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: '@scaleway/sdk-domain',
  namespace: 'domain',
  displayName: 'Domain',
  versions: ['v2beta1'],
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
