// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'dedibox',
  version: 'v1',
  folderName: 'dediboxv1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listServers',
          protoName: 'ListServers',
          paramsType: 'ListServersRequest',
          returnType: 'ListServersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ServerSummary',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getServer',
          protoName: 'GetServer',
          paramsType: 'GetServerRequest',
          returnType: 'Server',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'getServerBackup',
          protoName: 'GetServerBackup',
          paramsType: 'GetServerBackupRequest',
          returnType: 'Backup',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSubscribableServerOptions',
          protoName: 'ListSubscribableServerOptions',
          paramsType: 'ListSubscribableServerOptionsRequest',
          returnType: 'ListSubscribableServerOptionsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Offer',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listServerEvents',
          protoName: 'ListServerEvents',
          paramsType: 'ListServerEventsRequest',
          returnType: 'ListServerEventsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ServerEvent',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listServerDisks',
          protoName: 'ListServerDisks',
          paramsType: 'ListServerDisksRequest',
          returnType: 'ListServerDisksResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ServerDisk',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getOrderedService',
          protoName: 'GetOrderedService',
          paramsType: 'GetOrderedServiceRequest',
          returnType: 'Service',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getService',
          protoName: 'GetService',
          paramsType: 'GetServiceRequest',
          returnType: 'Service',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listServices',
          protoName: 'ListServices',
          paramsType: 'ListServicesRequest',
          returnType: 'ListServicesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Service',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getServerInstall',
          protoName: 'GetServerInstall',
          paramsType: 'GetServerInstallRequest',
          returnType: 'ServerInstall',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'getServerDefaultPartitioning',
          protoName: 'GetServerDefaultPartitioning',
          paramsType: 'GetServerDefaultPartitioningRequest',
          returnType: 'ServerDefaultPartitioning',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getBMCAccess',
          protoName: 'GetBMCAccess',
          paramsType: 'GetBMCAccessRequest',
          returnType: 'BMCAccess',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listOffers',
          protoName: 'ListOffers',
          paramsType: 'ListOffersRequest',
          returnType: 'ListOffersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Offer',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getOffer',
          protoName: 'GetOffer',
          paramsType: 'GetOfferRequest',
          returnType: 'Offer',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listOS',
          protoName: 'ListOS',
          paramsType: 'ListOSRequest',
          returnType: 'ListOSResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'OS',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getOS',
          protoName: 'GetOS',
          paramsType: 'GetOSRequest',
          returnType: 'OS',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listFailoverIPs',
          protoName: 'ListFailoverIPs',
          paramsType: 'ListFailoverIPsRequest',
          returnType: 'ListFailoverIPsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'FailoverIP',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getFailoverIP',
          protoName: 'GetFailoverIP',
          paramsType: 'GetFailoverIPRequest',
          returnType: 'FailoverIP',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRemainingQuota',
          protoName: 'GetRemainingQuota',
          paramsType: 'GetRemainingQuotaRequest',
          returnType: 'GetRemainingQuotaResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRaid',
          protoName: 'GetRaid',
          paramsType: 'GetRaidRequest',
          returnType: 'Raid',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRescue',
          protoName: 'GetRescue',
          paramsType: 'GetRescueRequest',
          returnType: 'Rescue',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'BillingAPI',
      methods: [
        {
          methodName: 'listInvoices',
          protoName: 'ListInvoices',
          paramsType: 'BillingApiListInvoicesRequest',
          returnType: 'ListInvoicesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'InvoiceSummary',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getInvoice',
          protoName: 'GetInvoice',
          paramsType: 'BillingApiGetInvoiceRequest',
          returnType: 'Invoice',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listRefunds',
          protoName: 'ListRefunds',
          paramsType: 'BillingApiListRefundsRequest',
          returnType: 'ListRefundsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'RefundSummary',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRefund',
          protoName: 'GetRefund',
          paramsType: 'BillingApiGetRefundRequest',
          returnType: 'Refund',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'IPv6BlockAPI',
      methods: [
        {
          methodName: 'getIPv6BlockQuotas',
          protoName: 'GetIPv6BlockQuotas',
          paramsType: 'IPv6BlockApiGetIPv6BlockQuotasRequest',
          returnType: 'GetIPv6BlockQuotasResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listIPv6Blocks',
          protoName: 'ListIPv6Blocks',
          paramsType: 'IPv6BlockApiListIPv6BlocksRequest',
          returnType: 'ListIPv6BlocksResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getIPv6Block',
          protoName: 'GetIPv6Block',
          paramsType: 'IPv6BlockApiGetIPv6BlockRequest',
          returnType: 'IPv6Block',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listIPv6BlockSubnetsAvailable',
          protoName: 'ListIPv6BlockSubnetsAvailable',
          paramsType: 'IPv6BlockApiListIPv6BlockSubnetsAvailableRequest',
          returnType: 'ListIPv6BlockSubnetsAvailableResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'RpnAPI',
      methods: [
        {
          methodName: 'listRpnServerCapabilities',
          protoName: 'ListRpnServerCapabilities',
          paramsType: 'RpnApiListRpnServerCapabilitiesRequest',
          returnType: 'ListRpnServerCapabilitiesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'RpnServerCapability',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRpnStatus',
          protoName: 'GetRpnStatus',
          paramsType: 'RpnApiGetRpnStatusRequest',
          returnType: 'GetRpnStatusResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'RpnSanAPI',
      methods: [
        {
          methodName: 'listRpnSans',
          protoName: 'ListRpnSans',
          paramsType: 'RpnSanApiListRpnSansRequest',
          returnType: 'ListRpnSansResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'RpnSanSummary',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRpnSan',
          protoName: 'GetRpnSan',
          paramsType: 'RpnSanApiGetRpnSanRequest',
          returnType: 'RpnSan',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listIps',
          protoName: 'ListIps',
          paramsType: 'RpnSanApiListIpsRequest',
          returnType: 'ListIpsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listAvailableIps',
          protoName: 'ListAvailableIps',
          paramsType: 'RpnSanApiListAvailableIpsRequest',
          returnType: 'ListIpsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'RpnV1API',
      methods: [
        {
          methodName: 'listRpnGroups',
          protoName: 'ListRpnGroups',
          paramsType: 'RpnV1ApiListRpnGroupsRequest',
          returnType: 'ListRpnGroupsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'RpnGroup',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRpnGroup',
          protoName: 'GetRpnGroup',
          paramsType: 'RpnV1ApiGetRpnGroupRequest',
          returnType: 'RpnGroup',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listRpnGroupMembers',
          protoName: 'ListRpnGroupMembers',
          paramsType: 'RpnV1ApiListRpnGroupMembersRequest',
          returnType: 'ListRpnGroupMembersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'RpnGroupMember',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listRpnCapableServers',
          protoName: 'ListRpnCapableServers',
          paramsType: 'RpnV1ApiListRpnCapableServersRequest',
          returnType: 'ListRpnCapableServersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Server',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listRpnCapableSanServers',
          protoName: 'ListRpnCapableSanServers',
          paramsType: 'RpnV1ApiListRpnCapableSanServersRequest',
          returnType: 'ListRpnCapableSanServersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'RpnSanServer',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listRpnInvites',
          protoName: 'ListRpnInvites',
          paramsType: 'RpnV1ApiListRpnInvitesRequest',
          returnType: 'ListRpnInvitesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'RpnGroupMember',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'RpnV2API',
      methods: [
        {
          methodName: 'listRpnV2Groups',
          protoName: 'ListRpnV2Groups',
          paramsType: 'RpnV2ApiListRpnV2GroupsRequest',
          returnType: 'ListRpnV2GroupsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'RpnV2Group',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listRpnV2Members',
          protoName: 'ListRpnV2Members',
          paramsType: 'RpnV2ApiListRpnV2MembersRequest',
          returnType: 'ListRpnV2MembersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'RpnV2Member',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRpnV2Group',
          protoName: 'GetRpnV2Group',
          paramsType: 'RpnV2ApiGetRpnV2GroupRequest',
          returnType: 'RpnV2Group',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listRpnV2CapableResources',
          protoName: 'ListRpnV2CapableResources',
          paramsType: 'RpnV2ApiListRpnV2CapableResourcesRequest',
          returnType: 'ListRpnV2CapableResourcesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Server',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listRpnV2GroupLogs',
          protoName: 'ListRpnV2GroupLogs',
          paramsType: 'RpnV2ApiListRpnV2GroupLogsRequest',
          returnType: 'ListRpnV2GroupLogsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Log',
          listItemTypeNamespace: '@scaleway-internal/sdk-dedibox/v1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
