/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: '@scaleway/sdk-product-catalog',
  namespace: 'product-catalog',
  displayName: 'Product Catalog',
  versions: ['v2alpha1'],
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
