/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: "@scaleway/sdk-mnq",
  namespace: "mnq",
  displayName: "Mnq",
  versions: ["v1beta1"]
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
