// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'cockpit',
  version: 'v1',
  folderName: 'cockpitv1',
  services: [
    {
      apiClass: 'GlobalAPI',
      methods: [
        {
          methodName: 'getGrafana',
          protoName: 'GetGrafana',
          paramsType: 'GlobalApiGetGrafanaRequest',
          returnType: 'Grafana',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listGrafanaUsers',
          protoName: 'ListGrafanaUsers',
          paramsType: 'GlobalApiListGrafanaUsersRequest',
          returnType: 'ListGrafanaUsersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'GrafanaUser',
          listItemTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listGrafanaProductDashboards',
          protoName: 'ListGrafanaProductDashboards',
          paramsType: 'GlobalApiListGrafanaProductDashboardsRequest',
          returnType: 'ListGrafanaProductDashboardsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'GrafanaProductDashboard',
          listItemTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getGrafanaProductDashboard',
          protoName: 'GetGrafanaProductDashboard',
          paramsType: 'GlobalApiGetGrafanaProductDashboardRequest',
          returnType: 'GrafanaProductDashboard',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listPlans',
          protoName: 'ListPlans',
          paramsType: 'GlobalApiListPlansRequest',
          returnType: 'ListPlansResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Plan',
          listItemTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getCurrentPlan',
          protoName: 'GetCurrentPlan',
          paramsType: 'GlobalApiGetCurrentPlanRequest',
          returnType: 'Plan',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'RegionalAPI',
      methods: [
        {
          methodName: 'getConfig',
          protoName: 'GetConfig',
          paramsType: 'RegionalApiGetConfigRequest',
          returnType: 'GetConfigResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listExporters',
          protoName: 'ListExporters',
          paramsType: 'RegionalApiListExportersRequest',
          returnType: 'ListExportersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Exporter',
          listItemTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getExporter',
          protoName: 'GetExporter',
          paramsType: 'RegionalApiGetExporterRequest',
          returnType: 'Exporter',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'getDataSource',
          protoName: 'GetDataSource',
          paramsType: 'RegionalApiGetDataSourceRequest',
          returnType: 'DataSource',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDataSources',
          protoName: 'ListDataSources',
          paramsType: 'RegionalApiListDataSourcesRequest',
          returnType: 'ListDataSourcesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'DataSource',
          listItemTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getUsageOverview',
          protoName: 'GetUsageOverview',
          paramsType: 'RegionalApiGetUsageOverviewRequest',
          returnType: 'UsageOverview',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listTokens',
          protoName: 'ListTokens',
          paramsType: 'RegionalApiListTokensRequest',
          returnType: 'ListTokensResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Token',
          listItemTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getToken',
          protoName: 'GetToken',
          paramsType: 'RegionalApiGetTokenRequest',
          returnType: 'Token',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listProducts',
          protoName: 'ListProducts',
          paramsType: 'RegionalApiListProductsRequest',
          returnType: 'ListProductsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Product',
          listItemTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getAlertManager',
          protoName: 'GetAlertManager',
          paramsType: 'RegionalApiGetAlertManagerRequest',
          returnType: 'AlertManager',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRulesCount',
          protoName: 'GetRulesCount',
          paramsType: 'RegionalApiGetRulesCountRequest',
          returnType: 'GetRulesCountResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listContactPoints',
          protoName: 'ListContactPoints',
          paramsType: 'RegionalApiListContactPointsRequest',
          returnType: 'ListContactPointsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ContactPoint',
          listItemTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listAlerts',
          protoName: 'ListAlerts',
          paramsType: 'RegionalApiListAlertsRequest',
          returnType: 'ListAlertsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-cockpit/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
