// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.
export { API } from './api.gen'
export * from './content.gen'
export type {
  CancelEmailRequest,
  CheckDomainRequest,
  CreateDomainRequest,
  CreateEmailRequest,
  CreateEmailRequestAddress,
  CreateEmailRequestAttachment,
  CreateEmailRequestHeader,
  CreateEmailResponse,
  CreateWebhookRequest,
  DeleteWebhookRequest,
  Domain,
  DomainLastStatus,
  DomainLastStatusAutoconfigState,
  DomainLastStatusAutoconfigStateReason,
  DomainLastStatusDkimRecord,
  DomainLastStatusDmarcRecord,
  DomainLastStatusRecordStatus,
  DomainLastStatusSpfRecord,
  DomainRecords,
  DomainRecordsDMARC,
  DomainReputation,
  DomainReputationStatus,
  DomainStatistics,
  DomainStatus,
  Email,
  EmailFlag,
  EmailRcptType,
  EmailStatus,
  EmailTry,
  GetDomainLastStatusRequest,
  GetDomainRequest,
  GetEmailRequest,
  GetProjectSettingsRequest,
  GetStatisticsRequest,
  GetWebhookRequest,
  ListDomainsRequest,
  ListDomainsResponse,
  ListEmailsRequest,
  ListEmailsRequestOrderBy,
  ListEmailsResponse,
  ListWebhookEventsRequest,
  ListWebhookEventsRequestOrderBy,
  ListWebhookEventsResponse,
  ListWebhooksRequest,
  ListWebhooksRequestOrderBy,
  ListWebhooksResponse,
  ProjectSettings,
  ProjectSettingsPeriodicReport,
  ProjectSettingsPeriodicReportFrequency,
  RevokeDomainRequest,
  Statistics,
  UpdateDomainRequest,
  UpdateProjectSettingsRequest,
  UpdateProjectSettingsRequestUpdatePeriodicReport,
  UpdateWebhookRequest,
  Webhook,
  WebhookEvent,
  WebhookEventStatus,
  WebhookEventType,
} from './types.gen'
export * as ValidationRules from './validation-rules.gen'
