// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.
export { API } from './api.gen'
export * from './content.gen'
export type {
  CancelEmailRequest,
  CheckDomainRequest,
  CreateDomainRequest,
  CreateEmailRequest,
  CreateEmailRequestAddress,
  CreateEmailRequestAttachment,
  CreateEmailResponse,
  Domain,
  DomainLastStatus,
  DomainLastStatusDkimRecord,
  DomainLastStatusRecordStatus,
  DomainLastStatusSpfRecord,
  DomainStatistics,
  DomainStatus,
  Email,
  EmailFlag,
  EmailRcptType,
  EmailStatus,
  EmailTry,
  GetDomainLastStatusRequest,
  GetDomainRequest,
  GetEmailRequest,
  GetStatisticsRequest,
  ListDomainsRequest,
  ListDomainsResponse,
  ListEmailsRequest,
  ListEmailsRequestOrderBy,
  ListEmailsResponse,
  RevokeDomainRequest,
  Statistics,
} from './types.gen'
