/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: "@scaleway/sdk-vpc",
  namespace: "vpc",
  displayName: "Vpc",
  versions: ["v2"]
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
