/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: "@scaleway/sdk-k8s",
  namespace: "k8s",
  displayName: "K8S",
  versions: ["v1"]
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
