// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'mailbox',
  version: 'v1alpha1',
  folderName: 'mailboxv1alpha1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listDomains',
          protoName: 'ListDomains',
          paramsType: 'ListDomainsRequest',
          returnType: 'ListDomainsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-mailbox/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Domain',
          listItemTypeNamespace: '@scaleway-internal/sdk-mailbox/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDomain',
          protoName: 'GetDomain',
          paramsType: 'GetDomainRequest',
          returnType: 'Domain',
          returnTypeNamespace: '@scaleway-internal/sdk-mailbox/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'getDomainRecords',
          protoName: 'GetDomainRecords',
          paramsType: 'GetDomainRecordsRequest',
          returnType: 'GetDomainRecordsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-mailbox/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listMailboxes',
          protoName: 'ListMailboxes',
          paramsType: 'ListMailboxesRequest',
          returnType: 'ListMailboxesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-mailbox/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Mailbox',
          listItemTypeNamespace: '@scaleway-internal/sdk-mailbox/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getMailbox',
          protoName: 'GetMailbox',
          paramsType: 'GetMailboxRequest',
          returnType: 'Mailbox',
          returnTypeNamespace: '@scaleway-internal/sdk-mailbox/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listAliases',
          protoName: 'ListAliases',
          paramsType: 'ListAliasesRequest',
          returnType: 'ListAliasesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-mailbox/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Alias',
          listItemTypeNamespace: '@scaleway-internal/sdk-mailbox/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getAlias',
          protoName: 'GetAlias',
          paramsType: 'GetAliasRequest',
          returnType: 'Alias',
          returnTypeNamespace: '@scaleway-internal/sdk-mailbox/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
