/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: "@scaleway/sdk-vpcgw",
  namespace: "vpcgw",
  displayName: "Vpcgw",
  versions: ["v1", "v2"]
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
