// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'iot',
  version: 'v1',
  folderName: 'iotv1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listHubs',
          protoName: 'ListHubs',
          paramsType: 'ListHubsRequest',
          returnType: 'ListHubsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Hub',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getHub',
          protoName: 'GetHub',
          paramsType: 'GetHubRequest',
          returnType: 'Hub',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'getHubMetrics',
          protoName: 'GetHubMetrics',
          paramsType: 'GetHubMetricsRequest',
          returnType: 'GetHubMetricsResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getHubCA',
          protoName: 'GetHubCA',
          paramsType: 'GetHubCARequest',
          returnType: 'GetHubCAResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDevices',
          protoName: 'ListDevices',
          paramsType: 'ListDevicesRequest',
          returnType: 'ListDevicesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Device',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDevice',
          protoName: 'GetDevice',
          paramsType: 'GetDeviceRequest',
          returnType: 'Device',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDeviceCertificate',
          protoName: 'GetDeviceCertificate',
          paramsType: 'GetDeviceCertificateRequest',
          returnType: 'GetDeviceCertificateResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDeviceMetrics',
          protoName: 'GetDeviceMetrics',
          paramsType: 'GetDeviceMetricsRequest',
          returnType: 'GetDeviceMetricsResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listRoutes',
          protoName: 'ListRoutes',
          paramsType: 'ListRoutesRequest',
          returnType: 'ListRoutesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'RouteSummary',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRoute',
          protoName: 'GetRoute',
          paramsType: 'GetRouteRequest',
          returnType: 'Route',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listNetworks',
          protoName: 'ListNetworks',
          paramsType: 'ListNetworksRequest',
          returnType: 'ListNetworksResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Network',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getNetwork',
          protoName: 'GetNetwork',
          paramsType: 'GetNetworkRequest',
          returnType: 'Network',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getTwinDocument',
          protoName: 'GetTwinDocument',
          paramsType: 'GetTwinDocumentRequest',
          returnType: 'TwinDocument',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listTwinDocuments',
          protoName: 'ListTwinDocuments',
          paramsType: 'ListTwinDocumentsRequest',
          returnType: 'ListTwinDocumentsResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
