// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'applesilicon',
  version: 'v1alpha1',
  folderName: 'applesiliconv1alpha1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listServerTypes',
          protoName: 'ListServerTypes',
          paramsType: 'ListServerTypesRequest',
          returnType: 'ListServerTypesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-applesilicon/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getServerType',
          protoName: 'GetServerType',
          paramsType: 'GetServerTypeRequest',
          returnType: 'ServerType',
          returnTypeNamespace: '@scaleway-internal/sdk-applesilicon/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listServers',
          protoName: 'ListServers',
          paramsType: 'ListServersRequest',
          returnType: 'ListServersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-applesilicon/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Server',
          listItemTypeNamespace: '@scaleway-internal/sdk-applesilicon/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listOS',
          protoName: 'ListOS',
          paramsType: 'ListOSRequest',
          returnType: 'ListOSResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-applesilicon/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'OS',
          listItemTypeNamespace: '@scaleway-internal/sdk-applesilicon/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getOS',
          protoName: 'GetOS',
          paramsType: 'GetOSRequest',
          returnType: 'OS',
          returnTypeNamespace: '@scaleway-internal/sdk-applesilicon/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getServer',
          protoName: 'GetServer',
          paramsType: 'GetServerRequest',
          returnType: 'Server',
          returnTypeNamespace: '@scaleway-internal/sdk-applesilicon/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'getConnectivityDiagnostic',
          protoName: 'GetConnectivityDiagnostic',
          paramsType: 'GetConnectivityDiagnosticRequest',
          returnType: 'ConnectivityDiagnostic',
          returnTypeNamespace: '@scaleway-internal/sdk-applesilicon/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRunner',
          protoName: 'GetRunner',
          paramsType: 'GetRunnerRequest',
          returnType: 'Runner',
          returnTypeNamespace: '@scaleway-internal/sdk-applesilicon/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listRunners',
          protoName: 'ListRunners',
          paramsType: 'ListRunnersRequest',
          returnType: 'ListRunnersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-applesilicon/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Runner',
          listItemTypeNamespace: '@scaleway-internal/sdk-applesilicon/v1alpha1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'PrivateNetworkAPI',
      methods: [
        {
          methodName: 'getServerPrivateNetwork',
          protoName: 'GetServerPrivateNetwork',
          paramsType: 'PrivateNetworkApiGetServerPrivateNetworkRequest',
          returnType: 'ServerPrivateNetwork',
          returnTypeNamespace: '@scaleway-internal/sdk-applesilicon/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listServerPrivateNetworks',
          protoName: 'ListServerPrivateNetworks',
          paramsType: 'PrivateNetworkApiListServerPrivateNetworksRequest',
          returnType: 'ListServerPrivateNetworksResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-applesilicon/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ServerPrivateNetwork',
          listItemTypeNamespace: '@scaleway-internal/sdk-applesilicon/v1alpha1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
