/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: "@scaleway/sdk-file",
  namespace: "file",
  displayName: "File",
  versions: ["v1alpha1"]
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
