// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'datalab',
  version: 'v1beta1',
  folderName: 'datalabv1beta1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'getDatalab',
          protoName: 'GetDatalab',
          paramsType: 'GetDatalabRequest',
          returnType: 'Datalab',
          returnTypeNamespace: '@scaleway/sdk-datalab/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listDatalabs',
          protoName: 'ListDatalabs',
          paramsType: 'ListDatalabsRequest',
          returnType: 'ListDatalabsResponse',
          returnTypeNamespace: '@scaleway/sdk-datalab/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Datalab',
          listItemTypeNamespace: '@scaleway/sdk-datalab/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listNodeTypes',
          protoName: 'ListNodeTypes',
          paramsType: 'ListNodeTypesRequest',
          returnType: 'ListNodeTypesResponse',
          returnTypeNamespace: '@scaleway/sdk-datalab/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'NodeType',
          listItemTypeNamespace: '@scaleway/sdk-datalab/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listNotebookVersions',
          protoName: 'ListNotebookVersions',
          paramsType: 'ListNotebookVersionsRequest',
          returnType: 'ListNotebookVersionsResponse',
          returnTypeNamespace: '@scaleway/sdk-datalab/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Notebook',
          listItemTypeNamespace: '@scaleway/sdk-datalab/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listClusterVersions',
          protoName: 'ListClusterVersions',
          paramsType: 'ListClusterVersionsRequest',
          returnType: 'ListClusterVersionsResponse',
          returnTypeNamespace: '@scaleway/sdk-datalab/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Cluster',
          listItemTypeNamespace: '@scaleway/sdk-datalab/v1beta1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
