// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'datawarehouse',
  version: 'v1beta1',
  folderName: 'datawarehousev1beta1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listPresets',
          protoName: 'ListPresets',
          paramsType: 'ListPresetsRequest',
          returnType: 'ListPresetsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-datawarehouse/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Preset',
          listItemTypeNamespace: '@scaleway-internal/sdk-datawarehouse/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listVersions',
          protoName: 'ListVersions',
          paramsType: 'ListVersionsRequest',
          returnType: 'ListVersionsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-datawarehouse/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Version',
          listItemTypeNamespace: '@scaleway-internal/sdk-datawarehouse/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDeployments',
          protoName: 'ListDeployments',
          paramsType: 'ListDeploymentsRequest',
          returnType: 'ListDeploymentsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-datawarehouse/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Deployment',
          listItemTypeNamespace: '@scaleway-internal/sdk-datawarehouse/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDeployment',
          protoName: 'GetDeployment',
          paramsType: 'GetDeploymentRequest',
          returnType: 'Deployment',
          returnTypeNamespace: '@scaleway-internal/sdk-datawarehouse/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'getDeploymentCertificate',
          protoName: 'GetDeploymentCertificate',
          paramsType: 'GetDeploymentCertificateRequest',
          returnType: 'Blob',
          returnTypeNamespace: '@scaleway-internal/sdk-datawarehouse/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listUsers',
          protoName: 'ListUsers',
          paramsType: 'ListUsersRequest',
          returnType: 'ListUsersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-datawarehouse/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'User',
          listItemTypeNamespace: '@scaleway-internal/sdk-datawarehouse/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDatabases',
          protoName: 'ListDatabases',
          paramsType: 'ListDatabasesRequest',
          returnType: 'ListDatabasesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-datawarehouse/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Database',
          listItemTypeNamespace: '@scaleway-internal/sdk-datawarehouse/v1beta1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
