// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.
export { API } from './api.gen.js'
export * from './content.gen.js'
export * from './marshalling.gen.js'
export type {
  AddBastionAllowedIPsRequest,
  AddBastionAllowedIPsResponse,
  CreateGatewayNetworkRequest,
  CreateGatewayRequest,
  CreateIPRequest,
  CreatePatRuleRequest,
  DeleteBastionAllowedIPsRequest,
  DeleteGatewayNetworkRequest,
  DeleteGatewayRequest,
  DeleteIPRequest,
  DeletePatRuleRequest,
  Gateway,
  GatewayNetwork,
  GatewayNetworkStatus,
  GatewayStatus,
  GatewayType,
  GetGatewayNetworkRequest,
  GetGatewayRequest,
  GetIPRequest,
  GetPatRuleRequest,
  IP,
  ListGatewayNetworksRequest,
  ListGatewayNetworksRequestOrderBy,
  ListGatewayNetworksResponse,
  ListGatewayTypesRequest,
  ListGatewayTypesResponse,
  ListGatewaysRequest,
  ListGatewaysRequestOrderBy,
  ListGatewaysResponse,
  ListIPsRequest,
  ListIPsRequestOrderBy,
  ListIPsResponse,
  ListPatRulesRequest,
  ListPatRulesRequestOrderBy,
  ListPatRulesResponse,
  PatRule,
  PatRuleProtocol,
  RefreshSSHKeysRequest,
  SetBastionAllowedIPsRequest,
  SetBastionAllowedIPsResponse,
  SetPatRulesRequest,
  SetPatRulesRequestRule,
  SetPatRulesResponse,
  UpdateGatewayNetworkRequest,
  UpdateGatewayRequest,
  UpdateIPRequest,
  UpdatePatRuleRequest,
  UpgradeGatewayRequest,
} from './types.gen.js'
