// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'vpcgw',
  version: 'v2',
  folderName: 'vpcgwv2',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listGateways',
          protoName: 'ListGateways',
          paramsType: 'ListGatewaysRequest',
          returnType: 'ListGatewaysResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-vpcgw/v2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Gateway',
          listItemTypeNamespace: '@scaleway-internal/sdk-vpcgw/v2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getGateway',
          protoName: 'GetGateway',
          paramsType: 'GetGatewayRequest',
          returnType: 'Gateway',
          returnTypeNamespace: '@scaleway-internal/sdk-vpcgw/v2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listGatewayNetworks',
          protoName: 'ListGatewayNetworks',
          paramsType: 'ListGatewayNetworksRequest',
          returnType: 'ListGatewayNetworksResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-vpcgw/v2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'GatewayNetwork',
          listItemTypeNamespace: '@scaleway-internal/sdk-vpcgw/v2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getGatewayNetwork',
          protoName: 'GetGatewayNetwork',
          paramsType: 'GetGatewayNetworkRequest',
          returnType: 'GatewayNetwork',
          returnTypeNamespace: '@scaleway-internal/sdk-vpcgw/v2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listPatRules',
          protoName: 'ListPatRules',
          paramsType: 'ListPatRulesRequest',
          returnType: 'ListPatRulesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-vpcgw/v2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'PatRule',
          listItemTypeNamespace: '@scaleway-internal/sdk-vpcgw/v2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getPatRule',
          protoName: 'GetPatRule',
          paramsType: 'GetPatRuleRequest',
          returnType: 'PatRule',
          returnTypeNamespace: '@scaleway-internal/sdk-vpcgw/v2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listGatewayTypes',
          protoName: 'ListGatewayTypes',
          paramsType: 'ListGatewayTypesRequest',
          returnType: 'ListGatewayTypesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-vpcgw/v2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listIPs',
          protoName: 'ListIPs',
          paramsType: 'ListIPsRequest',
          returnType: 'ListIPsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-vpcgw/v2',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'IP',
          listItemTypeNamespace: '@scaleway-internal/sdk-vpcgw/v2',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getIP',
          protoName: 'GetIP',
          paramsType: 'GetIPRequest',
          returnType: 'IP',
          returnTypeNamespace: '@scaleway-internal/sdk-vpcgw/v2',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
