// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'webhosting',
  version: 'v1',
  folderName: 'webhostingv1',
  services: [
    {
      apiClass: 'BackupAPI',
      methods: [
        {
          methodName: 'listBackups',
          protoName: 'ListBackups',
          paramsType: 'BackupApiListBackupsRequest',
          returnType: 'ListBackupsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Backup',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getBackup',
          protoName: 'GetBackup',
          paramsType: 'BackupApiGetBackupRequest',
          returnType: 'Backup',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listBackupItems',
          protoName: 'ListBackupItems',
          paramsType: 'BackupApiListBackupItemsRequest',
          returnType: 'ListBackupItemsResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getProgress',
          protoName: 'GetProgress',
          paramsType: 'BackupApiGetProgressRequest',
          returnType: 'Progress',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listRecentProgresses',
          protoName: 'ListRecentProgresses',
          paramsType: 'BackupApiListRecentProgressesRequest',
          returnType: 'ListRecentProgressesResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'ControlPanelAPI',
      methods: [
        {
          methodName: 'listControlPanels',
          protoName: 'ListControlPanels',
          paramsType: 'ControlPanelApiListControlPanelsRequest',
          returnType: 'ListControlPanelsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ControlPanel',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'DatabaseAPI',
      methods: [
        {
          methodName: 'listDatabases',
          protoName: 'ListDatabases',
          paramsType: 'DatabaseApiListDatabasesRequest',
          returnType: 'ListDatabasesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Database',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDatabase',
          protoName: 'GetDatabase',
          paramsType: 'DatabaseApiGetDatabaseRequest',
          returnType: 'Database',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDatabaseUsers',
          protoName: 'ListDatabaseUsers',
          paramsType: 'DatabaseApiListDatabaseUsersRequest',
          returnType: 'ListDatabaseUsersResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'DatabaseUser',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDatabaseUser',
          protoName: 'GetDatabaseUser',
          paramsType: 'DatabaseApiGetDatabaseUserRequest',
          returnType: 'DatabaseUser',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'DnsAPI',
      methods: [
        {
          methodName: 'getDomainDnsRecords',
          protoName: 'GetDomainDnsRecords',
          paramsType: 'DnsApiGetDomainDnsRecordsRequest',
          returnType: 'DnsRecords',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'searchDomains',
          protoName: 'SearchDomains',
          paramsType: 'DnsApiSearchDomainsRequest',
          returnType: 'SearchDomainsResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDomain',
          protoName: 'GetDomain',
          paramsType: 'DnsApiGetDomainRequest',
          returnType: 'Domain',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
      ],
    },
    {
      apiClass: 'OfferAPI',
      methods: [
        {
          methodName: 'listOffers',
          protoName: 'ListOffers',
          paramsType: 'OfferApiListOffersRequest',
          returnType: 'ListOffersResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Offer',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'HostingAPI',
      methods: [
        {
          methodName: 'listHostings',
          protoName: 'ListHostings',
          paramsType: 'HostingApiListHostingsRequest',
          returnType: 'ListHostingsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'HostingSummary',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getHosting',
          protoName: 'GetHosting',
          paramsType: 'HostingApiGetHostingRequest',
          returnType: 'Hosting',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'getResourceSummary',
          protoName: 'GetResourceSummary',
          paramsType: 'HostingApiGetResourceSummaryRequest',
          returnType: 'ResourceSummary',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'FreeDomainAPI',
      methods: [
        {
          methodName: 'listFreeRootDomains',
          protoName: 'ListFreeRootDomains',
          paramsType: 'FreeDomainApiListFreeRootDomainsRequest',
          returnType: 'ListFreeRootDomainsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'string',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'FtpAccountAPI',
      methods: [
        {
          methodName: 'listFtpAccounts',
          protoName: 'ListFtpAccounts',
          paramsType: 'FtpAccountApiListFtpAccountsRequest',
          returnType: 'ListFtpAccountsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'FtpAccount',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'MailAccountAPI',
      methods: [
        {
          methodName: 'listMailAccounts',
          protoName: 'ListMailAccounts',
          paramsType: 'MailAccountApiListMailAccountsRequest',
          returnType: 'ListMailAccountsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'MailAccount',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'WebsiteAPI',
      methods: [
        {
          methodName: 'listWebsites',
          protoName: 'ListWebsites',
          paramsType: 'WebsiteApiListWebsitesRequest',
          returnType: 'ListWebsitesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Website',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
