// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'edge_services',
  version: 'v1beta1',
  folderName: 'edgeServicesv1beta1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listPipelines',
          protoName: 'ListPipelines',
          paramsType: 'ListPipelinesRequest',
          returnType: 'ListPipelinesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Pipeline',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getPipeline',
          protoName: 'GetPipeline',
          paramsType: 'GetPipelineRequest',
          returnType: 'Pipeline',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listPipelinesWithStages',
          protoName: 'ListPipelinesWithStages',
          paramsType: 'ListPipelinesWithStagesRequest',
          returnType: 'ListPipelinesWithStagesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'PipelineStages',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getVPCEndpoint',
          protoName: 'GetVPCEndpoint',
          paramsType: 'GetVPCEndpointRequest',
          returnType: 'VPCEndpoint',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listVPCEndpoints',
          protoName: 'ListVPCEndpoints',
          paramsType: 'ListVPCEndpointsRequest',
          returnType: 'ListVPCEndpointsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'VPCEndpoint',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listHeadStages',
          protoName: 'ListHeadStages',
          paramsType: 'ListHeadStagesRequest',
          returnType: 'ListHeadStagesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ListHeadStagesResponseHeadStage',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDNSStages',
          protoName: 'ListDNSStages',
          paramsType: 'ListDNSStagesRequest',
          returnType: 'ListDNSStagesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'DNSStage',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDNSStage',
          protoName: 'GetDNSStage',
          paramsType: 'GetDNSStageRequest',
          returnType: 'DNSStage',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listTLSStages',
          protoName: 'ListTLSStages',
          paramsType: 'ListTLSStagesRequest',
          returnType: 'ListTLSStagesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'TLSStage',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getTLSStage',
          protoName: 'GetTLSStage',
          paramsType: 'GetTLSStageRequest',
          returnType: 'TLSStage',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listCacheStages',
          protoName: 'ListCacheStages',
          paramsType: 'ListCacheStagesRequest',
          returnType: 'ListCacheStagesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'CacheStage',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getCacheStage',
          protoName: 'GetCacheStage',
          paramsType: 'GetCacheStageRequest',
          returnType: 'CacheStage',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listBackendStages',
          protoName: 'ListBackendStages',
          paramsType: 'ListBackendStagesRequest',
          returnType: 'ListBackendStagesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'BackendStage',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getBackendStage',
          protoName: 'GetBackendStage',
          paramsType: 'GetBackendStageRequest',
          returnType: 'BackendStage',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'searchBackendStages',
          protoName: 'SearchBackendStages',
          paramsType: 'SearchBackendStagesRequest',
          returnType: 'ListBackendStagesResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listWafStages',
          protoName: 'ListWafStages',
          paramsType: 'ListWafStagesRequest',
          returnType: 'ListWafStagesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'WafStage',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getWafStage',
          protoName: 'GetWafStage',
          paramsType: 'GetWafStageRequest',
          returnType: 'WafStage',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'searchWafStages',
          protoName: 'SearchWafStages',
          paramsType: 'SearchWafStagesRequest',
          returnType: 'ListWafStagesResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listRouteStages',
          protoName: 'ListRouteStages',
          paramsType: 'ListRouteStagesRequest',
          returnType: 'ListRouteStagesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'RouteStage',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRouteStage',
          protoName: 'GetRouteStage',
          paramsType: 'GetRouteStageRequest',
          returnType: 'RouteStage',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listRouteRules',
          protoName: 'ListRouteRules',
          paramsType: 'ListRouteRulesRequest',
          returnType: 'ListRouteRulesResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'searchRouteRules',
          protoName: 'SearchRouteRules',
          paramsType: 'SearchRouteRulesRequest',
          returnType: 'ListRouteRulesResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listPurgeRequests',
          protoName: 'ListPurgeRequests',
          paramsType: 'ListPurgeRequestsRequest',
          returnType: 'ListPurgeRequestsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'PurgeRequest',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getPurgeRequest',
          protoName: 'GetPurgeRequest',
          paramsType: 'GetPurgeRequestRequest',
          returnType: 'PurgeRequest',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listPlans',
          protoName: 'ListPlans',
          paramsType: '',
          returnType: 'ListPlansResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getCurrentPlan',
          protoName: 'GetCurrentPlan',
          paramsType: 'GetCurrentPlanRequest',
          returnType: 'Plan',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getBilling',
          protoName: 'GetBilling',
          paramsType: 'GetBillingRequest',
          returnType: 'GetBillingResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
