// --- Types ---

export interface QueryMethod {
  methodName: string
  protoName: string
  paramsType: string
  returnType: string
  isList: boolean
  paginationType?: 'offset' | 'cursor' | 'none'
  pageParamKey?: string
  listItemType?: string
  nextPageField?: string
  isPrivate: boolean
  description?: string
  hasWaiter?: boolean
}

export interface ServiceMetadata {
  apiClass: string
  methods: QueryMethod[]
}

export interface QueriesMetadata {
  namespace: string
  version: string
  folderName: string
  services: ServiceMetadata[]
}

// --- Config ---

export interface ReactQueriesConfig {
  outputDir: string
  generatedPath: string
  customPath: string
  customNamespaces: Map<string, string>

  // Optional path to a directory containing SDK packages directly (e.g. 'packages_generated/').
  // When set, packages are resolved from this directory instead of node_modules.
  // Each subdirectory should be a package with a package.json and dist/.
  packagesPath?: string

  imports: {
    apiSdkPath: string
    packageNameFilter: string
    dataLoaderPackage: string
  }

  naming: {
    hookPrefix: string
    reloadPrefix: string
    waiterPrefix: string
    allKeySuffix: string
    indexFile: string
    metadataFileName: string
  }

  filters: {
    skipMethods: string[]
    skipPrivateMethods: boolean
    skipCursorAllHooks: boolean
    rawTypes: string[]
  }

  generatedComment: string
}

export const defaultConfig: ReactQueriesConfig = {
  outputDir: 'src/queries',
  generatedPath: 'generated',
  customPath: 'custom',
  customNamespaces: new Map([
    ['Instancev1', 'InstanceV1UtilsAPI'],
    ['K8Sv1', 'K8SUtilsAPI'],
  ]),

  imports: {
    apiSdkPath: '@scaleway/sdk-react',
    packageNameFilter: '@scaleway/sdk-',
    dataLoaderPackage: '@scaleway/use-dataloader',
  },

  naming: {
    hookPrefix: 'use',
    reloadPrefix: 'reload',
    waiterPrefix: 'WaitFor',
    allKeySuffix: 'all',
    indexFile: 'index.ts',
    metadataFileName: 'metadata.gen.ts',
  },

  filters: {
    skipMethods: ['getServiceInfo'],
    skipPrivateMethods: true,
    skipCursorAllHooks: true,
    rawTypes: ['Blob', 'string', 'number', 'boolean'],
  },

  generatedComment:
    '// This file is generated by @scaleway/generate-react-queries placed in https://github.com/scaleway/scaleway-sdk-js` all modifications will be erased',
}

// --- Utils ---

export function capitalize(str: string): string {
  if (!str) return str
  return str.charAt(0).toUpperCase() + str.slice(1)
}

export function lowerCaseFirst(str: string): string {
  if (!str) return str
  return str.charAt(0).toLowerCase() + str.slice(1)
}
