/**
 * Types, configuration, and string utilities for the React Query hook generator.
 *
 * Metadata types mirror what each SDK package exports in its metadata.gen.ts.
 * Config controls naming conventions, filtering, and import paths.
 */

import { existsSync, readFileSync } from 'node:fs'

// --- Types (mirror metadata.gen.ts structure in each SDK package) ---

/** A single API method that will become a React Query hook. */
export interface QueryMethod {
  methodName: string
  protoName: string
  paramsType: string
  returnType: string
  isList: boolean
  paginationType?: 'offset' | 'cursor' | 'none'
  pageParamKey?: string
  listItemType?: string
  nextPageField?: string
  isPrivate: boolean
  description?: string
  hasWaiter?: boolean
}

/** A service class (e.g. "API", "ZonedAPI") containing query methods. */
export interface ServiceMetadata {
  apiClass: string
  methods: QueryMethod[]
}

/** Top-level metadata for one API version (e.g. instance/v1). */
export interface QueriesMetadata {
  namespace: string
  version: string
  folderName: string
  services: ServiceMetadata[]
}

// --- Config ---

export interface ReactQueriesConfig {
  /** Where to write generated hook files (relative to CWD). */
  outputDir: string
  /** Subdirectory name for generated hooks inside each namespace folder. */
  generatedPath: string
  /** Subdirectory name for hand-written custom hooks. */
  customPath: string
  /** Maps namespace → utils API class name (e.g. Instancev1 → InstanceV1UtilsAPI). */
  customNamespaces: Map<string, string>

  /**
   * Path to SDK packages directory (e.g. 'packages_generated/').
   * When set, scans this directory directly instead of resolving from node_modules.
   */
  packagesPath?: string

  imports: {
    /** Package that provides the useXxxAPI() hooks (e.g. @scaleway/sdk-react). */
    apiSdkPath: string
    /** Only packages matching this prefix are processed (e.g. @scaleway/sdk-). */
    packageNameFilter: string
    /** Package providing useDataLoader / useInfiniteDataLoader. */
    dataLoaderPackage: string
  }

  naming: {
    hookPrefix: string
    reloadPrefix: string
    waiterPrefix: string
    allKeySuffix: string
    indexFile: string
    /** File name to look for in each package's dist/<version>/. */
    metadataFileName: string
  }

  filters: {
    /** Method names to skip entirely (e.g. getServiceInfo). */
    skipMethods: string[]
    skipPrivateMethods: boolean
    /** Skip generating "all" hooks for cursor-paginated methods. */
    skipCursorAllHooks: boolean
    /** Types that don't need a namespace prefix (e.g. string, Blob). */
    rawTypes: string[]
    /** Skip generating waiter (polling) hooks for methods with hasWaiter. */
    skipWaiters: boolean
    /** Package names to exclude from generation (e.g. @scaleway/sdk-test). */
    skipPackages: string[]
    /** Service classes to exclude (matched against service.apiClass). */
    skipServices: string[]
    /**
     * Versions to exclude. "<package>@<version>" skips only that package's
     * version; a bare "<version>" skips it for all packages.
     */
    skipVersions: string[]
  }

  generatedComment: string
}

export const defaultConfig: ReactQueriesConfig = {
  outputDir: 'src/queries',
  generatedPath: 'generated',
  customPath: 'custom',
  customNamespaces: new Map([
    ['Instancev1', 'InstanceV1UtilsAPI'],
    ['K8Sv1', 'K8SUtilsAPI'],
  ]),

  imports: {
    apiSdkPath: '@scaleway/sdk-react',
    packageNameFilter: '@scaleway/sdk-',
    dataLoaderPackage: '@scaleway/use-dataloader',
  },

  naming: {
    hookPrefix: 'use',
    reloadPrefix: 'reload',
    waiterPrefix: 'WaitFor',
    allKeySuffix: 'all',
    indexFile: 'index.ts',
    metadataFileName: 'metadata.gen.ts',
  },

  filters: {
    skipMethods: ['getServiceInfo'],
    skipPrivateMethods: true,
    skipCursorAllHooks: true,
    skipWaiters: true,
    rawTypes: ['Blob', 'string', 'number', 'boolean'],
    skipPackages: ['@scaleway/sdk-test'],
    skipServices: [],
    skipVersions: [],
  },

  generatedComment:
    '// This file is generated by @scaleway/generate-react-queries placed in https://github.com/scaleway/scaleway-sdk-js` all modifications will be erased',
}

// --- String utils ---

export function capitalize(str: string): string {
  if (!str) return str
  return str.charAt(0).toUpperCase() + str.slice(1)
}

export function lowerCaseFirst(str: string): string {
  if (!str) return str
  return str.charAt(0).toLowerCase() + str.slice(1)
}

// --- Config helpers ---

/**
 * Load and parse a JSON config file, returning undefined (with a warning) if
 * the file is missing or malformed.
 */
export function loadJsonConfig<T>(path?: string): T | undefined {
  if (!path) return undefined
  if (!existsSync(path)) {
    console.warn(`⚠️  Config file not found: ${path} (ignored)`)
    return undefined
  }
  try {
    return JSON.parse(readFileSync(path, 'utf-8')) as T
  } catch (error) {
    console.warn(`⚠️  Could not parse config file ${path}: ${error}`)
    return undefined
  }
}
