/**
 * This file is automatically generated from /scripts/generate.js
 * PLEASE DO NOT EDIT HERE
 */

import * as Account from "@scaleway/sdk-account/index.gen"
import * as Applesilicon from "@scaleway/sdk-applesilicon/index.gen"
import * as AuditTrail from "@scaleway/sdk-audit-trail/index.gen"
import * as Baremetal from "@scaleway/sdk-baremetal/index.gen"
import * as Billing from "@scaleway/sdk-billing/index.gen"
import * as Block from "@scaleway/sdk-block/index.gen"
import * as Cockpit from "@scaleway/sdk-cockpit/index.gen"
import * as Container from "@scaleway/sdk-container/index.gen"
import * as Dedibox from "@scaleway/sdk-dedibox/index.gen"
import * as Domain from "@scaleway/sdk-domain/index.gen"
import * as EdgeServices from "@scaleway/sdk-edge-services/index.gen"
import * as File from "@scaleway/sdk-file/index.gen"
import * as Flexibleip from "@scaleway/sdk-flexibleip/index.gen"
import * as Function from "@scaleway/sdk-function/index.gen"
import * as Iam from "@scaleway/sdk-iam/index.gen"
import * as Inference from "@scaleway/sdk-inference/index.gen"
import * as Instance from "@scaleway/sdk-instance/index.gen"
import * as Interlink from "@scaleway/sdk-interlink/index.gen"
import * as Iot from "@scaleway/sdk-iot/index.gen"
import * as Ipam from "@scaleway/sdk-ipam/index.gen"
import * as Jobs from "@scaleway/sdk-jobs/index.gen"
import * as K8s from "@scaleway/sdk-k8s/index.gen"
import * as KeyManager from "@scaleway/sdk-key-manager/index.gen"
import * as Lb from "@scaleway/sdk-lb/index.gen"
import * as Marketplace from "@scaleway/sdk-marketplace/index.gen"
import * as Mnq from "@scaleway/sdk-mnq/index.gen"
import * as Mongodb from "@scaleway/sdk-mongodb/index.gen"
import * as ProductCatalog from "@scaleway/sdk-product-catalog/index.gen"
import * as Qaas from "@scaleway/sdk-qaas/index.gen"
import * as Rdb from "@scaleway/sdk-rdb/index.gen"
import * as Redis from "@scaleway/sdk-redis/index.gen"
import * as Registry from "@scaleway/sdk-registry/index.gen"
import * as Secret from "@scaleway/sdk-secret/index.gen"
import * as ServerlessSqldb from "@scaleway/sdk-serverless-sqldb/index.gen"
import * as Tem from "@scaleway/sdk-tem/index.gen"
import * as Test from "@scaleway/sdk-test/index.gen"
import * as Vpc from "@scaleway/sdk-vpc/index.gen"
import * as Vpcgw from "@scaleway/sdk-vpcgw/index.gen"
import * as Webhosting from "@scaleway/sdk-webhosting/index.gen"
import * as Std from './std/index.gen'

export {
  Account,
  Applesilicon,
  AuditTrail,
  Baremetal,
  Billing,
  Block,
  Cockpit,
  Container,
  Dedibox,
  Domain,
  EdgeServices,
  File,
  Flexibleip,
  Function,
  Iam,
  Inference,
  Instance,
  Interlink,
  Iot,
  Ipam,
  Jobs,
  K8s,
  KeyManager,
  Lb,
  Marketplace,
  Mnq,
  Mongodb,
  ProductCatalog,
  Qaas,
  Rdb,
  Redis,
  Registry,
  Secret,
  ServerlessSqldb,
  Std,
  Tem,
  Test,
  Vpc,
  Vpcgw,
  Webhosting,
}
