/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: "@scaleway/sdk-registry",
  namespace: "registry",
  displayName: "Registry",
  versions: ["v1"]
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
