// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'iam',
  version: 'v1alpha1',
  folderName: 'iamv1alpha1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listSSHKeys',
          protoName: 'ListSSHKeys',
          paramsType: 'ListSSHKeysRequest',
          returnType: 'ListSSHKeysResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'SSHKey',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSSHKey',
          protoName: 'GetSSHKey',
          paramsType: 'GetSSHKeyRequest',
          returnType: 'SSHKey',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listUsers',
          protoName: 'ListUsers',
          paramsType: 'ListUsersRequest',
          returnType: 'ListUsersResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'User',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getUser',
          protoName: 'GetUser',
          paramsType: 'GetUserRequest',
          returnType: 'User',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listGracePeriods',
          protoName: 'ListGracePeriods',
          paramsType: 'ListGracePeriodsRequest',
          returnType: 'ListGracePeriodsResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getUserConnections',
          protoName: 'GetUserConnections',
          paramsType: 'GetUserConnectionsRequest',
          returnType: 'GetUserConnectionsResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listApplications',
          protoName: 'ListApplications',
          paramsType: 'ListApplicationsRequest',
          returnType: 'ListApplicationsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Application',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getApplication',
          protoName: 'GetApplication',
          paramsType: 'GetApplicationRequest',
          returnType: 'Application',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listGroups',
          protoName: 'ListGroups',
          paramsType: 'ListGroupsRequest',
          returnType: 'ListGroupsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Group',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getGroup',
          protoName: 'GetGroup',
          paramsType: 'GetGroupRequest',
          returnType: 'Group',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listPolicies',
          protoName: 'ListPolicies',
          paramsType: 'ListPoliciesRequest',
          returnType: 'ListPoliciesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Policy',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getPolicy',
          protoName: 'GetPolicy',
          paramsType: 'GetPolicyRequest',
          returnType: 'Policy',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listRules',
          protoName: 'ListRules',
          paramsType: 'ListRulesRequest',
          returnType: 'ListRulesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Rule',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listPermissionSets',
          protoName: 'ListPermissionSets',
          paramsType: 'ListPermissionSetsRequest',
          returnType: 'ListPermissionSetsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'PermissionSet',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listAPIKeys',
          protoName: 'ListAPIKeys',
          paramsType: 'ListAPIKeysRequest',
          returnType: 'ListAPIKeysResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'APIKey',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getAPIKey',
          protoName: 'GetAPIKey',
          paramsType: 'GetAPIKeyRequest',
          returnType: 'APIKey',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listQuota',
          protoName: 'ListQuota',
          paramsType: 'ListQuotaRequest',
          returnType: 'ListQuotaResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Quotum',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getQuotum',
          protoName: 'GetQuotum',
          paramsType: 'GetQuotumRequest',
          returnType: 'Quotum',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listJWTs',
          protoName: 'ListJWTs',
          paramsType: 'ListJWTsRequest',
          returnType: 'ListJWTsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'JWT',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getJWT',
          protoName: 'GetJWT',
          paramsType: 'GetJWTRequest',
          returnType: 'JWT',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listLogs',
          protoName: 'ListLogs',
          paramsType: 'ListLogsRequest',
          returnType: 'ListLogsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Log',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getLog',
          protoName: 'GetLog',
          paramsType: 'GetLogRequest',
          returnType: 'Log',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getOrganizationSecuritySettings',
          protoName: 'GetOrganizationSecuritySettings',
          paramsType: 'GetOrganizationSecuritySettingsRequest',
          returnType: 'OrganizationSecuritySettings',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getOrganization',
          protoName: 'GetOrganization',
          paramsType: 'GetOrganizationRequest',
          returnType: 'Organization',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getOrganizationSaml',
          protoName: 'GetOrganizationSaml',
          paramsType: 'GetOrganizationSamlRequest',
          returnType: 'Saml',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSamlCertificates',
          protoName: 'ListSamlCertificates',
          paramsType: 'ListSamlCertificatesRequest',
          returnType: 'ListSamlCertificatesResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSamlCertificate',
          protoName: 'GetSamlCertificate',
          paramsType: 'GetSamlCertificateRequest',
          returnType: 'SamlCertificate',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getOrganizationScim',
          protoName: 'GetOrganizationScim',
          paramsType: 'GetOrganizationScimRequest',
          returnType: 'Scim',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listScimTokens',
          protoName: 'ListScimTokens',
          paramsType: 'ListScimTokensRequest',
          returnType: 'ListScimTokensResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ScimToken',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listUserWebAuthnAuthenticators',
          protoName: 'ListUserWebAuthnAuthenticators',
          paramsType: 'ListUserWebAuthnAuthenticatorsRequest',
          returnType: 'ListUserWebAuthnAuthenticatorsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'WebAuthnAuthenticator',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
