// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.
export { GlobalAPI, RegionalAPI } from './api.gen'
export type {
  AlertManager,
  ContactPoint,
  ContactPointEmail,
  DataSource,
  DataSourceOrigin,
  DataSourceType,
  GlobalApiCreateGrafanaUserRequest,
  GlobalApiDeleteGrafanaUserRequest,
  GlobalApiGetCurrentPlanRequest,
  GlobalApiGetGrafanaProductDashboardRequest,
  GlobalApiGetGrafanaRequest,
  GlobalApiListGrafanaProductDashboardsRequest,
  GlobalApiListGrafanaUsersRequest,
  GlobalApiListPlansRequest,
  GlobalApiResetGrafanaUserPasswordRequest,
  GlobalApiSelectPlanRequest,
  GlobalApiSyncGrafanaDataSourcesRequest,
  Grafana,
  GrafanaProductDashboard,
  GrafanaUser,
  GrafanaUserRole,
  ListContactPointsResponse,
  ListDataSourcesRequestOrderBy,
  ListDataSourcesResponse,
  ListGrafanaProductDashboardsResponse,
  ListGrafanaUsersRequestOrderBy,
  ListGrafanaUsersResponse,
  ListPlansRequestOrderBy,
  ListPlansResponse,
  ListTokensRequestOrderBy,
  ListTokensResponse,
  Plan,
  PlanName,
  RegionalApiCreateContactPointRequest,
  RegionalApiCreateDataSourceRequest,
  RegionalApiCreateTokenRequest,
  RegionalApiDeleteContactPointRequest,
  RegionalApiDeleteDataSourceRequest,
  RegionalApiDeleteTokenRequest,
  RegionalApiDisableAlertManagerRequest,
  RegionalApiDisableManagedAlertsRequest,
  RegionalApiEnableAlertManagerRequest,
  RegionalApiEnableManagedAlertsRequest,
  RegionalApiGetAlertManagerRequest,
  RegionalApiGetDataSourceRequest,
  RegionalApiGetTokenRequest,
  RegionalApiGetUsageOverviewRequest,
  RegionalApiListContactPointsRequest,
  RegionalApiListDataSourcesRequest,
  RegionalApiListTokensRequest,
  RegionalApiTriggerTestAlertRequest,
  Token,
  TokenScope,
  Usage,
  UsageOverview,
  UsageUnit,
} from './types.gen'
export * as ValidationRules from './validation-rules.gen'
