import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'

const { ENTRY_POINT } = process.env

if (!ENTRY_POINT) {
  throw new Error('ENTRY_POINT is not defined')
}

const INPUT_PATH_DIR = path.resolve(process.cwd(), ENTRY_POINT)

const DEFAULT_GENERATED_EXPORT_PATH = 'index.gen.ts' as const

const PRODUCT_EXPORT_FILE =
  `${INPUT_PATH_DIR}/${DEFAULT_GENERATED_EXPORT_PATH}` as const

const AUTO_GENERATE_MESSAGE = `/**
  * This file is automatically generated from /scripts/generate.js
  * PLEASE DO NOT EDIT HERE
  */\n
  ` as const

const CUSTOM = {
  /** Std is use for type generation */
  PRODUCT_EXPORT: new Set(['std']),
  /** Theses product are manually update to add waitFor... */
  PRODUCT_VERSION_EXPORT: new Set([
    'baremetal/v1',
    'instance/v1',
    'k8s/v1',
    'lb/v1',
  ]),
}

const upperFirst = (str: string) =>
  str.slice(0, 1).toUpperCase() + str.slice(1, str.length)

const snakeToPascal = (str: string) =>
  str
    .split('_')
    .map(s => upperFirst(s.split('/').map(upperFirst).join('/')))
    .join('')

const exportProductVersions = (productDir: string) => {
  const fullPath = path.join(INPUT_PATH_DIR, productDir)
  const versionDirs = fs.readdirSync(fullPath)

  const pathFile = `${fullPath}/${DEFAULT_GENERATED_EXPORT_PATH}` as const

  fs.writeFileSync(pathFile, AUTO_GENERATE_MESSAGE)

  for (const versionDir of versionDirs) {
    const pathVersion = `${fullPath}/${versionDir}`

    if (fs.statSync(pathVersion).isDirectory()) {
      const exportPath = CUSTOM.PRODUCT_VERSION_EXPORT.has(
        `${productDir}/${versionDir}`,
      )
        ? `./${versionDir}/index`
        : `./${versionDir}/index.gen`

      fs.appendFileSync(
        pathFile,
        `\nexport * as ${versionDir} from '${exportPath}'`,
      )
    }
  }
}

/**
 * This function will an index.ts with an export of all product. Std is a custom
 * export as it's only serve for types.
 */
const exportProducts = () => {
  const productsDirs = fs.readdirSync(INPUT_PATH_DIR)
  const productExports = []

  fs.writeFileSync(PRODUCT_EXPORT_FILE, AUTO_GENERATE_MESSAGE)

  for (const productDir of productsDirs) {
    const fullPath = path.join(INPUT_PATH_DIR, productDir)

    if (fs.statSync(fullPath).isDirectory()) {
      if (!CUSTOM.PRODUCT_EXPORT.has(productDir)) {
        exportProductVersions(productDir)
      }

      fs.appendFileSync(
        PRODUCT_EXPORT_FILE,
        `\nimport * as ${snakeToPascal(productDir)} from './${productDir}/index.gen'`,
      )

      productExports.push(snakeToPascal(productDir))
    }
  }

  fs.appendFileSync(
    `${PRODUCT_EXPORT_FILE}`,
    `\n\nexport { ${productExports.toString()}}`,
  )
}

exportProducts()
