/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: '@scaleway/sdk-billing',
  namespace: 'billing',
  displayName: 'Billing',
  versions: ['v2beta1'],
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
