/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: '@scaleway/sdk-kafka',
  namespace: 'kafka',
  displayName: 'Kafka',
  versions: ['v1alpha1'],
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
