// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.
export { API } from './api.gen'
export * from './content.gen'
export type {
  CreateEndpointRequest,
  CreateInstanceRequest,
  CreateInstanceRequestVolumeDetails,
  CreateSnapshotRequest,
  CreateUserRequest,
  DeleteEndpointRequest,
  DeleteInstanceRequest,
  DeleteSnapshotRequest,
  DeleteUserRequest,
  Endpoint,
  EndpointPrivateNetworkDetails,
  EndpointPublicDetails,
  EndpointSpec,
  EndpointSpecPrivateNetworkDetails,
  EndpointSpecPublicDetails,
  GetInstanceCertificateRequest,
  GetInstanceRequest,
  GetSnapshotRequest,
  Instance,
  InstanceSetting,
  InstanceStatus,
  ListInstancesRequest,
  ListInstancesRequestOrderBy,
  ListInstancesResponse,
  ListNodeTypesRequest,
  ListNodeTypesResponse,
  ListSnapshotsRequest,
  ListSnapshotsRequestOrderBy,
  ListSnapshotsResponse,
  ListUsersRequest,
  ListUsersRequestOrderBy,
  ListUsersResponse,
  ListVersionsRequest,
  ListVersionsResponse,
  NodeType,
  NodeTypeStock,
  NodeTypeVolumeType,
  RestoreSnapshotRequest,
  RestoreSnapshotRequestVolumeDetails,
  Setting,
  SettingPropertyType,
  Snapshot,
  SnapshotStatus,
  SnapshotVolumeType,
  UpdateInstanceRequest,
  UpdateSnapshotRequest,
  UpdateUserRequest,
  UpgradeInstanceRequest,
  User,
  Version,
  Volume,
  VolumeType,
} from './types.gen'
export * as ValidationRules from './validation-rules.gen'
