// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'domain',
  version: 'v2beta1',
  folderName: 'domainv2beta1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listDNSZones',
          protoName: 'ListDNSZones',
          paramsType: 'ListDNSZonesRequest',
          returnType: 'ListDNSZonesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'DNSZone',
          listItemTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDNSZoneRecords',
          protoName: 'ListDNSZoneRecords',
          paramsType: 'ListDNSZoneRecordsRequest',
          returnType: 'ListDNSZoneRecordsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'DomainRecord',
          listItemTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDNSZoneNameservers',
          protoName: 'ListDNSZoneNameservers',
          paramsType: 'ListDNSZoneNameserversRequest',
          returnType: 'ListDNSZoneNameserversResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDNSZoneVersions',
          protoName: 'ListDNSZoneVersions',
          paramsType: 'ListDNSZoneVersionsRequest',
          returnType: 'ListDNSZoneVersionsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'DNSZoneVersion',
          listItemTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDNSZoneVersionRecords',
          protoName: 'ListDNSZoneVersionRecords',
          paramsType: 'ListDNSZoneVersionRecordsRequest',
          returnType: 'ListDNSZoneVersionRecordsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'DomainRecord',
          listItemTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDNSZoneVersionDiff',
          protoName: 'GetDNSZoneVersionDiff',
          paramsType: 'GetDNSZoneVersionDiffRequest',
          returnType: 'GetDNSZoneVersionDiffResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSSLCertificate',
          protoName: 'GetSSLCertificate',
          paramsType: 'GetSSLCertificateRequest',
          returnType: 'SSLCertificate',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listSSLCertificates',
          protoName: 'ListSSLCertificates',
          paramsType: 'ListSSLCertificatesRequest',
          returnType: 'ListSSLCertificatesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'SSLCertificate',
          listItemTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDNSZoneTsigKey',
          protoName: 'GetDNSZoneTsigKey',
          paramsType: 'GetDNSZoneTsigKeyRequest',
          returnType: 'GetDNSZoneTsigKeyResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'RegistrarAPI',
      methods: [
        {
          methodName: 'listTasks',
          protoName: 'ListTasks',
          paramsType: 'RegistrarApiListTasksRequest',
          returnType: 'ListTasksResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Task',
          listItemTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listInboundTransfers',
          protoName: 'ListInboundTransfers',
          paramsType: 'RegistrarApiListInboundTransfersRequest',
          returnType: 'ListInboundTransfersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'InboundTransfer',
          listItemTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listContacts',
          protoName: 'ListContacts',
          paramsType: 'RegistrarApiListContactsRequest',
          returnType: 'ListContactsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ContactRoles',
          listItemTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getContact',
          protoName: 'GetContact',
          paramsType: 'RegistrarApiGetContactRequest',
          returnType: 'Contact',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDomains',
          protoName: 'ListDomains',
          paramsType: 'RegistrarApiListDomainsRequest',
          returnType: 'ListDomainsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'DomainSummary',
          listItemTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listRenewableDomains',
          protoName: 'ListRenewableDomains',
          paramsType: 'RegistrarApiListRenewableDomainsRequest',
          returnType: 'ListRenewableDomainsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'RenewableDomain',
          listItemTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDomain',
          protoName: 'GetDomain',
          paramsType: 'RegistrarApiGetDomainRequest',
          returnType: 'Domain',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'getDomainAuthCode',
          protoName: 'GetDomainAuthCode',
          paramsType: 'RegistrarApiGetDomainAuthCodeRequest',
          returnType: 'GetDomainAuthCodeResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'searchAvailableDomains',
          protoName: 'SearchAvailableDomains',
          paramsType: 'RegistrarApiSearchAvailableDomainsRequest',
          returnType: 'SearchAvailableDomainsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listTlds',
          protoName: 'ListTlds',
          paramsType: 'RegistrarApiListTldsRequest',
          returnType: 'ListTldsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Tld',
          listItemTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listDomainHosts',
          protoName: 'ListDomainHosts',
          paramsType: 'RegistrarApiListDomainHostsRequest',
          returnType: 'ListDomainHostsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Host',
          listItemTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'UnauthenticatedRegistrarAPI',
      methods: [
        {
          methodName: 'getServiceInfo',
          protoName: 'GetServiceInfo',
          paramsType: '',
          returnType: 'ServiceInfo',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'searchAvailableDomainsConsole',
          protoName: 'SearchAvailableDomainsConsole',
          paramsType: 'UnauthenticatedRegistrarApiSearchAvailableDomainsConsoleRequest',
          returnType: 'SearchAvailableDomainsConsoleResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-domain/v2beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
