// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'container',
  version: 'v1',
  folderName: 'containerv1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'getServiceInfo',
          protoName: 'GetServiceInfo',
          paramsType: 'GetServiceInfoRequest',
          returnType: 'ServiceInfo',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getNamespace',
          protoName: 'GetNamespace',
          paramsType: 'GetNamespaceRequest',
          returnType: 'Namespace',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listNamespaces',
          protoName: 'ListNamespaces',
          paramsType: 'ListNamespacesRequest',
          returnType: 'ListNamespacesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Namespace',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getContainer',
          protoName: 'GetContainer',
          paramsType: 'GetContainerRequest',
          returnType: 'Container',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listContainers',
          protoName: 'ListContainers',
          paramsType: 'ListContainersRequest',
          returnType: 'ListContainersResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Container',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDomain',
          protoName: 'GetDomain',
          paramsType: 'GetDomainRequest',
          returnType: 'Domain',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listDomains',
          protoName: 'ListDomains',
          paramsType: 'ListDomainsRequest',
          returnType: 'ListDomainsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Domain',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getTrigger',
          protoName: 'GetTrigger',
          paramsType: 'GetTriggerRequest',
          returnType: 'Trigger',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listTriggers',
          protoName: 'ListTriggers',
          paramsType: 'ListTriggersRequest',
          returnType: 'ListTriggersResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Trigger',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
