// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'k8s',
  version: 'v1',
  folderName: 'k8Sv1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listClusters',
          protoName: 'ListClusters',
          paramsType: 'ListClustersRequest',
          returnType: 'ListClustersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Cluster',
          listItemTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getCluster',
          protoName: 'GetCluster',
          paramsType: 'GetClusterRequest',
          returnType: 'Cluster',
          returnTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listClusterAvailableVersions',
          protoName: 'ListClusterAvailableVersions',
          paramsType: 'ListClusterAvailableVersionsRequest',
          returnType: 'ListClusterAvailableVersionsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listClusterAvailableTypes',
          protoName: 'ListClusterAvailableTypes',
          paramsType: 'ListClusterAvailableTypesRequest',
          returnType: 'ListClusterAvailableTypesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: '_getClusterKubeConfig',
          protoName: 'GetClusterKubeConfig',
          paramsType: 'GetClusterKubeConfigRequest',
          returnType: 'Blob',
          returnTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: true,
          description: '"',
        },
        {
          methodName: 'listClusterACLRules',
          protoName: 'ListClusterACLRules',
          paramsType: 'ListClusterACLRulesRequest',
          returnType: 'ListClusterACLRulesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ACLRule',
          listItemTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listPools',
          protoName: 'ListPools',
          paramsType: 'ListPoolsRequest',
          returnType: 'ListPoolsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Pool',
          listItemTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getPool',
          protoName: 'GetPool',
          paramsType: 'GetPoolRequest',
          returnType: 'Pool',
          returnTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'getUserData',
          protoName: 'GetUserData',
          paramsType: 'GetUserDataRequest',
          returnType: 'Blob',
          returnTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getNodeMetadata',
          protoName: 'GetNodeMetadata',
          paramsType: 'GetNodeMetadataRequest',
          returnType: 'NodeMetadata',
          returnTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listNodes',
          protoName: 'ListNodes',
          paramsType: 'ListNodesRequest',
          returnType: 'ListNodesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Node',
          listItemTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getNode',
          protoName: 'GetNode',
          paramsType: 'GetNodeRequest',
          returnType: 'Node',
          returnTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listVersions',
          protoName: 'ListVersions',
          paramsType: 'ListVersionsRequest',
          returnType: 'ListVersionsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getVersion',
          protoName: 'GetVersion',
          paramsType: 'GetVersionRequest',
          returnType: 'Version',
          returnTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listClusterTypes',
          protoName: 'ListClusterTypes',
          paramsType: 'ListClusterTypesRequest',
          returnType: 'ListClusterTypesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ClusterType',
          listItemTypeNamespace: '@scaleway-internal/sdk-k8s/v1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
