// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.
export { API } from './api.gen'
export type {
  AccessSecretVersionByNameRequest,
  AccessSecretVersionRequest,
  AccessSecretVersionResponse,
  AddSecretOwnerRequest,
  CreateSecretRequest,
  CreateSecretVersionRequest,
  DeleteSecretRequest,
  DestroySecretVersionRequest,
  DisableSecretVersionRequest,
  EnableSecretVersionRequest,
  GeneratePasswordRequest,
  GetSecretByNameRequest,
  GetSecretRequest,
  GetSecretVersionByNameRequest,
  GetSecretVersionRequest,
  ListSecretVersionsByNameRequest,
  ListSecretVersionsRequest,
  ListSecretVersionsResponse,
  ListSecretsRequest,
  ListSecretsRequestOrderBy,
  ListSecretsResponse,
  ListTagsRequest,
  ListTagsResponse,
  PasswordGenerationParams,
  Product,
  ProtectSecretRequest,
  Secret,
  SecretStatus,
  SecretType,
  SecretVersion,
  SecretVersionStatus,
  UnprotectSecretRequest,
  UpdateSecretRequest,
  UpdateSecretVersionRequest,
} from './types.gen'
