/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: "@scaleway/sdk-container",
  namespace: "container",
  displayName: "Container",
  versions: ["v1", "v1beta1"]
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
