/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: "@scaleway/sdk-redis",
  namespace: "redis",
  displayName: "Redis",
  versions: ["v1"]
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
