// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'qaas',
  version: 'v1alpha1',
  folderName: 'qaasv1alpha1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'getJob',
          protoName: 'GetJob',
          paramsType: 'GetJobRequest',
          returnType: 'Job',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listJobs',
          protoName: 'ListJobs',
          paramsType: 'ListJobsRequest',
          returnType: 'ListJobsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Job',
          listItemTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listJobResults',
          protoName: 'ListJobResults',
          paramsType: 'ListJobResultsRequest',
          returnType: 'ListJobResultsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'JobResult',
          listItemTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getJobCircuit',
          protoName: 'GetJobCircuit',
          paramsType: 'GetJobCircuitRequest',
          returnType: 'JobCircuit',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getPlatform',
          protoName: 'GetPlatform',
          paramsType: 'GetPlatformRequest',
          returnType: 'Platform',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listPlatforms',
          protoName: 'ListPlatforms',
          paramsType: 'ListPlatformsRequest',
          returnType: 'ListPlatformsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Platform',
          listItemTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSession',
          protoName: 'GetSession',
          paramsType: 'GetSessionRequest',
          returnType: 'Session',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listSessions',
          protoName: 'ListSessions',
          paramsType: 'ListSessionsRequest',
          returnType: 'ListSessionsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Session',
          listItemTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSessionACLs',
          protoName: 'ListSessionACLs',
          paramsType: 'ListSessionACLsRequest',
          returnType: 'ListSessionACLsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'SessionAccess',
          listItemTypeNamespace: 'SessionAccess',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getProcess',
          protoName: 'GetProcess',
          paramsType: 'GetProcessRequest',
          returnType: 'Process',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listProcesses',
          protoName: 'ListProcesses',
          paramsType: 'ListProcessesRequest',
          returnType: 'ListProcessesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Process',
          listItemTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listProcessResults',
          protoName: 'ListProcessResults',
          paramsType: 'ListProcessResultsRequest',
          returnType: 'ListProcessResultsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ProcessResult',
          listItemTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getApplication',
          protoName: 'GetApplication',
          paramsType: 'GetApplicationRequest',
          returnType: 'Application',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listApplications',
          protoName: 'ListApplications',
          paramsType: 'ListApplicationsRequest',
          returnType: 'ListApplicationsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Application',
          listItemTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getBooking',
          protoName: 'GetBooking',
          paramsType: 'GetBookingRequest',
          returnType: 'Booking',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listBookings',
          protoName: 'ListBookings',
          paramsType: 'ListBookingsRequest',
          returnType: 'ListBookingsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Booking',
          listItemTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getModel',
          protoName: 'GetModel',
          paramsType: 'GetModelRequest',
          returnType: 'Model',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listModels',
          protoName: 'ListModels',
          paramsType: 'ListModelsRequest',
          returnType: 'ListModelsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Model',
          listItemTypeNamespace: '@scaleway-internal/sdk-qaas/v1alpha1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
