/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: '@scaleway/sdk-searchdb',
  namespace: 'searchdb',
  displayName: 'Searchdb',
  versions: ['v1alpha1'],
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
