#!/usr/bin/env tsx

/**
 * Format only configuration files generated by generatePackages.ts
 * (tsconfig.json, tsconfig.build.json, vite.config.ts, package.json)
 * This script is used in prebuild to format these files without
 * reformatting .gen.ts files that were already formatted by the external script.
 */

import { execSync } from 'node:child_process'
import { readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'

const CONFIG_FILES = [
  'tsconfig.json',
  'tsconfig.build.json',
  'vite.config.ts',
  'package.json',
]

function findConfigFiles(dir: string, fileList: string[] = []): string[] {
  const files = readdirSync(dir)
  for (const file of files) {
    const filePath = join(dir, file)
    const stat = statSync(filePath)
    if (stat.isDirectory()) {
      findConfigFiles(filePath, fileList)
    } else if (CONFIG_FILES.includes(file)) {
      fileList.push(filePath)
    }
  }
  return fileList
}

async function main(): Promise<void> {
  const rootDir = process.cwd()
  const packagesGeneratedDir = join(rootDir, 'packages_generated')
  const configFiles = findConfigFiles(packagesGeneratedDir)

  if (configFiles.length === 0) {
    console.log('No config files found to format')
    return
  }

  console.log(`Formatting ${configFiles.length} config file(s)...`)

  // Format all config files at once
  const filesArg = configFiles.map(f => `"${f}"`).join(' ')
  try {
    execSync(
      `pnpm biome format --write --config-path scripts/templates/biome.generated.json ${filesArg}`,
      { stdio: 'inherit' },
    )
  } catch (error) {
    console.error(`Error formatting config files:`, error)
    process.exit(1)
  }

  console.log('✅ Config files formatted successfully')
}

main().catch(error => {
  console.error(error)
  process.exit(1)
})
