#!/usr/bin/env tsx

/**
 * Format only configuration files generated by generatePackages.ts
 * (tsconfig.json, tsconfig.build.json, vite.config.ts, package.json)
 * This script is used in prebuild to format these files without
 * reformatting .gen.ts files that were already formatted by the external script.
 */

import { execSync } from 'node:child_process'
import { readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'

const CONFIG_FILES = [
  'tsconfig.json',
  'tsconfig.build.json',
  'vite.config.ts',
  'package.json',
]

function findConfigFiles(dir: string, fileList: string[] = []): string[] {
  const files = readdirSync(dir)
  for (const file of files) {
    // Skip node_modules directories
    if (file === 'node_modules') {
      continue
    }
    const filePath = join(dir, file)
    const stat = statSync(filePath)
    if (stat.isDirectory()) {
      findConfigFiles(filePath, fileList)
    } else if (CONFIG_FILES.includes(file)) {
      fileList.push(filePath)
    }
  }
  return fileList
}

async function main(): Promise<void> {
  const rootDir = process.cwd()
  const packagesGeneratedDir = join(rootDir, 'packages_generated')
  const configFiles = findConfigFiles(packagesGeneratedDir)

  if (configFiles.length === 0) {
    console.log('No config files found to format')
    return
  }

  console.log(`Formatting ${configFiles.length} config file(s)...`)

  // Format files in batches to avoid command line length issues
  // and handle errors gracefully
  const batchSize = 50
  let formattedCount = 0
  let errorCount = 0

  for (let i = 0; i < configFiles.length; i += batchSize) {
    const batch = configFiles.slice(i, i + batchSize)
    const filesArg = batch.map(f => `"${f}"`).join(' ')
    try {
      execSync(
        `pnpm biome format --write --files-ignore-unknown=true ${filesArg}`,
        { stdio: 'pipe' },
      )
      formattedCount += batch.length
    } catch (error) {
      // Continue with other files even if some fail
      errorCount += batch.length
      console.warn(`Warning: Failed to format ${batch.length} file(s)`)
    }
  }

  if (errorCount > 0) {
    console.warn(
      `⚠️  Formatted ${formattedCount} file(s), ${errorCount} file(s) had errors`,
    )
  } else {
    console.log(`✅ Formatted ${formattedCount} config file(s) successfully`)
  }
}

main().catch(error => {
  console.error(error)
  process.exit(1)
})
