// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'tem',
  version: 'v1alpha1',
  folderName: 'temv1alpha1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'getEmail',
          protoName: 'GetEmail',
          paramsType: 'GetEmailRequest',
          returnType: 'Email',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listEmails',
          protoName: 'ListEmails',
          paramsType: 'ListEmailsRequest',
          returnType: 'ListEmailsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Email',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getStatistics',
          protoName: 'GetStatistics',
          paramsType: 'GetStatisticsRequest',
          returnType: 'Statistics',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDomain',
          protoName: 'GetDomain',
          paramsType: 'GetDomainRequest',
          returnType: 'Domain',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listDomains',
          protoName: 'ListDomains',
          paramsType: 'ListDomainsRequest',
          returnType: 'ListDomainsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Domain',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDomainLastStatus',
          protoName: 'GetDomainLastStatus',
          paramsType: 'GetDomainLastStatusRequest',
          returnType: 'DomainLastStatus',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listWebhooks',
          protoName: 'ListWebhooks',
          paramsType: 'ListWebhooksRequest',
          returnType: 'ListWebhooksResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Webhook',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getWebhook',
          protoName: 'GetWebhook',
          paramsType: 'GetWebhookRequest',
          returnType: 'Webhook',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listWebhookEvents',
          protoName: 'ListWebhookEvents',
          paramsType: 'ListWebhookEventsRequest',
          returnType: 'ListWebhookEventsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'WebhookEvent',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getProjectSettings',
          protoName: 'GetProjectSettings',
          paramsType: 'GetProjectSettingsRequest',
          returnType: 'ProjectSettings',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listBlocklists',
          protoName: 'ListBlocklists',
          paramsType: 'ListBlocklistsRequest',
          returnType: 'ListBlocklistsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Blocklist',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listOfferSubscriptions',
          protoName: 'ListOfferSubscriptions',
          paramsType: 'ListOfferSubscriptionsRequest',
          returnType: 'ListOfferSubscriptionsResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listOffers',
          protoName: 'ListOffers',
          paramsType: 'ListOffersRequest',
          returnType: 'ListOffersResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listPools',
          protoName: 'ListPools',
          paramsType: 'ListPoolsRequest',
          returnType: 'ListPoolsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Pool',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getProjectConsumption',
          protoName: 'GetProjectConsumption',
          paramsType: 'GetProjectConsumptionRequest',
          returnType: 'ProjectConsumption',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
