// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'messageq',
  version: 'v1alpha1',
  folderName: 'messageqv1alpha1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'getDeployment',
          protoName: 'GetDeployment',
          paramsType: 'GetDeploymentRequest',
          returnType: 'Deployment',
          returnTypeNamespace: '@scaleway-internal/sdk-messageq/v1alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listDeployments',
          protoName: 'ListDeployments',
          paramsType: 'ListDeploymentsRequest',
          returnType: 'ListDeploymentsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-messageq/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Deployment',
          listItemTypeNamespace: '@scaleway-internal/sdk-messageq/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listVersions',
          protoName: 'ListVersions',
          paramsType: 'ListVersionsRequest',
          returnType: 'ListVersionsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-messageq/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Version',
          listItemTypeNamespace: '@scaleway-internal/sdk-messageq/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listNodeTypes',
          protoName: 'ListNodeTypes',
          paramsType: 'ListNodeTypesRequest',
          returnType: 'ListNodeTypesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-messageq/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'NodeType',
          listItemTypeNamespace: '@scaleway-internal/sdk-messageq/v1alpha1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listUsers',
          protoName: 'ListUsers',
          paramsType: 'ListUsersRequest',
          returnType: 'ListUsersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-messageq/v1alpha1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'User',
          listItemTypeNamespace: '@scaleway-internal/sdk-messageq/v1alpha1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
