// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'container',
  version: 'v1beta1',
  folderName: 'containerv1beta1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listNamespaces',
          protoName: 'ListNamespaces',
          paramsType: 'ListNamespacesRequest',
          returnType: 'ListNamespacesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Namespace',
          listItemTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getNamespace',
          protoName: 'GetNamespace',
          paramsType: 'GetNamespaceRequest',
          returnType: 'Namespace',
          returnTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listContainers',
          protoName: 'ListContainers',
          paramsType: 'ListContainersRequest',
          returnType: 'ListContainersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Container',
          listItemTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getContainer',
          protoName: 'GetContainer',
          paramsType: 'GetContainerRequest',
          returnType: 'Container',
          returnTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listCrons',
          protoName: 'ListCrons',
          paramsType: 'ListCronsRequest',
          returnType: 'ListCronsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Cron',
          listItemTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getCron',
          protoName: 'GetCron',
          paramsType: 'GetCronRequest',
          returnType: 'Cron',
          returnTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listDomains',
          protoName: 'ListDomains',
          paramsType: 'ListDomainsRequest',
          returnType: 'ListDomainsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Domain',
          listItemTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDomain',
          protoName: 'GetDomain',
          paramsType: 'GetDomainRequest',
          returnType: 'Domain',
          returnTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'getToken',
          protoName: 'GetToken',
          paramsType: 'GetTokenRequest',
          returnType: 'Token',
          returnTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listTokens',
          protoName: 'ListTokens',
          paramsType: 'ListTokensRequest',
          returnType: 'ListTokensResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Token',
          listItemTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getTrigger',
          protoName: 'GetTrigger',
          paramsType: 'GetTriggerRequest',
          returnType: 'Trigger',
          returnTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listTriggers',
          protoName: 'ListTriggers',
          paramsType: 'ListTriggersRequest',
          returnType: 'ListTriggersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Trigger',
          listItemTypeNamespace: '@scaleway-internal/sdk-container/v1beta1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
