// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'lb',
  version: 'v1',
  folderName: 'lbv1',
  services: [
    {
      apiClass: 'ZonedAPI',
      methods: [
        {
          methodName: 'listLbs',
          protoName: 'ListLbs',
          paramsType: 'ZonedApiListLbsRequest',
          returnType: 'ListLbsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Lb',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getLb',
          protoName: 'GetLb',
          paramsType: 'ZonedApiGetLbRequest',
          returnType: 'Lb',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listIPs',
          protoName: 'ListIPs',
          paramsType: 'ZonedApiListIPsRequest',
          returnType: 'ListIpsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Ip',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getIp',
          protoName: 'GetIp',
          paramsType: 'ZonedApiGetIpRequest',
          returnType: 'Ip',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listBackends',
          protoName: 'ListBackends',
          paramsType: 'ZonedApiListBackendsRequest',
          returnType: 'ListBackendsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Backend',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getBackend',
          protoName: 'GetBackend',
          paramsType: 'ZonedApiGetBackendRequest',
          returnType: 'Backend',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listFrontends',
          protoName: 'ListFrontends',
          paramsType: 'ZonedApiListFrontendsRequest',
          returnType: 'ListFrontendsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Frontend',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getFrontend',
          protoName: 'GetFrontend',
          paramsType: 'ZonedApiGetFrontendRequest',
          returnType: 'Frontend',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listRoutes',
          protoName: 'ListRoutes',
          paramsType: 'ZonedApiListRoutesRequest',
          returnType: 'ListRoutesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Route',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRoute',
          protoName: 'GetRoute',
          paramsType: 'ZonedApiGetRouteRequest',
          returnType: 'Route',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getLbStats',
          protoName: 'GetLbStats',
          paramsType: 'ZonedApiGetLbStatsRequest',
          returnType: 'LbStats',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listBackendStats',
          protoName: 'ListBackendStats',
          paramsType: 'ZonedApiListBackendStatsRequest',
          returnType: 'ListBackendStatsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'BackendServerStats',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listAcls',
          protoName: 'ListAcls',
          paramsType: 'ZonedApiListAclsRequest',
          returnType: 'ListAclResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Acl',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getAcl',
          protoName: 'GetAcl',
          paramsType: 'ZonedApiGetAclRequest',
          returnType: 'Acl',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listCertificates',
          protoName: 'ListCertificates',
          paramsType: 'ZonedApiListCertificatesRequest',
          returnType: 'ListCertificatesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Certificate',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getCertificate',
          protoName: 'GetCertificate',
          paramsType: 'ZonedApiGetCertificateRequest',
          returnType: 'Certificate',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listLbTypes',
          protoName: 'ListLbTypes',
          paramsType: 'ZonedApiListLbTypesRequest',
          returnType: 'ListLbTypesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'LbType',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSubscriber',
          protoName: 'GetSubscriber',
          paramsType: 'ZonedApiGetSubscriberRequest',
          returnType: 'Subscriber',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSubscriber',
          protoName: 'ListSubscriber',
          paramsType: 'ZonedApiListSubscriberRequest',
          returnType: 'ListSubscriberResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Subscriber',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listLbPrivateNetworks',
          protoName: 'ListLbPrivateNetworks',
          paramsType: 'ZonedApiListLbPrivateNetworksRequest',
          returnType: 'ListLbPrivateNetworksResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'PrivateNetwork',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listLbs',
          protoName: 'ListLbs',
          paramsType: 'ListLbsRequest',
          returnType: 'ListLbsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Lb',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getLb',
          protoName: 'GetLb',
          paramsType: 'GetLbRequest',
          returnType: 'Lb',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listIPs',
          protoName: 'ListIPs',
          paramsType: 'ListIPsRequest',
          returnType: 'ListIpsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Ip',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getIp',
          protoName: 'GetIp',
          paramsType: 'GetIpRequest',
          returnType: 'Ip',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listBackends',
          protoName: 'ListBackends',
          paramsType: 'ListBackendsRequest',
          returnType: 'ListBackendsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Backend',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getBackend',
          protoName: 'GetBackend',
          paramsType: 'GetBackendRequest',
          returnType: 'Backend',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listFrontends',
          protoName: 'ListFrontends',
          paramsType: 'ListFrontendsRequest',
          returnType: 'ListFrontendsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Frontend',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getFrontend',
          protoName: 'GetFrontend',
          paramsType: 'GetFrontendRequest',
          returnType: 'Frontend',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listRoutes',
          protoName: 'ListRoutes',
          paramsType: 'ListRoutesRequest',
          returnType: 'ListRoutesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Route',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRoute',
          protoName: 'GetRoute',
          paramsType: 'GetRouteRequest',
          returnType: 'Route',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getLbStats',
          protoName: 'GetLbStats',
          paramsType: 'GetLbStatsRequest',
          returnType: 'LbStats',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listBackendStats',
          protoName: 'ListBackendStats',
          paramsType: 'ListBackendStatsRequest',
          returnType: 'ListBackendStatsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'BackendServerStats',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listAcls',
          protoName: 'ListAcls',
          paramsType: 'ListAclsRequest',
          returnType: 'ListAclResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Acl',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getAcl',
          protoName: 'GetAcl',
          paramsType: 'GetAclRequest',
          returnType: 'Acl',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listCertificates',
          protoName: 'ListCertificates',
          paramsType: 'ListCertificatesRequest',
          returnType: 'ListCertificatesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Certificate',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getCertificate',
          protoName: 'GetCertificate',
          paramsType: 'GetCertificateRequest',
          returnType: 'Certificate',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listLbTypes',
          protoName: 'ListLbTypes',
          paramsType: 'ListLbTypesRequest',
          returnType: 'ListLbTypesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'LbType',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSubscriber',
          protoName: 'GetSubscriber',
          paramsType: 'GetSubscriberRequest',
          returnType: 'Subscriber',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSubscriber',
          protoName: 'ListSubscriber',
          paramsType: 'ListSubscriberRequest',
          returnType: 'ListSubscriberResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Subscriber',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listLbPrivateNetworks',
          protoName: 'ListLbPrivateNetworks',
          paramsType: 'ListLbPrivateNetworksRequest',
          returnType: 'ListLbPrivateNetworksResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'PrivateNetwork',
          listItemTypeNamespace: '@scaleway-internal/sdk-lb/v1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
