/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: '@scaleway/sdk-qaas',
  namespace: 'qaas',
  displayName: 'Qaas',
  versions: ['v1alpha1'],
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
