import { lowerCaseFirstLetter } from './helpers.ts'

type getContentProps = {
  name: string
  api: string
  packageName: string
  sdkFactoryPath: string
}

export const getFileContent = ({
  packageName,
  name,
  api,
  sdkFactoryPath,
}: getContentProps) => {
  const capitalizedName = name.charAt(0).toUpperCase() + name.slice(1)
  const apiName = capitalizedName + api
  const keyValue = name + api.replace('API', '')
  const template = [
    `import { ${capitalizedName} } from "${packageName}"`,
    `import { createSDKFactory } from "${sdkFactoryPath}"`,
    '',
    '// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased',
    `export const use${apiName} = createSDKFactory(`,
    `${capitalizedName}.${api},`,
    `'${lowerCaseFirstLetter(keyValue)}'`,
    ')',
  ].join('\n')

  return template.toString()
}
