import { lowerCaseFirstLetter } from './helpers.ts'

type getContentProps = {
  name: string
  api: string
  packageName: string
  sdkFactoryPath: string
}

export const getFileContent = ({
  packageName,
  name,
  api,
  sdkFactoryPath,
}: getContentProps) => {
  const apiName = name + api
  const keyValue = name + api.replace('API', '')
  const template = [
    `import { ${name} } from "${packageName}"`,
    `import { createSDKFactory } from "${sdkFactoryPath}"`,
    '',
    '// This file is generated by scripts placed in `packages/api/scripts/generate/` all modifications will be erased',
    `export const use${apiName} = createSDKFactory(`,
    `${name}.${api},`,
    `'${lowerCaseFirstLetter(keyValue)}'`,
    ')',
  ].join('\n')

  return template.toString()
}
