export { ap as UserConfigExport, ao as UserConfigFn, am as UserConfigFnObject, an as UserConfigFnPromise, ar as UserProjectConfigExport, aq as UserProjectConfigFn, z as UserWorkspaceConfig, aw as configDefaults, az as coverageConfigDefaults, av as defaultBrowserPort, ay as defaultExclude, ax as defaultInclude, as as defineConfig, at as defineProject, au as defineWorkspace, aA as extraInlineDeps } from './chunks/reporters.C_zwCd4j.js';
export { ConfigEnv, Plugin, UserConfig, mergeConfig } from 'vite';
import '@vitest/runner';
import '@vitest/pretty-format';
import './chunks/config.DCnyCTbs.js';
import '@vitest/snapshot';
import '@vitest/snapshot/environment';
import 'vite-node';
import './chunks/environment.0M5R1SX_.js';
import 'node:stream';
import 'vite-node/client';
import '@vitest/snapshot/manager';
import 'vite-node/server';
import '@vitest/utils';
import '@vitest/utils/source-map';
import 'node:fs';
import 'chai';
import './chunks/benchmark.puBFxyfE.js';
import '@vitest/runner/utils';
import 'tinybench';
