import { execSync } from 'node:child_process'
import { appendFileSync, copyFileSync, existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { cwd } from 'node:process'
import { fileURLToPath } from 'node:url'
import {
  renderTemplate,
  renderTemplatePackageJson,
  snakeToDisplayName,
  snakeToPascal,
  snakeToSlug,
} from '../helpers.ts'

const TEMPLATES_DIR = join(dirname(fileURLToPath(import.meta.url)), '../../templates')

const TEMPLATES = {
  PACKAGE_JSON: join(TEMPLATES_DIR, 'package.tmpl'),
  TS_CONFIG: join(TEMPLATES_DIR, 'tsconfig.json'),
  TS_CONFIG_BUILD: join(TEMPLATES_DIR, 'tsconfig.build.json'),
  VITE_CONFIG: join(TEMPLATES_DIR, 'vite.config.ts'),
  METADATA_TS: join(TEMPLATES_DIR, 'metadata.gen.ts.tmpl'),
}

const AUTO_GENERATE_MESSAGE = `/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */\n`

const CUSTOM = {
  PRODUCT_EXPORT: new Set(['std']),
  PRODUCT_VERSION_EXPORT: new Set(['', 'instance/v1', 'billing/v1', 'payment/v1', 'k8s/v1']),
}

export type PackagesOptions = { src: string; runInstall?: boolean }

/**
 * Generate per-product configuration files from templates.
 *
 * For each directory under `src` (excluding `std`):
 * - Creates `package.json` if missing (from `templates/package.tmpl`)
 * - Generates `src/index.gen.ts` re-exporting all version directories as namespaces
 * - Generates `src/metadata.gen.ts` with product name, display name, and version list
 * - Copies `tsconfig.json`, `tsconfig.build.json`, and `vite.config.ts` from templates
 *
 * @param options.src - Absolute path to the generated packages directory
 * @param options.runInstall - Run `pnpm install` + `manypkg fix` after generation (default: true)
 */
export const packages = async ({ src: inputPathDir, runInstall = true }: PackagesOptions): Promise<void> => {
  const templateString = readFileSync(TEMPLATES.PACKAGE_JSON, 'utf8')
  const metadataTsTemplateString = readFileSync(TEMPLATES.METADATA_TS, 'utf8')

  for (const productDir of readdirSync(inputPathDir)) {
    const fullPath = join(inputPathDir, productDir)
    if (!statSync(fullPath).isDirectory() || CUSTOM.PRODUCT_EXPORT.has(productDir)) continue

    const packageJsonPath = join(fullPath, 'package.json')
    if (!existsSync(packageJsonPath)) {
      const pkg = renderTemplatePackageJson(templateString, { name: snakeToSlug(productDir) })
      writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2))
    }

    const srcPath = join(fullPath, 'src')
    const indexGenPath = join(srcPath, 'index.gen.ts')
    writeFileSync(indexGenPath, AUTO_GENERATE_MESSAGE)
    for (const versionDir of readdirSync(srcPath)) {
      if (statSync(join(srcPath, versionDir)).isDirectory()) {
        const exportPath = CUSTOM.PRODUCT_VERSION_EXPORT.has(`${productDir}/${versionDir}`)
          ? `./${versionDir}/index.js`
          : `./${versionDir}/index.gen.js`
        appendFileSync(indexGenPath, `\nexport * as ${snakeToPascal(productDir)}${versionDir} from '${exportPath}'`)
      }
    }

    const versionsList = readdirSync(srcPath)
      .filter(d => statSync(join(srcPath, d)).isDirectory())
      .map(v => `"${v}"`)
      .join(', ')
    writeFileSync(
      join(srcPath, 'metadata.gen.ts'),
      renderTemplate(metadataTsTemplateString, {
        name: snakeToSlug(productDir),
        displayName: snakeToDisplayName(productDir),
        versions: versionsList,
      }),
    )

    copyFileSync(TEMPLATES.TS_CONFIG, join(fullPath, 'tsconfig.json'))
    copyFileSync(TEMPLATES.TS_CONFIG_BUILD, join(fullPath, 'tsconfig.build.json'))
    copyFileSync(TEMPLATES.VITE_CONFIG, join(fullPath, 'vite.config.ts'))
  }

  if (runInstall) {
    console.log('📦 Updating pnpm-lock.yaml...')
    execSync('pnpm install --no-frozen-lockfile', { stdio: 'inherit', cwd: cwd() })
    execSync('pnpm exec manypkg fix', { stdio: 'inherit', cwd: cwd() })
    console.log('✅ Done')
  }
}
