#!/usr/bin/env node
import {
  access,
  appendFileSync,
  constants,
  copyFileSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { cwd, exit } from 'node:process'
import { fileURLToPath } from 'node:url'
import type { ParseArgsConfig } from 'node:util'
import { parseArgs } from 'node:util'
import { SDKS } from './constants.ts'
import {
  renderTemplate,
  renderTemplatePackageJson,
  snakeToDisplayName,
  snakeToPascal,
  snakeToSlug,
} from './helpers.ts'

/**
 * Generates package scaffolding for each product in packages_generated/:
 * - package.json (from template, only if missing)
 * - tsconfig.json, tsconfig.build.json, vite.config.ts (always overwritten)
 * - README.md (from template, only if missing)
 * - src/index.gen.ts (version re-exports)
 */

const TEMPLATES_DIR = join(
  dirname(fileURLToPath(import.meta.url)),
  '../templates',
)

const TEMPLATES = {
  PACKAGE_JSON: join(TEMPLATES_DIR, 'package.tmpl'),
  TS_CONFIG: join(TEMPLATES_DIR, 'tsconfig.json'),
  TS_CONFIG_BUILD: join(TEMPLATES_DIR, 'tsconfig.build.json'),
  VITE_CONFIG: join(TEMPLATES_DIR, 'vite.config.ts'),
  README: join(TEMPLATES_DIR, 'README.tmpl'),
}

const templateString = readFileSync(TEMPLATES.PACKAGE_JSON, 'utf8')
const readmeTemplateString = readFileSync(TEMPLATES.README, 'utf8')

const options: ParseArgsConfig['options'] = {
  src: {
    type: 'string',
    short: 's',
    default: 'packages_generated',
  },
}

const SOURCE_DIR = 'src'
const DEFAULT_GENERATED_EXPORT_PATH = 'index.gen.ts'

const CUSTOM = {
  PRODUCT_EXPORT: new Set(['std']),
  PRODUCT_VERSION_EXPORT: new Set(['', 'instance/v1', 'k8s/v1']),
}

const AUTO_GENERATE_MESSAGE = `/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */\n`

const { values } = parseArgs({ options, allowPositionals: true })

if (!values.src) {
  console.error('Missing required argument: --src')
  exit(1)
}

const INPUT_PATH_DIR = resolve(cwd(), values.src as string)

const exportProductVersions = ({ productDir }: { productDir: string }) => {
  const fullPath = join(INPUT_PATH_DIR, productDir, SOURCE_DIR)
  const versionDirs = readdirSync(fullPath)
  const pathFile = `${fullPath}/${DEFAULT_GENERATED_EXPORT_PATH}`

  writeFileSync(pathFile, AUTO_GENERATE_MESSAGE)

  for (const versionDir of versionDirs) {
    const pathVersion = `${fullPath}/${versionDir}`
    if (statSync(pathVersion).isDirectory()) {
      const exportPath = CUSTOM.PRODUCT_VERSION_EXPORT.has(
        `${productDir}/${versionDir}`,
      )
        ? `./${versionDir}/index.js`
        : `./${versionDir}/index.gen.js`

      appendFileSync(
        pathFile,
        `\nexport * as ${snakeToPascal(productDir)}${versionDir} from '${exportPath}'`,
      )
    }
  }
  appendFileSync(pathFile, '\n')
}

const main = () => {
  for (const _sdk of SDKS) {
    const productsDirs = readdirSync(INPUT_PATH_DIR)

    for (const productDir of productsDirs) {
      const fullPath = join(INPUT_PATH_DIR, productDir)
      if (statSync(fullPath).isDirectory()) {
        if (!CUSTOM.PRODUCT_EXPORT.has(productDir)) {
          const fileName = 'package.json'
          const filePath = join(fullPath, fileName)
          access(filePath, constants.F_OK, err => {
            if (err) {
              const pkg = renderTemplatePackageJson(templateString, {
                name: snakeToSlug(productDir),
              })
              writeFileSync(filePath, JSON.stringify(pkg, null, 2))
            }
          })

          exportProductVersions({ productDir })
          copyFileSync(TEMPLATES.TS_CONFIG, join(fullPath, 'tsconfig.json'))
          copyFileSync(
            TEMPLATES.TS_CONFIG_BUILD,
            join(fullPath, 'tsconfig.build.json'),
          )
          copyFileSync(TEMPLATES.VITE_CONFIG, join(fullPath, 'vite.config.ts'))

          const readmeFilePath = join(fullPath, 'README.md')
          access(readmeFilePath, constants.F_OK, err => {
            if (err) {
              const readme = renderTemplate(readmeTemplateString, {
                name: snakeToSlug(productDir),
                displayName: snakeToDisplayName(productDir),
                pascalName: snakeToPascal(productDir),
              })
              writeFileSync(readmeFilePath, readme)
              console.log(`Generated README.md for ${productDir}`)
            }
          })
        }
      }
    }
  }
}

main()
