// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'redis',
  version: 'v1',
  folderName: 'redisv1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'getCluster',
          protoName: 'GetCluster',
          paramsType: 'GetClusterRequest',
          returnType: 'Cluster',
          returnTypeNamespace: '@scaleway-internal/sdk-redis/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listClusters',
          protoName: 'ListClusters',
          paramsType: 'ListClustersRequest',
          returnType: 'ListClustersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-redis/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Cluster',
          listItemTypeNamespace: '@scaleway-internal/sdk-redis/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getClusterMetrics',
          protoName: 'GetClusterMetrics',
          paramsType: 'GetClusterMetricsRequest',
          returnType: 'ClusterMetricsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-redis/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listNodeTypes',
          protoName: 'ListNodeTypes',
          paramsType: 'ListNodeTypesRequest',
          returnType: 'ListNodeTypesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-redis/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'NodeType',
          listItemTypeNamespace: '@scaleway-internal/sdk-redis/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listClusterVersions',
          protoName: 'ListClusterVersions',
          paramsType: 'ListClusterVersionsRequest',
          returnType: 'ListClusterVersionsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-redis/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ClusterVersion',
          listItemTypeNamespace: '@scaleway-internal/sdk-redis/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getClusterCertificate',
          protoName: 'GetClusterCertificate',
          paramsType: 'GetClusterCertificateRequest',
          returnType: 'Blob',
          returnTypeNamespace: '@scaleway-internal/sdk-redis/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getAclRule',
          protoName: 'GetAclRule',
          paramsType: 'GetAclRuleRequest',
          returnType: 'ACLRule',
          returnTypeNamespace: '@scaleway-internal/sdk-redis/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getEndpoint',
          protoName: 'GetEndpoint',
          paramsType: 'GetEndpointRequest',
          returnType: 'Endpoint',
          returnTypeNamespace: '@scaleway-internal/sdk-redis/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
