/**
 * This file is automatically generated from /scripts/generate.js
 * PLEASE DO NOT EDIT HERE
 */

import * as Account from './account/index.gen'
import * as Applesilicon from './applesilicon/index.gen'
import * as AuditTrail from './audit_trail/index.gen'
import * as Baremetal from './baremetal/index.gen'
import * as Billing from './billing/index.gen'
import * as Block from './block/index.gen'
import * as Cockpit from './cockpit/index.gen'
import * as Container from './container/index.gen'
import * as Dedibox from './dedibox/index.gen'
import * as DocumentDb from './document_db/index.gen'
import * as Domain from './domain/index.gen'
import * as EdgeServices from './edge_services/index.gen'
import * as File from './file/index.gen'
import * as Flexibleip from './flexibleip/index.gen'
import * as Function from './function/index.gen'
import * as Iam from './iam/index.gen'
import * as Inference from './inference/index.gen'
import * as Instance from './instance/index.gen'
import * as Interlink from './interlink/index.gen'
import * as Iot from './iot/index.gen'
import * as Ipam from './ipam/index.gen'
import * as Ipfs from './ipfs/index.gen'
import * as Jobs from './jobs/index.gen'
import * as K8s from './k8s/index.gen'
import * as KeyManager from './key_manager/index.gen'
import * as Lb from './lb/index.gen'
import * as LlmInference from './llm_inference/index.gen'
import * as Marketplace from './marketplace/index.gen'
import * as Mnq from './mnq/index.gen'
import * as Mongodb from './mongodb/index.gen'
import * as ProductCatalog from './product_catalog/index.gen'
import * as Qaas from './qaas/index.gen'
import * as Rdb from './rdb/index.gen'
import * as Redis from './redis/index.gen'
import * as Registry from './registry/index.gen'
import * as Secret from './secret/index.gen'
import * as ServerlessSqldb from './serverless_sqldb/index.gen'
import * as Std from './std/index.gen'
import * as Tem from './tem/index.gen'
import * as Test from './test/index.gen'
import * as Vpc from './vpc/index.gen'
import * as Vpcgw from './vpcgw/index.gen'
import * as Webhosting from './webhosting/index.gen'

export {
  Account,
  Applesilicon,
  AuditTrail,
  Baremetal,
  Billing,
  Block,
  Cockpit,
  Container,
  Dedibox,
  DocumentDb,
  Domain,
  EdgeServices,
  File,
  Flexibleip,
  Function,
  Iam,
  Inference,
  Instance,
  Interlink,
  Iot,
  Ipam,
  Ipfs,
  Jobs,
  K8s,
  KeyManager,
  Lb,
  LlmInference,
  Marketplace,
  Mnq,
  Mongodb,
  ProductCatalog,
  Qaas,
  Rdb,
  Redis,
  Registry,
  Secret,
  ServerlessSqldb,
  Std,
  Tem,
  Test,
  Vpc,
  Vpcgw,
  Webhosting,
}
