// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'instance',
  version: 'v2alpha1',
  folderName: 'instancev2alpha1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'getResourceCounts',
          protoName: 'GetResourceCounts',
          paramsType: 'GetResourceCountsRequest',
          returnType: 'ResourceCounts',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listServers',
          protoName: 'ListServers',
          paramsType: 'ListServersRequest',
          returnType: 'ListServersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: true,
          paginationType: 'cursor',
          pageParamKey: 'pageToken',
          listItemType: 'ServerSummary',
          listItemTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          nextPageField: 'nextPageToken',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getServer',
          protoName: 'GetServer',
          paramsType: 'GetServerRequest',
          returnType: 'Server',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listServerTypes',
          protoName: 'ListServerTypes',
          paramsType: 'ListServerTypesRequest',
          returnType: 'ListServerTypesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: true,
          paginationType: 'cursor',
          pageParamKey: 'pageToken',
          listItemType: 'ServerType',
          listItemTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          nextPageField: 'nextPageToken',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listPrivateNetworkInterfaces',
          protoName: 'ListPrivateNetworkInterfaces',
          paramsType: 'ListPrivateNetworkInterfacesRequest',
          returnType: 'ListPrivateNetworkInterfacesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: true,
          paginationType: 'cursor',
          pageParamKey: 'pageToken',
          listItemType: 'PrivateNetworkInterfaceSummary',
          listItemTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          nextPageField: 'nextPageToken',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getPrivateNetworkInterface',
          protoName: 'GetPrivateNetworkInterface',
          paramsType: 'GetPrivateNetworkInterfaceRequest',
          returnType: 'PrivateNetworkInterface',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listPlacementGroups',
          protoName: 'ListPlacementGroups',
          paramsType: 'ListPlacementGroupsRequest',
          returnType: 'ListPlacementGroupsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: true,
          paginationType: 'cursor',
          pageParamKey: 'pageToken',
          listItemType: 'PlacementGroup',
          listItemTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          nextPageField: 'nextPageToken',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getPlacementGroup',
          protoName: 'GetPlacementGroup',
          paramsType: 'GetPlacementGroupRequest',
          returnType: 'PlacementGroup',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSecurityGroups',
          protoName: 'ListSecurityGroups',
          paramsType: 'ListSecurityGroupsRequest',
          returnType: 'ListSecurityGroupsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: true,
          paginationType: 'cursor',
          pageParamKey: 'pageToken',
          listItemType: 'SecurityGroupSummary',
          listItemTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          nextPageField: 'nextPageToken',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSecurityGroup',
          protoName: 'GetSecurityGroup',
          paramsType: 'GetSecurityGroupRequest',
          returnType: 'SecurityGroup',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listUserDataKeys',
          protoName: 'ListUserDataKeys',
          paramsType: 'ListUserDataKeysRequest',
          returnType: 'ListUserDataKeysResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: true,
          paginationType: 'cursor',
          pageParamKey: 'pageToken',
          listItemType: 'string',
          listItemTypeNamespace: 'string',
          nextPageField: 'nextPageToken',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getUserData',
          protoName: 'GetUserData',
          paramsType: 'GetUserDataRequest',
          returnType: 'UserData',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getServerCloudInit',
          protoName: 'GetServerCloudInit',
          paramsType: 'GetServerCloudInitRequest',
          returnType: 'UserData',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listTemplates',
          protoName: 'ListTemplates',
          paramsType: 'ListTemplatesRequest',
          returnType: 'ListTemplatesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: true,
          paginationType: 'cursor',
          pageParamKey: 'pageToken',
          listItemType: 'TemplateSummary',
          listItemTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          nextPageField: 'nextPageToken',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getTemplate',
          protoName: 'GetTemplate',
          paramsType: 'GetTemplateRequest',
          returnType: 'Template',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listTemplateUserDataKeys',
          protoName: 'ListTemplateUserDataKeys',
          paramsType: 'ListTemplateUserDataKeysRequest',
          returnType: 'ListTemplateUserDataKeysResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: true,
          paginationType: 'cursor',
          pageParamKey: 'pageToken',
          listItemType: 'string',
          listItemTypeNamespace: 'string',
          nextPageField: 'nextPageToken',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getTemplateUserData',
          protoName: 'GetTemplateUserData',
          paramsType: 'GetTemplateUserDataRequest',
          returnType: 'UserData',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getTemplateCloudInit',
          protoName: 'GetTemplateCloudInit',
          paramsType: 'GetTemplateCloudInitRequest',
          returnType: 'UserData',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'VolumeAPI',
      methods: [
        {
          methodName: 'listVolumeTypes',
          protoName: 'ListVolumeTypes',
          paramsType: 'VolumeApiListVolumeTypesRequest',
          returnType: 'ListVolumeTypesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: true,
          paginationType: 'cursor',
          pageParamKey: 'pageToken',
          listItemType: 'VolumeType',
          listItemTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          nextPageField: 'nextPageToken',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listVolumes',
          protoName: 'ListVolumes',
          paramsType: 'VolumeApiListVolumesRequest',
          returnType: 'ListVolumesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: true,
          paginationType: 'cursor',
          pageParamKey: 'pageToken',
          listItemType: 'Volume',
          listItemTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          nextPageField: 'nextPageToken',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getVolume',
          protoName: 'GetVolume',
          paramsType: 'VolumeApiGetVolumeRequest',
          returnType: 'Volume',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listSnapshots',
          protoName: 'ListSnapshots',
          paramsType: 'VolumeApiListSnapshotsRequest',
          returnType: 'ListSnapshotsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: true,
          paginationType: 'cursor',
          pageParamKey: 'pageToken',
          listItemType: 'Snapshot',
          listItemTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          nextPageField: 'nextPageToken',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSnapshot',
          protoName: 'GetSnapshot',
          paramsType: 'VolumeApiGetSnapshotRequest',
          returnType: 'Snapshot',
          returnTypeNamespace: '@scaleway-internal/sdk-instance/v2alpha1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
