import { Annotationsv1 } from "@scaleway/sdk-annotations"
import { createSDKFactory } from "../../contexts/SDKCacheProvider/sdkFactory"

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useAnnotationsv1API = createSDKFactory(
   Annotationsv1.API,
   'annotationsv1'
)