import { Applesiliconv1alpha1 } from '@scaleway/sdk-applesilicon'
import { createSDKFactory } from '../../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useApplesiliconv1alpha1PrivateNetworkAPI = createSDKFactory(
  Applesiliconv1alpha1.PrivateNetworkAPI,
  'applesiliconv1alpha1PrivateNetwork',
)
