import { Autoscalingv1alpha2 } from "@scaleway/sdk-autoscaling"
import { createSDKFactory } from "../../contexts/SDKCacheProvider/sdkFactory"

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useAutoscalingv1alpha2API = createSDKFactory(
   Autoscalingv1alpha2.API,
   'autoscalingv1alpha2'
)