import { Baremetalv1 } from "@scaleway/sdk-baremetal"
import { createSDKFactory } from "../../contexts/SDKCacheProvider/sdkFactory"

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useBaremetalv1PrivateNetworkAPI = createSDKFactory(
   Baremetalv1.PrivateNetworkAPI,
   'baremetalv1PrivateNetwork'
)