import { Billingv2 } from "@scaleway/sdk-billing"
import { createSDKFactory } from "../../contexts/SDKCacheProvider/sdkFactory"

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useBillingv2ElectronicBillingAPI = createSDKFactory(
   Billingv2.ElectronicBillingAPI,
   'billingv2ElectronicBilling'
)