import { Billingv2beta1 } from "@scaleway/sdk-billing"
import { createSDKFactory } from "../../contexts/SDKCacheProvider/sdkFactory"

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useBillingv2beta1FinOpsAPI = createSDKFactory(
   Billingv2beta1.FinOpsAPI,
   'billingv2beta1FinOps'
)