import { Billingv2 } from "@scaleway/sdk-billing"
import { createSDKFactory } from "../../contexts/SDKCacheProvider/sdkFactory"

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useBillingv2API = createSDKFactory(
   Billingv2.API,
   'billingv2'
)