import { Blockv1alpha1 } from '@scaleway/sdk-block'
import { createSDKFactory } from '../../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useBlockv1alpha1API = createSDKFactory(
  Blockv1alpha1.API,
  'blockv1alpha1',
)
