import { Blockv1 } from '@scaleway/sdk-block'
import { createSDKFactory } from '../../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useBlockv1API = createSDKFactory(Blockv1.API, 'blockv1')
