import { Cockpitv1 } from "@scaleway/sdk-cockpit"
import { createSDKFactory } from "../../contexts/SDKCacheProvider/sdkFactory"

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useCockpitv1RegionalAPI = createSDKFactory(
   Cockpitv1.RegionalAPI,
   'cockpitv1Regional'
)