import { Containerv1 } from "@scaleway/sdk-container"
import { createSDKFactory } from "../../contexts/SDKCacheProvider/sdkFactory"

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useContainerv1API = createSDKFactory(
   Containerv1.API,
   'containerv1'
)