import { Datalabv1beta1 } from '@scaleway/sdk-datalab'
import { createSDKFactory } from '../../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useDatalabv1beta1API = createSDKFactory(
  Datalabv1beta1.API,
  'datalabv1beta1',
)
