import { Datawarehousev1beta1 } from "@scaleway/sdk-datawarehouse"
import { createSDKFactory } from "../../contexts/SDKCacheProvider/sdkFactory"

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useDatawarehousev1beta1API = createSDKFactory(
   Datawarehousev1beta1.API,
   'datawarehousev1beta1'
)