import { Domainv2beta1 } from "@scaleway/sdk-domain"
import { createSDKFactory } from "../../contexts/SDKCacheProvider/sdkFactory"

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useDomainv2beta1RegistrarAPI = createSDKFactory(
   Domainv2beta1.RegistrarAPI,
   'domainv2beta1Registrar'
)