import { EnvironmentalFootprintv1alpha1 } from '@scaleway/sdk-environmental-footprint'
import { createSDKFactory } from '../../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useEnvironmentalFootprintv1alpha1UserAPI = createSDKFactory(
  EnvironmentalFootprintv1alpha1.UserAPI,
  'environmentalFootprintv1alpha1User',
)
