import { Inferencev1 } from "@scaleway/sdk-inference"
import { createSDKFactory } from "../../contexts/SDKCacheProvider/sdkFactory"

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useInferencev1API = createSDKFactory(
   Inferencev1.API,
   'inferencev1'
)