import { Inferencev1beta1 } from '@scaleway/sdk-inference'
import { createSDKFactory } from '../../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useInferencev1beta1API = createSDKFactory(
  Inferencev1beta1.API,
  'inferencev1beta1',
)
