import { Instancev2alpha1 } from "@scaleway/sdk-instance"
import { createSDKFactory } from "../../contexts/SDKCacheProvider/sdkFactory"

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useInstancev2alpha1API = createSDKFactory(
   Instancev2alpha1.API,
   'instancev2alpha1'
)