import { Interlinkv1beta1 } from '@scaleway/sdk-interlink'
import { createSDKFactory } from '../../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useInterlinkv1beta1API = createSDKFactory(
  Interlinkv1beta1.API,
  'interlinkv1beta1',
)
