import { Iotv1 } from "@scaleway/sdk-iot"
import { createSDKFactory } from "../../contexts/SDKCacheProvider/sdkFactory"

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useIotv1API = createSDKFactory(
   Iotv1.API,
   'iotv1'
)