import { Ipamv1 } from '@scaleway/sdk-ipam'
import { createSDKFactory } from '../../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useIpamv1API = createSDKFactory(Ipamv1.API, 'ipamv1')
