import { Jobsv1alpha1 } from "@scaleway/sdk-jobs"
import { createSDKFactory } from "../../contexts/SDKCacheProvider/sdkFactory"

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useJobsv1alpha1API = createSDKFactory(
   Jobsv1alpha1.API,
   'jobsv1alpha1'
)