import { K8Sv1 } from "@scaleway/sdk-k8s"
import { createSDKFactory } from "../../contexts/SDKCacheProvider/sdkFactory"

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useK8Sv1API = createSDKFactory(
   K8Sv1.API,
   'k8Sv1'
)