import { Kafkav1alpha1 } from "@scaleway/sdk-kafka"
import { createSDKFactory } from "../../contexts/SDKCacheProvider/sdkFactory"

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useKafkav1alpha1API = createSDKFactory(
   Kafkav1alpha1.API,
   'kafkav1alpha1'
)