import { KeyManagerv1alpha1 } from '@scaleway/sdk-key-manager'
import { createSDKFactory } from '../../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useKeyManagerv1alpha1API = createSDKFactory(
  KeyManagerv1alpha1.API,
  'keyManagerv1alpha1',
)
