import { Lbv1 } from '@scaleway/sdk-lb'
import { createSDKFactory } from '../../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useLbv1API = createSDKFactory(Lbv1.API, 'lbv1')
