import { Mailboxv1alpha1 } from '@scaleway/sdk-mailbox'
import { createSDKFactory } from '../../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useMailboxv1alpha1API = createSDKFactory(
  Mailboxv1alpha1.API,
  'mailboxv1alpha1',
)
