import { Qaasv1alpha1 } from '@scaleway/sdk-qaas'
import { createSDKFactory } from '../../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useQaasv1alpha1API = createSDKFactory(
  Qaasv1alpha1.API,
  'qaasv1alpha1',
)
