import { Registryv1 } from '@scaleway/sdk-registry'
import { createSDKFactory } from '../../contexts/SDKCacheProvider/sdkFactory'

// This file is generated by scripts placed in `@scaleway/sdk:tools/generate-react-sdk` all modifications will be erased
export const useRegistryv1API = createSDKFactory(Registryv1.API, 'registryv1')
