// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'autoscaling',
  version: 'v1alpha1',
  folderName: 'autoscalingv1alpha1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'getInstanceGroup',
          protoName: 'GetInstanceGroup',
          paramsType: 'GetInstanceGroupRequest',
          returnType: 'InstanceGroup',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listInstanceGroups',
          protoName: 'ListInstanceGroups',
          paramsType: 'ListInstanceGroupsRequest',
          returnType: 'ListInstanceGroupsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'InstanceGroup',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getInstanceTemplate',
          protoName: 'GetInstanceTemplate',
          paramsType: 'GetInstanceTemplateRequest',
          returnType: 'InstanceTemplate',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listInstanceTemplates',
          protoName: 'ListInstanceTemplates',
          paramsType: 'ListInstanceTemplatesRequest',
          returnType: 'ListInstanceTemplatesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'InstanceTemplate',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listInstancePolicies',
          protoName: 'ListInstancePolicies',
          paramsType: 'ListInstancePoliciesRequest',
          returnType: 'ListInstancePoliciesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'InstancePolicy',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getInstancePolicy',
          protoName: 'GetInstancePolicy',
          paramsType: 'GetInstancePolicyRequest',
          returnType: 'InstancePolicy',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listInstanceGroupEvents',
          protoName: 'ListInstanceGroupEvents',
          paramsType: 'ListInstanceGroupEventsRequest',
          returnType: 'ListInstanceGroupEventsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'InstanceGroupEvent',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
