// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.
export { API } from './api.gen'
export * from './content.gen'
export type {
  ConnectivityDiagnostic,
  ConnectivityDiagnosticActionType,
  ConnectivityDiagnosticDiagnosticStatus,
  ConnectivityDiagnosticServerHealth,
  CreateServerRequest,
  DeleteServerRequest,
  GetConnectivityDiagnosticRequest,
  GetOSRequest,
  GetServerRequest,
  GetServerTypeRequest,
  ListOSRequest,
  ListOSResponse,
  ListServerTypesRequest,
  ListServerTypesResponse,
  ListServersRequest,
  ListServersRequestOrderBy,
  ListServersResponse,
  OS,
  RebootServerRequest,
  ReinstallServerRequest,
  Server,
  ServerPrivateNetworkStatus,
  ServerStatus,
  ServerType,
  ServerTypeCPU,
  ServerTypeDisk,
  ServerTypeGPU,
  ServerTypeMemory,
  ServerTypeNetwork,
  ServerTypeStock,
  StartConnectivityDiagnosticRequest,
  StartConnectivityDiagnosticResponse,
  UpdateServerRequest,
} from './types.gen'
