/**
 * This file is automatically generated
 * PLEASE DO NOT EDIT HERE
 */

export const pkgMetadata = {
  name: '@scaleway/sdk-edge-services',
  namespace: 'edge-services',
  displayName: 'Edge Services',
  versions: ['v1beta1'],
} as const

export type Metadata = typeof pkgMetadata

export default pkgMetadata
