// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.
export { API } from './api.gen'
export type {
  AttachRoutingPolicyRequest,
  AttachVpcRequest,
  BgpStatus,
  CreateLinkRequest,
  CreateRoutingPolicyRequest,
  DeleteLinkRequest,
  DeleteRoutingPolicyRequest,
  DetachRoutingPolicyRequest,
  DetachVpcRequest,
  DisableRoutePropagationRequest,
  EnableRoutePropagationRequest,
  GetLinkRequest,
  GetPartnerRequest,
  GetPopRequest,
  GetRoutingPolicyRequest,
  Link,
  LinkStatus,
  ListLinksRequest,
  ListLinksRequestOrderBy,
  ListLinksResponse,
  ListPartnersRequest,
  ListPartnersRequestOrderBy,
  ListPartnersResponse,
  ListPopsRequest,
  ListPopsRequestOrderBy,
  ListPopsResponse,
  ListRoutingPoliciesRequest,
  ListRoutingPoliciesRequestOrderBy,
  ListRoutingPoliciesResponse,
  Partner,
  Pop,
  RoutingPolicy,
  UpdateLinkRequest,
  UpdateRoutingPolicyRequest,
} from './types.gen'
export * as ValidationRules from './validation-rules.gen'
