// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'interlink',
  version: 'v1beta1',
  folderName: 'interlinkv1beta1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listDedicatedConnections',
          protoName: 'ListDedicatedConnections',
          paramsType: 'ListDedicatedConnectionsRequest',
          returnType: 'ListDedicatedConnectionsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-interlink/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'DedicatedConnection',
          listItemTypeNamespace: '@scaleway-internal/sdk-interlink/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDedicatedConnection',
          protoName: 'GetDedicatedConnection',
          paramsType: 'GetDedicatedConnectionRequest',
          returnType: 'DedicatedConnection',
          returnTypeNamespace: '@scaleway-internal/sdk-interlink/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listPartners',
          protoName: 'ListPartners',
          paramsType: 'ListPartnersRequest',
          returnType: 'ListPartnersResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-interlink/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Partner',
          listItemTypeNamespace: '@scaleway-internal/sdk-interlink/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getPartner',
          protoName: 'GetPartner',
          paramsType: 'GetPartnerRequest',
          returnType: 'Partner',
          returnTypeNamespace: '@scaleway-internal/sdk-interlink/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listPops',
          protoName: 'ListPops',
          paramsType: 'ListPopsRequest',
          returnType: 'ListPopsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-interlink/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Pop',
          listItemTypeNamespace: '@scaleway-internal/sdk-interlink/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getPop',
          protoName: 'GetPop',
          paramsType: 'GetPopRequest',
          returnType: 'Pop',
          returnTypeNamespace: '@scaleway-internal/sdk-interlink/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listLinks',
          protoName: 'ListLinks',
          paramsType: 'ListLinksRequest',
          returnType: 'ListLinksResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-interlink/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Link',
          listItemTypeNamespace: '@scaleway-internal/sdk-interlink/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getLink',
          protoName: 'GetLink',
          paramsType: 'GetLinkRequest',
          returnType: 'Link',
          returnTypeNamespace: '@scaleway-internal/sdk-interlink/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listRoutingPolicies',
          protoName: 'ListRoutingPolicies',
          paramsType: 'ListRoutingPoliciesRequest',
          returnType: 'ListRoutingPoliciesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-interlink/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'RoutingPolicy',
          listItemTypeNamespace: '@scaleway-internal/sdk-interlink/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRoutingPolicy',
          protoName: 'GetRoutingPolicy',
          paramsType: 'GetRoutingPolicyRequest',
          returnType: 'RoutingPolicy',
          returnTypeNamespace: '@scaleway-internal/sdk-interlink/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
