// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'baremetal',
  version: 'v1',
  folderName: 'baremetalv1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listServers',
          protoName: 'ListServers',
          paramsType: 'ListServersRequest',
          returnType: 'ListServersResponse',
          returnTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Server',
          listItemTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getServer',
          protoName: 'GetServer',
          paramsType: 'GetServerRequest',
          returnType: 'Server',
          returnTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'getServerMetrics',
          protoName: 'GetServerMetrics',
          paramsType: 'GetServerMetricsRequest',
          returnType: 'GetServerMetricsResponse',
          returnTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listServerEvents',
          protoName: 'ListServerEvents',
          paramsType: 'ListServerEventsRequest',
          returnType: 'ListServerEventsResponse',
          returnTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ServerEvent',
          listItemTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getDefaultPartitioningSchema',
          protoName: 'GetDefaultPartitioningSchema',
          paramsType: 'GetDefaultPartitioningSchemaRequest',
          returnType: 'Schema',
          returnTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getBMCAccess',
          protoName: 'GetBMCAccess',
          paramsType: 'GetBMCAccessRequest',
          returnType: 'BMCAccess',
          returnTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listOffers',
          protoName: 'ListOffers',
          paramsType: 'ListOffersRequest',
          returnType: 'ListOffersResponse',
          returnTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Offer',
          listItemTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getOffer',
          protoName: 'GetOffer',
          paramsType: 'GetOfferRequest',
          returnType: 'Offer',
          returnTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getOption',
          protoName: 'GetOption',
          paramsType: 'GetOptionRequest',
          returnType: 'Option',
          returnTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listOptions',
          protoName: 'ListOptions',
          paramsType: 'ListOptionsRequest',
          returnType: 'ListOptionsResponse',
          returnTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Option',
          listItemTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSettings',
          protoName: 'ListSettings',
          paramsType: 'ListSettingsRequest',
          returnType: 'ListSettingsResponse',
          returnTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Setting',
          listItemTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listOS',
          protoName: 'ListOS',
          paramsType: 'ListOSRequest',
          returnType: 'ListOSResponse',
          returnTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'OS',
          listItemTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getOS',
          protoName: 'GetOS',
          paramsType: 'GetOSRequest',
          returnType: 'OS',
          returnTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
    {
      apiClass: 'PrivateNetworkAPI',
      methods: [
        {
          methodName: 'listServerPrivateNetworks',
          protoName: 'ListServerPrivateNetworks',
          paramsType: 'PrivateNetworkApiListServerPrivateNetworksRequest',
          returnType: 'ListServerPrivateNetworksResponse',
          returnTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'ServerPrivateNetwork',
          listItemTypeNamespace: '@scaleway/sdk-baremetal/v1',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
