// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'jobs',
  version: 'v1alpha1',
  folderName: 'jobsv1alpha1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'getJobDefinition',
          protoName: 'GetJobDefinition',
          paramsType: 'GetJobDefinitionRequest',
          returnType: 'JobDefinition',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listJobDefinitions',
          protoName: 'ListJobDefinitions',
          paramsType: 'ListJobDefinitionsRequest',
          returnType: 'ListJobDefinitionsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'JobDefinition',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getJobDefinitionSecret',
          protoName: 'GetJobDefinitionSecret',
          paramsType: 'GetJobDefinitionSecretRequest',
          returnType: 'Secret',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listJobDefinitionSecrets',
          protoName: 'ListJobDefinitionSecrets',
          paramsType: 'ListJobDefinitionSecretsRequest',
          returnType: 'ListJobDefinitionSecretsResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getJobRun',
          protoName: 'GetJobRun',
          paramsType: 'GetJobRunRequest',
          returnType: 'JobRun',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listJobRuns',
          protoName: 'ListJobRuns',
          paramsType: 'ListJobRunsRequest',
          returnType: 'ListJobRunsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'JobRun',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listJobsResources',
          protoName: 'ListJobsResources',
          paramsType: 'ListJobsResourcesRequest',
          returnType: 'ListJobsResourcesResponse',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getJobsLimits',
          protoName: 'GetJobsLimits',
          paramsType: 'GetJobsLimitsRequest',
          returnType: 'JobsLimits',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
