// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 's2s_vpn',
  version: 'v1alpha1',
  folderName: 's2SVpnv1alpha1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'listVpnGatewayTypes',
          protoName: 'ListVpnGatewayTypes',
          paramsType: 'ListVpnGatewayTypesRequest',
          returnType: 'ListVpnGatewayTypesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'GatewayType',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listVpnGateways',
          protoName: 'ListVpnGateways',
          paramsType: 'ListVpnGatewaysRequest',
          returnType: 'ListVpnGatewaysResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'VpnGateway',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getVpnGateway',
          protoName: 'GetVpnGateway',
          paramsType: 'GetVpnGatewayRequest',
          returnType: 'VpnGateway',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
          hasWaiter: true,
        },
        {
          methodName: 'listConnections',
          protoName: 'ListConnections',
          paramsType: 'ListConnectionsRequest',
          returnType: 'ListConnectionsResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Connection',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getConnection',
          protoName: 'GetConnection',
          paramsType: 'GetConnectionRequest',
          returnType: 'Connection',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listCustomerGateways',
          protoName: 'ListCustomerGateways',
          paramsType: 'ListCustomerGatewaysRequest',
          returnType: 'ListCustomerGatewaysResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'CustomerGateway',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getCustomerGateway',
          protoName: 'GetCustomerGateway',
          paramsType: 'GetCustomerGatewayRequest',
          returnType: 'CustomerGateway',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listRoutingPolicies',
          protoName: 'ListRoutingPolicies',
          paramsType: 'ListRoutingPoliciesRequest',
          returnType: 'ListRoutingPoliciesResponse',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'RoutingPolicy',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getRoutingPolicy',
          protoName: 'GetRoutingPolicy',
          paramsType: 'GetRoutingPolicyRequest',
          returnType: 'RoutingPolicy',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
