// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

export const queriesMetadata = {
  namespace: 'secret',
  version: 'v1beta1',
  folderName: 'secretv1beta1',
  services: [
    {
      apiClass: 'API',
      methods: [
        {
          methodName: 'getSecret',
          protoName: 'GetSecret',
          paramsType: 'GetSecretRequest',
          returnType: 'Secret',
          returnTypeNamespace: '@scaleway-internal/sdk-secret/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSecrets',
          protoName: 'ListSecrets',
          paramsType: 'ListSecretsRequest',
          returnType: 'ListSecretsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-secret/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'Secret',
          listItemTypeNamespace: '@scaleway-internal/sdk-secret/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'getSecretVersion',
          protoName: 'GetSecretVersion',
          paramsType: 'GetSecretVersionRequest',
          returnType: 'SecretVersion',
          returnTypeNamespace: '@scaleway-internal/sdk-secret/v1beta1',
          isList: false,
          paginationType: 'none',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSecretVersions',
          protoName: 'ListSecretVersions',
          paramsType: 'ListSecretVersionsRequest',
          returnType: 'ListSecretVersionsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-secret/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'SecretVersion',
          listItemTypeNamespace: '@scaleway-internal/sdk-secret/v1beta1',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listTags',
          protoName: 'ListTags',
          paramsType: 'ListTagsRequest',
          returnType: 'ListTagsResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-secret/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'string',
          listItemTypeNamespace: 'string',
          isPrivate: false,
          description: '"',
        },
        {
          methodName: 'listSecretTypes',
          protoName: 'ListSecretTypes',
          paramsType: 'ListSecretTypesRequest',
          returnType: 'ListSecretTypesResponse',
          returnTypeNamespace: '@scaleway-internal/sdk-secret/v1beta1',
          isList: true,
          paginationType: 'offset',
          pageParamKey: 'page',
          listItemType: 'SecretType',
          listItemTypeNamespace: 'SecretType',
          isPrivate: false,
          description: '"',
        },
      ],
    },
  ],
} as const

export type QueriesMetadata = typeof queriesMetadata
