name: Run Tests

on: push

jobs:
  typecheck:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: pnpm/action-setup@v2.2.2
    - name: Use Node.js
      uses: actions/setup-node@v3.4.1
      with:
        node-version: 17
        check-latest: true
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run build
    - run: pnpm tsc --noEmit
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: pnpm/action-setup@v2.2.2
    - name: Use Node.js
      uses: actions/setup-node@v3.4.1
      with:
        node-version: 17
        check-latest: true
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run build
    - run: pnpm run lint
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [ '14', '16', '17' ]
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: pnpm/action-setup@v2.2.2
    - name: Use Node.js
      uses: actions/setup-node@v3.4.1
      with:
        node-version: ${{ matrix.node }}
        check-latest: true
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run build
    - run: pnpm run test:coverage
    - uses: codecov/codecov-action@v3.1.0
 