// biome-ignore-all  lint/complexity/noForEach: toFix

import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path/posix'
import type { FileToCreateWithNamespace } from './types.ts'

// Create namespace folders, generated, queries inside it and index.ts files
export const createNamespaceFilesAndFolders = ({
  allNamespaces,
  filesToCreate,
  directoryOfSrcFolder,
  generatedPath,
}: {
  allNamespaces: string[]
  filesToCreate: FileToCreateWithNamespace
  directoryOfSrcFolder: string
  generatedPath: string
}) => {
  // Create all queries files in generated folder, generate the generated/index.ts file and index.ts of the whole namespace
  allNamespaces.forEach(namespace => {
    const namespaceDir = join(directoryOfSrcFolder, namespace.toLowerCase())
    const generatedDir = join(namespaceDir, generatedPath)
    if (filesToCreate[namespace]) {
      // If the generated folder doesnt exist we create it
      if (!existsSync(namespaceDir)) {
        mkdirSync(namespaceDir, { recursive: true })
      }

      if (!existsSync(generatedDir)) {
        mkdirSync(generatedDir, { recursive: true })
      }

      filesToCreate[namespace]?.forEach(({ fileName, fileContent }) => {
        // Write the file
        writeFileSync(join(generatedDir, fileName), fileContent)
      })

      // Content of the `index.ts` in `src/NAMESPACE/generated`: Loop through all the files and populate the file with their names.
      const indexOfGenFolderContent = [
        '// This file is generated by scripts placed in `packages/queries/scripts/generate/` all modifications will be erased',
        ...filesToCreate[namespace].map(
          ({ fileName }) =>
            `export { ${fileName.split('.')[0]} } from "./${fileName.split('.')[0]}"`,
        ),
      ].join('\n')

      // We create the `index.ts` file in `src/NAMESPACE/generated`.
      writeFileSync(join(generatedDir, './index.ts'), indexOfGenFolderContent)
    }

    // Content of the `index.ts` in `src/NAMESPACE/`: refrom generated and custom dir. May be it can be removed but it allow usage of custom and generated by using namespace import
    // ex : import { Abuse } from '@shire/queries'... Abuse.getGenQuery() or Abuse.getCustomQuery()
    // WARNING : It can lead to error if the same name it provided multiple times I guess so care before enabling it
    // const indexOfNsContentLines = [
    //  '// This file is generated by a script placed in `tools/scripts/src/query-generation` all modifications will be erased',
    //  '/* eslint-disable eslint-comments/disable-enable-pair */',
    //  '/* eslint-disable no-restricted-syntax */',
    // ]
    // if (filesToCreate[namespace]) {
    //  indexOfNsContentLines.push(`export * from './${generatedPath}'`)
    // }
    // if (hasCustomDir) {
    //  indexOfNsContentLines.push(
    //    `export * from './${dirNameOfCustomQueriesInNS}'`,
    //  )
    // }
    //
    // writeFileSync(
    //  join(namespaceDir, 'index.ts'),
    //  indexOfNsContentLines.join('\n'),
    // )
  })
}
