import { lowerCaseFirstLetter } from './helpers.ts'

// It allows you to retrieve the file with its name `use + fileName + Query.ts` as well as its content from the transformed result information.
export function getQueryFileContent({
  apiPath,
  packageName,
  mainNamespace,
  methodParamsType,
  methodReturnType,
  apiToUse,
  methodToUse,
  isAll,
  isInfinite,
  fileName,
}: {
  apiPath: string
  packageName: string
  mainNamespace: string
  methodParamsType: string
  methodReturnType: string
  apiToUse: string
  methodToUse: string
  isAll: boolean
  fileName: string
  isInfinite: boolean
}) {
  const useAPI = `use${apiToUse}`
  const importKey = lowerCaseFirstLetter(apiToUse)
  const apiKey = importKey.replace('API', '')

  const defineImport = `import { ${useAPI} } from "${apiPath}/${importKey}"`
  const defineUsage = `const { ${apiKey} } = ${useAPI}()`

  if (isInfinite) {
    return [
      'import { useInfiniteDataLoader } from "@scaleway/use-dataloader"',
      'import type { UseInfiniteDataLoaderConfig } from "@scaleway/use-dataloader"',
      `import type { ${mainNamespace} } from "${packageName}"`,
      defineImport,
      '',
      '// This file is generated by @scaleway/generate-react-queries placed in https://github.com/scaleway/scaleway-sdk-js` all modifications will be erased',
      `export const ${fileName} = (params: ${methodParamsType}, pageParamKey: keyof typeof params, dataloaderConfig?: UseInfiniteDataLoaderConfig<${methodReturnType}, Error, typeof params, typeof pageParamKey>): ReturnType<typeof useInfiniteDataLoader<${methodReturnType}, Error, typeof params, typeof pageParamKey>> => {`,
      defineUsage,
      `const key = ["${apiKey}", "${methodToUse}", ...Object.entries(params).flat(3).sort()]`,
      '',
      `return useInfiniteDataLoader(key, (requestParams) => ${apiKey}.${methodToUse}(requestParams), params, pageParamKey, dataloaderConfig)`,
      '}',
    ].join('\n')
  }

  return [
    defineImport,
    'import { useDataLoader } from "@scaleway/use-dataloader"',
    'import type { UseDataLoaderConfig } from "@scaleway/use-dataloader"',
    `import type { ${mainNamespace} } from "${packageName}"`,
    '',
    '// This file is generated by @scaleway/generate-react-queries placed in https://github.com/scaleway/scaleway-sdk-js` all modifications will be erased',
    `export const ${fileName} = (${methodParamsType !== '' ? `params: ${methodParamsType}, ` : ''}dataloaderConfig?: UseDataLoaderConfig<${methodReturnType}, Error>): ReturnType<typeof useDataLoader<${methodReturnType}, Error>> => {`,
    defineUsage,
    `const key = ["${apiKey}", "${methodToUse}"${isAll ? ', "all"' : ''}, ${methodParamsType !== '' ? '...Object.entries(params).flat(3).sort()' : ''}]`,
    '',
    `return useDataLoader(key, () => ${apiKey}.${methodToUse}(${methodParamsType !== '' ? 'params' : ''})${isAll ? '.all()' : ''}, dataloaderConfig)`,
    '}',
  ].join('\n')
}
