import { lowerCaseFirstLetter } from './helpers.ts'

export function getReloadFileContent({ apiToUse }: { apiToUse: string }) {
  const importKey = lowerCaseFirstLetter(apiToUse)
  const apiKey = importKey.replace('API', '')
  const reloadFnName = `reload${apiToUse}`
  const asyncReloadFnName = `asyncReload${apiToUse}`
  const hookName = `use${apiToUse}Reload`

  return [
    'import { useDataLoaderContext } from "@scaleway/use-dataloader"',
    '',
    '// This file is generated by @scaleway/generate-react-queries placed in https://github.com/scaleway/scaleway-sdk-js` all modifications will be erased',
    `export const ${hookName} = (): { ${reloadFnName}: () => void; ${asyncReloadFnName}: () => Promise<void> } => {`,
    '  const dataLoader = useDataLoaderContext()',
    `  const keyPrefix = ["${apiKey}"]`,
    '',
    '  return {',
    `    ${reloadFnName}: () => dataLoader.reloadGroupActive(keyPrefix).catch(() => null),`,
    `    ${asyncReloadFnName}: () => dataLoader.reloadGroupActive(keyPrefix)`,
    '  }',
    '}',
  ].join('\n')
}
